import type { Country, Region } from "./data";

function toRegion([slug, nameZh, nameEn, typeZh, capitalZh]: string[]): Region {
  return { slug, nameZh, nameEn, typeZh, capitalZh };
}

const pendingParties = [
  { shortName: "TBD", nameZh: "主要党派待核验", familyZh: "待接入最近一次选举与议会席位数据", color: "#667085" },
];

function commonEconomicMetrics(currency: string) {
  return [
    { label: "欧盟成员", value: "待按国家核验" },
    { label: "北约成员", value: "待按国家核验" },
    { label: "货币", value: currency },
    { label: "经济数据口径", value: "各国统计部门最新发布为主" },
  ];
}

export const additionalCountries: Country[] = [
  {
    slug: "germany",
    iso2: "DE",
    nameZh: "德国",
    nameEn: "Germany",
    capitalZh: "柏林",
    polityZh: "联邦议会共和制",
    parliamentZh: "两院结构：联邦议院与联邦参议院",
    currency: "EUR",
    euMember: true,
    natoMember: true,
    headOfGovernmentZh: "待核验",
    headOfStateZh: "待核验",
    governmentZh: "政府组成、执政党和部长名单待接入德国官方来源核验。",
    governmentNoteZh: "正式版以德国联邦政府、联邦议院和联邦选举管理机构资料为准。",
    summaryZh: "德国是十国范围中的核心经济体和欧盟政策枢纽，适合作为产业链、能源、贸易和对华经贸关系的基准参照。",
    parties: pendingParties,
    regions: [
      ["baden-wurttemberg", "巴登-符腾堡州", "Baden-Wurttemberg", "州", "斯图加特"],
      ["bavaria", "巴伐利亚州", "Bavaria", "州", "慕尼黑"],
      ["berlin", "柏林", "Berlin", "州 / 城市州", "柏林"],
      ["brandenburg", "勃兰登堡州", "Brandenburg", "州", "波茨坦"],
      ["bremen", "不来梅", "Bremen", "州 / 城市州", "不来梅"],
      ["hamburg", "汉堡", "Hamburg", "州 / 城市州", "汉堡"],
      ["hesse", "黑森州", "Hesse", "州", "威斯巴登"],
      ["lower-saxony-de", "下萨克森州", "Lower Saxony", "州", "汉诺威"],
      ["mecklenburg-vorpommern", "梅克伦堡-前波美拉尼亚州", "Mecklenburg-Vorpommern", "州", "什未林"],
      ["north-rhine-westphalia", "北莱茵-威斯特法伦州", "North Rhine-Westphalia", "州", "杜塞尔多夫"],
      ["rhineland-palatinate", "莱茵兰-普法尔茨州", "Rhineland-Palatinate", "州", "美因茨"],
      ["saarland", "萨尔州", "Saarland", "州", "萨尔布吕肯"],
      ["saxony", "萨克森州", "Saxony", "州", "德累斯顿"],
      ["saxony-anhalt", "萨克森-安哈尔特州", "Saxony-Anhalt", "州", "马格德堡"],
      ["schleswig-holstein", "石勒苏益格-荷尔斯泰因州", "Schleswig-Holstein", "州", "基尔"],
      ["thuringia", "图林根州", "Thuringia", "州", "埃尔福特"],
    ].map(toRegion),
    economicMetrics: commonEconomicMetrics("EUR"),
    chinaTradeNote: "第一版先建立贸易、汽车、机械、化工、绿色技术和供应链合作的资料框架；具体金额以德国联邦统计局和官方贸易数据为主。",
    chinaProjects: [
      { name: "中德制造业与汽车供应链合作", sector: "汽车 / 制造业", status: "待量化", note: "先作为经贸专题入口，后续按企业、地区和年份拆分。" },
      { name: "绿色技术与能源转型合作", sector: "能源 / 技术", status: "待核验", note: "后续区分政策合作、企业项目和贸易品类。" },
    ],
    sources: [
      { label: "Federal Government", url: "https://www.bundesregierung.de/" },
      { label: "Federal Statistical Office", url: "https://www.destatis.de/EN/Home/_node.html" },
    ],
  },
  {
    slug: "romania",
    iso2: "RO",
    nameZh: "罗马尼亚",
    nameEn: "Romania",
    capitalZh: "布加勒斯特",
    polityZh: "半总统制共和制",
    parliamentZh: "两院制：众议院与参议院",
    currency: "RON",
    euMember: true,
    natoMember: true,
    headOfGovernmentZh: "待核验",
    headOfStateZh: "待核验",
    governmentZh: "政府组成和执政联盟待接入罗马尼亚官方来源核验。",
    governmentNoteZh: "正式版以罗马尼亚政府、议会、中央选举局和国家统计局资料为准。",
    summaryZh: "罗马尼亚是黑海、巴尔干和中东欧产业转移的重要交汇点，适合纳入能源、港口、农业、制造业和对华贸易分析。",
    parties: pendingParties,
    regions: [
      ["alba", "阿尔巴县", "Alba County", "县", "阿尔巴尤利亚"],
      ["arad", "阿拉德县", "Arad County", "县", "阿拉德"],
      ["arges", "阿尔杰什县", "Arges County", "县", "皮特什蒂"],
      ["bacau", "巴克乌县", "Bacau County", "县", "巴克乌"],
      ["bihor", "比霍尔县", "Bihor County", "县", "奥拉迪亚"],
      ["bistrita-nasaud", "比斯特里察-讷瑟乌德县", "Bistrita-Nasaud County", "县", "比斯特里察"],
      ["botosani", "博托沙尼县", "Botosani County", "县", "博托沙尼"],
      ["brasov", "布拉索夫县", "Brasov County", "县", "布拉索夫"],
      ["braila", "布勒伊拉县", "Braila County", "县", "布勒伊拉"],
      ["bucharest", "布加勒斯特", "Bucharest", "首都直辖市", "布加勒斯特"],
      ["buzau", "布泽乌县", "Buzau County", "县", "布泽乌"],
      ["caras-severin", "卡拉什-塞维林县", "Caras-Severin County", "县", "雷希察"],
      ["calarasi", "克勒拉希县", "Calarasi County", "县", "克勒拉希"],
      ["cluj", "克卢日县", "Cluj County", "县", "克卢日-纳波卡"],
      ["constanta", "康斯坦察县", "Constanta County", "县", "康斯坦察"],
      ["covasna", "科瓦斯纳县", "Covasna County", "县", "圣格奥尔基"],
      ["dambovita", "登博维察县", "Dambovita County", "县", "特尔戈维什泰"],
      ["dolj", "多尔日县", "Dolj County", "县", "克拉约瓦"],
      ["galati", "加拉茨县", "Galati County", "县", "加拉茨"],
      ["giurgiu", "久尔久县", "Giurgiu County", "县", "久尔久"],
      ["gorj", "戈尔日县", "Gorj County", "县", "特尔古日乌"],
      ["harghita", "哈尔吉塔县", "Harghita County", "县", "米耶尔库雷亚丘克"],
      ["hunedoara", "胡内多阿拉县", "Hunedoara County", "县", "德瓦"],
      ["ialomita", "雅洛米察县", "Ialomita County", "县", "斯洛博齐亚"],
      ["iasi", "雅西县", "Iasi County", "县", "雅西"],
      ["ilfov", "伊尔福夫县", "Ilfov County", "县", "布夫泰亚"],
      ["maramures", "马拉穆列什县", "Maramures County", "县", "巴亚马雷"],
      ["mehedinti", "梅赫丁茨县", "Mehedinti County", "县", "德罗贝塔- Turnu Severin"],
      ["mures", "穆列什县", "Mures County", "县", "特尔古穆列什"],
      ["neamt", "尼亚姆茨县", "Neamt County", "县", "皮亚特拉尼亚姆茨"],
      ["olt", "奥尔特县", "Olt County", "县", "斯拉蒂纳"],
      ["prahova", "普拉霍瓦县", "Prahova County", "县", "普洛耶什蒂"],
      ["satu-mare", "萨图马雷县", "Satu Mare County", "县", "萨图马雷"],
      ["salaj", "瑟拉日县", "Salaj County", "县", "扎勒乌"],
      ["sibiu", "锡比乌县", "Sibiu County", "县", "锡比乌"],
      ["suceava", "苏恰瓦县", "Suceava County", "县", "苏恰瓦"],
      ["teleorman", "特列奥尔曼县", "Teleorman County", "县", "亚历山德里亚"],
      ["timis", "蒂米什县", "Timis County", "县", "蒂米什瓦拉"],
      ["tulcea", "图尔恰县", "Tulcea County", "县", "图尔恰"],
      ["vaslui", "瓦斯卢伊县", "Vaslui County", "县", "瓦斯卢伊"],
      ["valcea", "沃尔恰县", "Valcea County", "县", "勒姆尼库沃尔恰"],
      ["vrancea", "弗朗恰县", "Vrancea County", "县", "福克沙尼"],
    ].map(toRegion),
    economicMetrics: commonEconomicMetrics("RON"),
    chinaTradeNote: "第一版重点预留港口、能源、农业、制造业和基础设施合作维度；具体贸易额和项目状态以罗马尼亚官方统计与项目来源核验。",
    chinaProjects: [
      { name: "黑海港口与物流通道", sector: "港口 / 物流", status: "待核验", note: "适合作为罗马尼亚对华经贸入口之一。" },
      { name: "制造业与农业贸易", sector: "贸易 / 制造业", status: "待量化", note: "后续按商品类别和年度贸易额拆分。" },
    ],
    sources: [
      { label: "Government of Romania", url: "https://gov.ro/en" },
      { label: "National Institute of Statistics", url: "https://insse.ro/cms/en" },
    ],
  },
  {
    slug: "slovenia",
    iso2: "SI",
    nameZh: "斯洛文尼亚",
    nameEn: "Slovenia",
    capitalZh: "卢布尔雅那",
    polityZh: "议会共和制",
    parliamentZh: "两院结构：国民议会与国民委员会",
    currency: "EUR",
    euMember: true,
    natoMember: true,
    headOfGovernmentZh: "待核验",
    headOfStateZh: "待核验",
    governmentZh: "政府组成和执政党待接入斯洛文尼亚官方来源核验。",
    governmentNoteZh: "正式版以政府、国家选举委员会和统计局资料为准。",
    summaryZh: "斯洛文尼亚体量较小但位处阿尔卑斯-亚得里亚交通和供应链节点，适合纳入港口、物流、制造业和欧盟内部比较。",
    parties: pendingParties,
    regions: [
      ["eastern-slovenia", "东斯洛文尼亚凝聚区", "Eastern Slovenia Cohesion Region", "凝聚区 / ADM1", "马里博尔"],
      ["western-slovenia", "西斯洛文尼亚凝聚区", "Western Slovenia Cohesion Region", "凝聚区 / ADM1", "卢布尔雅那"],
    ].map(toRegion),
    economicMetrics: commonEconomicMetrics("EUR"),
    chinaTradeNote: "第一版重点关注科佩尔港、物流通道、机械制造和高附加值贸易；后续接入斯洛文尼亚统计局与海关贸易数据。",
    chinaProjects: [
      { name: "科佩尔港与亚得里亚物流", sector: "港口 / 物流", status: "待核验", note: "用于观察中欧物流和海港节点。" },
      { name: "机械与高附加值制造贸易", sector: "贸易 / 制造业", status: "待量化", note: "后续按商品类别拆分。" },
    ],
    sources: [
      { label: "Government of Slovenia", url: "https://www.gov.si/en/" },
      { label: "Statistical Office of Slovenia", url: "https://www.stat.si/StatWeb/en" },
    ],
  },
  {
    slug: "serbia",
    iso2: "RS",
    nameZh: "塞尔维亚",
    nameEn: "Serbia",
    capitalZh: "贝尔格莱德",
    polityZh: "议会共和制",
    parliamentZh: "一院制：国民议会",
    currency: "RSD",
    euMember: false,
    natoMember: false,
    headOfGovernmentZh: "待核验",
    headOfStateZh: "待核验",
    governmentZh: "政府组成和执政党待接入塞尔维亚官方来源核验。",
    governmentNoteZh: "正式版以塞尔维亚政府、共和国选举委员会和统计局资料为准；科索沃相关边界与政治表述需单独制定口径。",
    summaryZh: "塞尔维亚是中国在巴尔干基础设施、矿业、能源和制造业合作中的关键案例，也是非欧盟国家比较的重要样本。",
    parties: pendingParties,
    regions: [
      ["belgrade", "贝尔格莱德市", "City of Belgrade", "城市", "贝尔格莱德"],
      ["bor", "博尔州", "Bor District", "州 / 区", "博尔"],
      ["branicevo", "布拉尼切沃州", "Branicevo District", "州 / 区", "波扎雷瓦茨"],
      ["jablanica", "雅布拉尼察州", "Jablanica District", "州 / 区", "莱斯科瓦茨"],
      ["kolubara", "科卢巴拉州", "Kolubara District", "州 / 区", "瓦列沃"],
      ["macva", "马奇瓦州", "Macva District", "州 / 区", "沙巴茨"],
      ["moravica", "莫拉维察州", "Moravica District", "州 / 区", "查查克"],
      ["nisava", "尼沙瓦州", "Nisava District", "州 / 区", "尼什"],
      ["pcinja", "普奇尼亚州", "Pcinja District", "州 / 区", "弗拉涅"],
      ["pirot", "皮罗特州", "Pirot District", "州 / 区", "皮罗特"],
      ["podunavlje", "波杜那瓦列州", "Podunavlje District", "州 / 区", "斯梅代雷沃"],
      ["pomoravlje", "波莫拉夫列州", "Pomoravlje District", "州 / 区", "亚戈迪纳"],
      ["rasina", "拉西纳州", "Rasina District", "州 / 区", "克鲁舍瓦茨"],
      ["raska", "拉什卡州", "Raska District", "州 / 区", "克拉列沃"],
      ["sumadija", "舒马迪亚州", "Sumadija District", "州 / 区", "克拉古耶瓦茨"],
      ["toplica", "托普利察州", "Toplica District", "州 / 区", "普罗库普列"],
      ["zajecar", "扎耶查尔州", "Zajecar District", "州 / 区", "扎耶查尔"],
      ["zlatibor", "兹拉蒂博尔州", "Zlatibor District", "州 / 区", "乌日策"],
      ["north-backa", "北巴奇卡州", "North Backa District", "州 / 区", "苏博蒂察"],
      ["central-banat", "中巴纳特州", "Central Banat District", "州 / 区", "兹雷尼亚宁"],
      ["north-banat", "北巴纳特州", "North Banat District", "州 / 区", "基金达"],
      ["south-banat", "南巴纳特州", "South Banat District", "州 / 区", "潘切沃"],
      ["west-backa", "西巴奇卡州", "West Backa District", "州 / 区", "松博尔"],
      ["south-backa", "南巴奇卡州", "South Backa District", "州 / 区", "诺维萨德"],
      ["srem", "斯雷姆州", "Srem District", "州 / 区", "斯雷姆斯卡米特罗维察"],
    ].map(toRegion),
    economicMetrics: commonEconomicMetrics("RSD"),
    chinaTradeNote: "第一版重点关注铁路、公路、矿业、钢铁、能源和制造业项目；需对项目金额、融资、承包方和状态逐项核验。",
    chinaProjects: [
      { name: "匈塞铁路塞尔维亚段", sector: "铁路 / 基础设施", status: "待核验", note: "适合作为中国-巴尔干基础设施合作主案例。" },
      { name: "矿业、钢铁与能源项目", sector: "矿业 / 能源 / 制造业", status: "待核验", note: "后续需按企业、地区和项目状态拆分。" },
    ],
    sources: [
      { label: "Government of Serbia", url: "https://www.srbija.gov.rs/" },
      { label: "Statistical Office of Serbia", url: "https://www.stat.gov.rs/en-US/" },
    ],
  },
  {
    slug: "austria",
    iso2: "AT",
    nameZh: "奥地利",
    nameEn: "Austria",
    capitalZh: "维也纳",
    polityZh: "联邦议会共和制",
    parliamentZh: "两院制：国民议会与联邦议会",
    currency: "EUR",
    euMember: true,
    natoMember: false,
    headOfGovernmentZh: "待核验",
    headOfStateZh: "待核验",
    governmentZh: "政府组成和执政党待接入奥地利官方来源核验。",
    governmentNoteZh: "正式版以奥地利联邦政府、内政部选举资料和统计局资料为准。",
    summaryZh: "奥地利位于德语区和中东欧之间，是金融、制造、交通和欧盟邻近政策比较中的重要桥梁国家。",
    parties: pendingParties,
    regions: [
      ["burgenland", "布尔根兰州", "Burgenland", "州", "艾森施塔特"],
      ["carinthia", "克恩顿州", "Carinthia", "州", "克拉根福"],
      ["lower-austria", "下奥地利州", "Lower Austria", "州", "圣珀尔滕"],
      ["upper-austria", "上奥地利州", "Upper Austria", "州", "林茨"],
      ["salzburg", "萨尔茨堡州", "Salzburg", "州", "萨尔茨堡"],
      ["styria", "施泰尔马克州", "Styria", "州", "格拉茨"],
      ["tyrol", "蒂罗尔州", "Tyrol", "州", "因斯布鲁克"],
      ["vorarlberg", "福拉尔贝格州", "Vorarlberg", "州", "布雷根茨"],
      ["vienna", "维也纳", "Vienna", "州 / 首都", "维也纳"],
    ].map(toRegion),
    economicMetrics: commonEconomicMetrics("EUR"),
    chinaTradeNote: "第一版重点关注机械、环保技术、交通物流、金融服务和旅游相关经贸联系；具体数据以奥地利统计局和官方贸易数据为主。",
    chinaProjects: [
      { name: "机械与环保技术贸易", sector: "贸易 / 技术", status: "待量化", note: "后续按商品类别、企业和年度数据拆分。" },
      { name: "中欧交通与物流节点", sector: "物流 / 服务业", status: "待核验", note: "可作为区域供应链比较维度。" },
    ],
    sources: [
      { label: "Federal Chancellery", url: "https://www.bundeskanzleramt.gv.at/en.html" },
      { label: "Statistics Austria", url: "https://www.statistik.at/en" },
    ],
  },
  {
    slug: "croatia",
    iso2: "HR",
    nameZh: "克罗地亚",
    nameEn: "Croatia",
    capitalZh: "萨格勒布",
    polityZh: "议会共和制",
    parliamentZh: "一院制：克罗地亚议会",
    currency: "EUR",
    euMember: true,
    natoMember: true,
    headOfGovernmentZh: "待核验",
    headOfStateZh: "待核验",
    governmentZh: "政府组成和执政党待接入克罗地亚官方来源核验。",
    governmentNoteZh: "正式版以克罗地亚政府、选举委员会和统计局资料为准。",
    summaryZh: "克罗地亚连接中欧、巴尔干和亚得里亚海，是港口、旅游、能源、物流和对华基础设施合作观察的重要样本。",
    parties: pendingParties,
    regions: [
      ["zagreb-county", "萨格勒布县", "Zagreb County", "县", "萨格勒布"],
      ["krapina-zagorje", "克拉皮纳-扎戈列县", "Krapina-Zagorje County", "县", "克拉皮纳"],
      ["sisak-moslavina", "锡萨克-莫斯拉维纳县", "Sisak-Moslavina County", "县", "锡萨克"],
      ["karlovac", "卡尔洛瓦茨县", "Karlovac County", "县", "卡尔洛瓦茨"],
      ["varazdin", "瓦拉日丁县", "Varazdin County", "县", "瓦拉日丁"],
      ["koprivnica-krizevci", "科普里夫尼察-克里热夫齐县", "Koprivnica-Krizevci County", "县", "科普里夫尼察"],
      ["bjelovar-bilogora", "别洛瓦尔-比洛戈拉县", "Bjelovar-Bilogora County", "县", "别洛瓦尔"],
      ["primorje-gorski-kotar", "滨海和山区县", "Primorje-Gorski Kotar County", "县", "里耶卡"],
      ["lika-senj", "利卡-塞尼县", "Lika-Senj County", "县", "戈斯皮奇"],
      ["virovitica-podravina", "维罗维蒂察-波德拉维纳县", "Virovitica-Podravina County", "县", "维罗维蒂察"],
      ["pozega-slavonia", "波热加-斯拉沃尼亚县", "Pozega-Slavonia County", "县", "波热加"],
      ["brod-posavina", "布罗德-波萨维纳县", "Brod-Posavina County", "县", "斯拉沃尼亚布罗德"],
      ["zadar", "扎达尔县", "Zadar County", "县", "扎达尔"],
      ["osijek-baranja", "奥西耶克-巴拉尼亚县", "Osijek-Baranja County", "县", "奥西耶克"],
      ["sibenik-knin", "希贝尼克-克宁县", "Sibenik-Knin County", "县", "希贝尼克"],
      ["vukovar-srijem", "武科瓦尔-斯里耶姆县", "Vukovar-Srijem County", "县", "武科瓦尔"],
      ["split-dalmatia", "斯普利特-达尔马提亚县", "Split-Dalmatia County", "县", "斯普利特"],
      ["istria", "伊斯特拉县", "Istria County", "县", "帕津"],
      ["dubrovnik-neretva", "杜布罗夫尼克-内雷特瓦县", "Dubrovnik-Neretva County", "县", "杜布罗夫尼克"],
      ["medimurje", "梅吉穆列县", "Medimurje County", "县", "查科韦茨"],
      ["zagreb-city", "萨格勒布市", "City of Zagreb", "市 / 首都", "萨格勒布"],
    ].map(toRegion),
    economicMetrics: commonEconomicMetrics("EUR"),
    chinaTradeNote: "第一版重点关注亚得里亚港口、旅游、交通基础设施、能源和商品贸易；项目状态需逐项核验。",
    chinaProjects: [
      { name: "佩列沙茨大桥相关基础设施案例", sector: "基础设施 / 交通", status: "待核验", note: "适合作为中国企业在克罗地亚基础设施合作案例入口。" },
      { name: "港口、旅游与商品贸易", sector: "服务业 / 贸易", status: "待量化", note: "后续按港口、地区和年度贸易数据拆分。" },
    ],
    sources: [
      { label: "Government of Croatia", url: "https://vlada.gov.hr/" },
      { label: "Croatian Bureau of Statistics", url: "https://dzs.gov.hr/" },
    ],
  },
];
