import { modelCards } from "@/lib/modelFramework";
import { PLATFORM_BASE_URL, PLATFORM_VERSION } from "@/lib/releaseMetadata";
import { panelGate } from "@/lib/panelData";
import type { AnalysisSkill, AnalysisSkillCategory } from "@/types/AnalysisSkill";

export const analysisCategoryLabels: Record<AnalysisSkillCategory, string> = {
  composite_indicators: "Composite Indicators",
  panel_econometrics: "Panel Econometrics",
  macro_time_series: "Macro Time Series",
  event_analysis: "Event Analysis",
  network_analysis: "Network Analysis",
  bayesian_analysis: "Bayesian Analysis",
};

const sharedOutputSchema = ["result", "drivers", "diagnostics", "data_trace", "limitations"];
const registryCitation = `${PLATFORM_BASE_URL}methodology/ (Analysis Skills Registry, ${PLATFORM_VERSION})`;

export const activeCompositeSkills: AnalysisSkill[] = modelCards.map((card) => ({
  skill_id: card.model_id,
  name: card.name_zh,
  category: "composite_indicators",
  description: card.purpose,
  required_data: card.inputs.map((input) => input.indicator_id),
  optional_data: card.reserved_inputs,
  parameters: [card.formula_version, card.weight_version],
  minimum_observations: card.inputs.length,
  supported_spatial_level: ["country"],
  supported_frequency: ["annual"],
  calculation_mode: "active",
  output_schema: sharedOutputSchema,
  diagnostics: ["data_completeness", "year_alignment", "observation_trace", "validation_gate"],
  limitations: card.limitations,
  citation: registryCitation,
}));

export const futureAnalysisSkills: AnalysisSkill[] = [
  {
    skill_id: "panel_econometrics",
    name: "Panel Econometrics",
    category: "panel_econometrics",
    description: "基于 2015–2025 官方年度面板运行 Pooled OLS、国家固定效应和国家加年份固定效应。",
    required_data: [">=8_countries", ">=8_years", "comparable_key_variables", "traceable_official_observations"],
    optional_data: ["country_fixed_effects", "time_fixed_effects", "clustered_standard_errors"],
    parameters: ["estimator", "fixed_effects", "standard_error_method"],
    minimum_observations: 64,
    supported_spatial_level: ["country"],
    supported_frequency: ["annual"],
    calculation_mode: panelGate.status === "passed" ? "active" : "data_building",
    output_schema: ["coefficients", "standard_errors", "diagnostics", "data_trace", "limitations"],
    diagnostics: ["sample_coverage", "multicollinearity", "residual_checks", "specification_notes"],
    limitations: ["association 不等于 causality；固定效应本身不提供因果识别。", "部分可比口径和 pending 观测不会进入估计。", "第一版 p 值与置信区间使用大样本近似。"],
    citation: registryCitation,
  },
  {
    skill_id: "var_svar",
    name: "VAR / SVAR",
    category: "macro_time_series",
    description: "宏观时间序列动态与结构冲击分析接口；当前不估计冲击响应。",
    required_data: ["consistent_time_series", "documented_frequency", "sufficient_lags"],
    optional_data: ["external_instruments", "structural_restrictions"],
    parameters: ["lag_order", "identification", "sample_window"],
    minimum_observations: 40,
    supported_spatial_level: ["country"],
    supported_frequency: ["quarterly", "monthly"],
    calculation_mode: "blocked",
    output_schema: ["impulse_response", "forecast_error_variance", "diagnostics", "data_trace", "limitations"],
    diagnostics: ["stationarity", "lag_selection", "stability", "residual_autocorrelation"],
    limitations: ["blocked_by_frequency。", "至少需要 40 个有效季度或月度观测，并通过平稳性、滞后选择和稳定性诊断。"],
    citation: registryCitation,
  },
  {
    skill_id: "event_study",
    name: "Event Study",
    category: "event_analysis",
    description: "事件窗口与结果变量变化分析接口；事件编码本身不构成因果识别。",
    required_data: ["verified_event_date", "pre_post_outcome_series"],
    optional_data: ["comparison_group", "multiple_event_controls"],
    parameters: ["event_window", "baseline_window", "comparison_design"],
    minimum_observations: 20,
    supported_spatial_level: ["country", "region"],
    supported_frequency: ["daily", "monthly", "quarterly"],
    calculation_mode: "registry_only",
    output_schema: ["event_time_estimates", "confidence_intervals", "diagnostics", "data_trace", "limitations"],
    diagnostics: ["pre_trends", "overlapping_events", "window_coverage"],
    limitations: ["不在 v1.1 运行。", "低置信度或待编码事件不得进入估计。"],
    citation: registryCitation,
  },
  {
    skill_id: "network_dependency",
    name: "Network Dependency",
    category: "network_analysis",
    description: "双边贸易边、伙伴集中度与中心性分析；通用伙伴边尚未完成，因此保持数据建设中。",
    required_data: ["directed_edges", "comparable_edge_weights", "time_reference"],
    optional_data: ["sector_nodes", "project_links", "regional_nodes"],
    parameters: ["network_definition", "edge_weight", "time_window"],
    minimum_observations: 30,
    supported_spatial_level: ["country"],
    supported_frequency: ["annual"],
    calculation_mode: "data_building",
    output_schema: ["network_summary", "node_metrics", "diagnostics", "data_trace", "limitations"],
    diagnostics: ["edge_coverage", "weight_comparability", "isolated_nodes"],
    limitations: ["当前对华聚合序列不冒充完整双边贸易网络。", "中心性不等于政治影响，集中度不等于风险，中国份额不等于政治依赖。"],
    citation: registryCitation,
  },
  {
    skill_id: "bayesian_var",
    name: "Bayesian VAR",
    category: "bayesian_analysis",
    description: "贝叶斯宏观动态分析接口；当前不设置先验、不生成后验结果。",
    required_data: ["consistent_time_series", "documented_vintages"],
    optional_data: ["prior_calibration", "external_forecasts"],
    parameters: ["prior", "lag_order", "sample_window"],
    minimum_observations: 60,
    supported_spatial_level: ["country"],
    supported_frequency: ["quarterly", "monthly"],
    calculation_mode: "blocked",
    output_schema: ["posterior_summary", "credible_intervals", "diagnostics", "data_trace", "limitations"],
    diagnostics: ["prior_sensitivity", "convergence", "posterior_predictive_checks"],
    limitations: ["blocked_by_frequency；等待 VAR 高频数据层成熟。", "不得把先验设定隐藏为客观事实。"],
    citation: registryCitation,
  },
  {
    skill_id: "causal_policy_analysis",
    name: "Causal Policy Analysis",
    category: "panel_econometrics",
    description: "政策评估设计登记接口；只有识别假设和对照组成立时才讨论因果效应。",
    required_data: ["verified_policy_timing", "outcome_series", "comparison_design"],
    optional_data: ["treatment_intensity", "regional_controls"],
    parameters: ["design", "treatment_definition", "estimation_window"],
    minimum_observations: 50,
    supported_spatial_level: ["country", "region"],
    supported_frequency: ["annual", "quarterly", "monthly"],
    calculation_mode: "registry_only",
    output_schema: ["effect_estimates", "uncertainty", "diagnostics", "data_trace", "limitations"],
    diagnostics: ["identification_assumptions", "pre_trends", "placebo_tests", "robustness"],
    limitations: ["不在 v1.1 运行。", "事件关联与时间先后不能替代因果识别。"],
    citation: registryCitation,
  },
];

export const analysisSkills = [...activeCompositeSkills, ...futureAnalysisSkills];
