export type BoundaryFeatureMap = Record<string, Record<string, string>>;

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const withBasePath = (path: string) => `${basePath}${path}`;

export const countryGeoJsonFiles: Record<string, string> = {
  germany: withBasePath("/geo/adm1/germany.geojson"),
  poland: withBasePath("/geo/adm1/poland.geojson"),
  hungary: withBasePath("/geo/adm1/hungary.geojson"),
  romania: withBasePath("/geo/adm1/romania.geojson"),
  czechia: withBasePath("/geo/adm1/czechia.geojson"),
  slovakia: withBasePath("/geo/adm1/slovakia.geojson"),
  slovenia: withBasePath("/geo/adm1/slovenia.geojson"),
  serbia: withBasePath("/geo/adm1/serbia.geojson"),
  austria: withBasePath("/geo/adm1/austria.geojson"),
  croatia: withBasePath("/geo/adm1/croatia.geojson"),
};

export const boundaryFeatureToRegionSlug: BoundaryFeatureMap = {
  germany: {
    "Baden-Württemberg": "baden-wurttemberg",
    Bayern: "bavaria",
    Berlin: "berlin",
    Brandenburg: "brandenburg",
    Bremen: "bremen",
    Hamburg: "hamburg",
    Hessen: "hesse",
    "Mecklenburg-Vorpommern": "mecklenburg-vorpommern",
    Niedersachsen: "lower-saxony-de",
    "Nordrhein-Westfalen": "north-rhine-westphalia",
    "Rheinland-Pfalz": "rhineland-palatinate",
    Saarland: "saarland",
    Sachsen: "saxony",
    "Sachsen-Anhalt": "saxony-anhalt",
    "Schleswig-Holstein": "schleswig-holstein",
    Thüringen: "thuringia",
  },
  poland: {
    "Lower Silesian Voivodeship": "lower-silesian",
    "Kuyavian-Pomeranian Voivodeship": "kuyavian-pomeranian",
    "Lublin Voivodeship": "lublin",
    "Lubusz Voivodeship": "lubusz",
    "Łódź Voivodeship": "lodz",
    "Lesser Poland Voivodeship": "lesser-poland",
    "Masovian Voivodeship": "masovian",
    "Opole Voivodeship": "opole",
    "Subcarpathian Voivodeship": "subcarpathian",
    "Podlaskie Voivodeship": "podlaskie",
    "Pomeranian Voivodeship": "pomeranian",
    "Silesian Voivodeship": "silesian",
    "Świętokrzyskie Voivodeship": "swietokrzyskie",
    "Warmian-Masurian Voivodeship": "warmian-masurian",
    "Greater Poland Voivodeship": "greater-poland",
    "West Pomeranian Voivodeship": "west-pomeranian",
  },
  hungary: {
    "Bács-Kiskun": "bacs-kiskun",
    Baranya: "baranya",
    Békés: "bekes",
    "Borsod-Abaúj-Zemplén": "borsod-abauj-zemplen",
    "Csongrád-Csanád": "csongrad-csanad",
    Fejér: "fejer",
    "Győr-Moson-Sopron": "gyor-moson-sopron",
    "Hajdú-Bihar": "hajdu-bihar",
    Heves: "heves",
    "Jász-Nagykun-Szolnok": "jasz-nagykun-szolnok",
    "Komárom-Esztergom": "komarom-esztergom",
    Nógrád: "nograd",
    Pest: "pest",
    Somogy: "somogy",
    "Szabolcs-Szatmár-Bereg": "szabolcs-szatmar-bereg",
    Tolna: "tolna",
    Vas: "vas",
    Veszprém: "veszprem",
    Zala: "zala",
  },
  romania: {
    ALBA: "alba",
    ARAD: "arad",
    ARGES: "arges",
    BACAU: "bacau",
    BIHOR: "bihor",
    "BISTRITA-NASAUD": "bistrita-nasaud",
    BOTOSANI: "botosani",
    BRAILA: "braila",
    BRASOV: "brasov",
    BUZAU: "buzau",
    CALARASI: "calarasi",
    "CARAS-SEVERIN": "caras-severin",
    CLUJ: "cluj",
    CONSTANTA: "constanta",
    COVASNA: "covasna",
    DAMBOVITA: "dambovita",
    DOLJ: "dolj",
    GALATI: "galati",
    GIURGIU: "giurgiu",
    GORJ: "gorj",
    HARGHITA: "harghita",
    HUNEDOARA: "hunedoara",
    IALOMITA: "ialomita",
    IASI: "iasi",
    ILFOV: "ilfov",
    MARAMURES: "maramures",
    MEHEDINTI: "mehedinti",
    BUCURESTI: "bucharest",
    MURES: "mures",
    NEAMT: "neamt",
    OLT: "olt",
    PRAHOVA: "prahova",
    SALAJ: "salaj",
    "SATU MARE": "satu-mare",
    SIBIU: "sibiu",
    SUCEAVA: "suceava",
    TELEORMAN: "teleorman",
    TIMIS: "timis",
    TULCEA: "tulcea",
    VALCEA: "valcea",
    VASLUI: "vaslui",
    VRANCEA: "vrancea",
  },
  czechia: {
    "Hlavní město Praha": "prague",
    "Středočeský kraj": "central-bohemian",
    "Jihočeský kraj": "south-bohemian",
    "Plzeňský kraj": "plzen",
    "Karlovarský kraj": "karlovy-vary",
    "Ústecký kraj": "usti",
    "Liberecký kraj": "liberec",
    "Královéhradecký kraj": "hradec-kralove",
    "Pardubický kraj": "pardubice",
    Vysočina: "vysocina",
    "Jihomoravský kraj": "south-moravian",
    "Olomoucký kraj": "olomouc",
    "Zlínský kraj": "zlin",
    "Moravskoslezský kraj": "moravian-silesian",
  },
  slovakia: {
    "Region of Bratislava": "bratislava",
    "Region of Trnava": "trnava",
    "Region of Trenčín": "trencin",
    "Region of Nitra": "nitra",
    "Region of Žilina": "zilina",
    "Region of Banská Bystrica": "banska-bystrica",
    "Region of Prešov": "presov",
    "Region of Košice": "kosice",
  },
  slovenia: {
    Vzhodna: "eastern-slovenia",
    "Zahodna Slovenija": "western-slovenia",
  },
  serbia: {
    "Syrmia District": "srem",
    "South Banat District": "south-banat",
    "North Banat District": "north-banat",
    "North Backa District": "north-backa",
    "Central Banat District": "central-banat",
    "West Backa District": "west-backa",
    "South Backa District": "south-backa",
    Belgrade: "belgrade",
    "Bor District": "bor",
    "Macva District": "macva",
    "Pcinja District": "pcinja",
    "Kolubara District": "kolubara",
    "Podunavlje District": "podunavlje",
    "Branicevo District": "branicevo",
    "Sumadija District": "sumadija",
    "Pomoravlje District": "pomoravlje",
    "Moravica District": "moravica",
    "Zajecar District": "zajecar",
    "Zlatibor District": "zlatibor",
    "Raska District": "raska",
    "Pirot District": "pirot",
    "Jablanica District": "jablanica",
    "Toplica District": "toplica",
    "Nisava District": "nisava",
    "Rasina District": "rasina",
  },
  austria: {
    Burgenland: "burgenland",
    Kärnten: "carinthia",
    Niederösterreich: "lower-austria",
    Oberösterreich: "upper-austria",
    Salzburg: "salzburg",
    Steiermark: "styria",
    Tirol: "tyrol",
    Vorarlberg: "vorarlberg",
    Wien: "vienna",
  },
  croatia: {
    "Osijek-Baranja": "osijek-baranja",
    "Vukovar-Syrmia": "vukovar-srijem",
    "Brod-Posavina": "brod-posavina",
    "Virovitica-Podravina": "virovitica-podravina",
    "Požega-Slavonia": "pozega-slavonia",
    "Sisak-Moslavina": "sisak-moslavina",
    "Bjelovar-Bilogora": "bjelovar-bilogora",
    Međimurje: "medimurje",
    "Koprivnica-Križevci": "koprivnica-krizevci",
    Varaždin: "varazdin",
    "Krapina-Zagorje": "krapina-zagorje",
    "City of Zagreb": "zagreb-city",
    "Zagreb County": "zagreb-county",
    Karlovac: "karlovac",
    Istria: "istria",
    "Primorje-Gorski Kotar": "primorje-gorski-kotar",
    "Lika-Senj": "lika-senj",
    "Zadar County": "zadar",
    "Šibenik-Knin": "sibenik-knin",
    "Split-Dalmatia": "split-dalmatia",
    "Dubrovnik-Neretva": "dubrovnik-neretva",
  },
};

export const supplementalRegionMarkers = [
  {
    countrySlug: "hungary",
    regionSlug: "budapest",
    label: "Budapest",
    lon: 19.0402,
    lat: 47.4979,
  },
];
