export type NewsTopic = "政治" | "经济" | "欧盟" | "能源" | "区域" | "对华经贸";

import type {
  EventCodingStatus,
  EventConfidence,
  EventDirection,
  EventDuration,
  EventSourceStatus,
  EventType,
} from "../types/Event";

export const eventTypeValues: EventType[] = [
  "fiscal",
  "EU_funds",
  "macro",
  "energy",
  "industrial_policy",
  "FDI",
  "China",
  "election",
  "regional",
];

export type WeeklyNewsItem = {
  id: string;
  countrySlug: string;
  countryZh: string;
  title: string;
  topic: NewsTopic;
  summary: string;
  sourceLabel: string;
  sourceUrl?: string;
  language: string;
  weekOf: string;
  dataStatus: "sample" | "verified";
  actor?: string;
  eventType?: EventType;
  direction?: EventDirection;
  intensity?: number | null;
  affectedIndicators?: string[];
  affectedModels?: string[];
  relatedProjectIds?: string[];
  duration?: EventDuration;
  confidence?: EventConfidence;
  sourceStatus?: EventSourceStatus;
  codingStatus?: EventCodingStatus;
  entersModel?: false;
};

export type EventRecord = {
  event_id: string;
  date: string;
  country_code: string;
  region_code: string | null;
  actor: string;
  event_type: EventType;
  direction: EventDirection;
  intensity: number | null;
  affected_indicator: string[];
  affected_model: string[];
  related_project_ids: string[];
  duration: EventDuration;
  confidence: EventConfidence;
  source_status: EventSourceStatus;
  enters_model: boolean;
  coding_status: EventCodingStatus;
  model_note: string;
};

const countryCodeBySlug: Record<string, string> = {
  poland: "PL",
  hungary: "HU",
  czechia: "CZ",
  slovakia: "SK",
  germany: "DE",
  romania: "RO",
  slovenia: "SI",
  serbia: "RS",
  austria: "AT",
  croatia: "HR",
};

const eventTypeByTopic: Record<NewsTopic, EventType> = {
  政治: "election",
  经济: "macro",
  欧盟: "EU_funds",
  能源: "energy",
  区域: "regional",
  对华经贸: "China",
};

export function toEventRecord(item: WeeklyNewsItem): EventRecord {
  return {
    event_id: item.id,
    date: item.weekOf,
    country_code: countryCodeBySlug[item.countrySlug] ?? item.countrySlug,
    region_code: null,
    actor: item.actor ?? "待编码",
    event_type: item.eventType ?? eventTypeByTopic[item.topic],
    direction: item.direction ?? "pending",
    intensity: item.intensity ?? null,
    affected_indicator: item.affectedIndicators ?? [],
    affected_model: item.affectedModels ?? [],
    related_project_ids: item.relatedProjectIds ?? [],
    duration: item.duration ?? "pending",
    confidence: item.confidence ?? (item.dataStatus === "verified" ? "pending" : "low"),
    source_status: item.sourceStatus ?? (item.dataStatus === "verified" ? "official" : "sample"),
    enters_model: item.entersModel ?? false,
    coding_status: item.codingStatus ?? "pending",
    model_note: item.dataStatus === "verified"
      ? "事件编码与未来模型候选关联已记录；当前模型层未启用，事件不进入模型。"
      : "结构样例，不进入模型。",
  };
}

export const eventLibraryItems: WeeklyNewsItem[] = [
  {
    id: "hu-2026-06-24-v4-summit",
    countrySlug: "hungary",
    countryZh: "匈牙利",
    title: "匈牙利主办格德勒 V4 峰会，四国同意重启定期磋商",
    topic: "区域",
    summary: "匈牙利政府公告称，V4 四国总理在格德勒会晤，同意恢复欧洲理事会和欧盟理事会会议前的定期协调，并推进交通、能源、竞争力与文化合作。该条为官方来源的人工中文摘要。",
    sourceLabel: "匈牙利政府",
    sourceUrl: "https://kormany.hu/en/news/v4-csucs-godollon-orszagainkat-sokkal-tobb-koti-ossze-mint-ami-elvalasztja",
    language: "hu / zh",
    weekOf: "2026-06-24",
    dataStatus: "verified",
    actor: "V4 四国政府首脑",
    eventType: "regional",
    direction: "positive",
    intensity: 2,
    affectedIndicators: ["exports_goods_services", "energy_import_dependency"],
    affectedModels: ["External Vulnerability", "Industrial Dependency"],
    duration: "medium_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "pl-2026-06-24-v4-summit",
    countrySlug: "poland",
    countryZh: "波兰",
    title: "波兰总理参加格德勒 V4 峰会，四国将协调欧盟议程立场",
    topic: "欧盟",
    summary: "V4 峰会公告显示，波兰总理 Donald Tusk 与匈牙利、捷克、斯洛伐克总理共同同意恢复欧盟会议前协调，议题包括欧盟多年期预算、凝聚政策、农业、扩大与绿色转型。该条为官方来源的人工中文摘要。",
    sourceLabel: "匈牙利政府",
    sourceUrl: "https://kormany.hu/en/news/v4-csucs-godollon-orszagainkat-sokkal-tobb-koti-ossze-mint-ami-elvalasztja",
    language: "hu / zh",
    weekOf: "2026-06-24",
    dataStatus: "verified",
    actor: "V4 四国政府首脑",
    eventType: "EU_funds",
    direction: "neutral",
    intensity: 1,
    affectedIndicators: ["eu_funds_received", "government_expenditure_gdp"],
    affectedModels: ["Fiscal Pressure"],
    duration: "medium_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "cz-2026-06-24-v4-summit",
    countrySlug: "czechia",
    countryZh: "捷克",
    title: "捷克总理参加格德勒 V4 峰会，合作议题覆盖竞争力与汽车产业",
    topic: "经济",
    summary: "V4 峰会公告将竞争力、排放交易体系、汽车产业和贸易政策列为四国下一阶段协调重点，并提出恢复 V4+ 专家和高层磋商。该条为官方来源的人工中文摘要。",
    sourceLabel: "匈牙利政府",
    sourceUrl: "https://kormany.hu/en/news/v4-csucs-godollon-orszagainkat-sokkal-tobb-koti-ossze-mint-ami-elvalasztja",
    language: "hu / zh",
    weekOf: "2026-06-24",
    dataStatus: "verified",
    actor: "V4 四国政府首脑",
    eventType: "industrial_policy",
    direction: "neutral",
    intensity: 1,
    affectedIndicators: ["manufacturing_share_gdp", "automotive_export_share"],
    affectedModels: ["Industrial Dependency"],
    duration: "medium_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "sk-2026-06-24-v4-presidency",
    countrySlug: "slovakia",
    countryZh: "斯洛伐克",
    title: "斯洛伐克将接任 V4 轮值主席，四国重启高层合作",
    topic: "区域",
    summary: "格德勒峰会同时是匈牙利 V4 主席期的收官活动。公告称，四国已于 6 月 19 日完成斯洛伐克下一主席期计划的协调，并将继续推动南北交通与能源基础设施合作。该条为官方来源的人工中文摘要。",
    sourceLabel: "匈牙利政府",
    sourceUrl: "https://kormany.hu/en/news/v4-csucs-godollon-orszagainkat-sokkal-tobb-koti-ossze-mint-ami-elvalasztja",
    language: "hu / zh",
    weekOf: "2026-06-24",
    dataStatus: "verified",
    actor: "V4 四国政府首脑",
    eventType: "regional",
    direction: "positive",
    intensity: 2,
    affectedIndicators: ["exports_goods_services", "energy_import_dependency"],
    affectedModels: ["External Vulnerability"],
    duration: "medium_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "hu-2023-01-26-eu-funds-conditionality",
    countrySlug: "hungary",
    countryZh: "匈牙利",
    title: "欧盟预算条件机制措施限制部分匈牙利机构签署新资金承诺",
    topic: "欧盟",
    summary: "欧盟委员会说明，理事会 2022 年 12 月 15 日决定所采取的措施，限制与匈牙利公共利益信托及其维持实体签署新的欧盟预算法律承诺。该记录只编码政策事件及其可能关联的财政指标，不推断宏观结果。",
    sourceLabel: "European Commission",
    sourceUrl: "https://commission.europa.eu/news-and-media/news/joint-statement-commissioners-hahn-and-gabriel-application-council-implementing-decision-15-december-2023-01-26_en",
    language: "en / zh",
    weekOf: "2023-01-26",
    dataStatus: "verified",
    actor: "Council of the EU / European Commission",
    eventType: "EU_funds",
    direction: "negative",
    intensity: 3,
    affectedIndicators: ["eu_funds_received", "government_revenue_gdp", "government_expenditure_gdp"],
    affectedModels: ["Fiscal Pressure"],
    duration: "long_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "pl-2024-07-01-amended-recovery-plan",
    countrySlug: "poland",
    countryZh: "波兰",
    title: "欧盟委员会通过波兰修订后的复苏与韧性计划评估",
    topic: "欧盟",
    summary: "欧盟委员会文件记录了波兰修订后复苏与韧性计划的正面评估，计划同时涉及非偿还支持、贷款与 REPowerEU 投资。该事件与欧盟资金、财政支出和能源指标建立关联，但不计算政策成效或模型分数。",
    sourceLabel: "European Commission",
    sourceUrl: "https://commission.europa.eu/document/download/2ca5f289-d08e-4dda-aade-4d74a6447594_en?filename=COM_2024_284_1_EN_ACT_part1_v4.pdf",
    language: "en / zh",
    weekOf: "2024-07-01",
    dataStatus: "verified",
    actor: "European Commission / Polish government",
    eventType: "EU_funds",
    direction: "positive",
    intensity: 3,
    affectedIndicators: ["eu_funds_received", "government_expenditure_gdp", "fiscal_balance_gdp", "energy_import_dependency"],
    affectedModels: ["Fiscal Pressure", "External Vulnerability"],
    duration: "long_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "cz-2023-10-16-repowereu-plan",
    countrySlug: "czechia",
    countryZh: "捷克",
    title: "捷克修订复苏计划纳入 REPowerEU 能源改革与投资",
    topic: "能源",
    summary: "捷克修订后的复苏与韧性计划纳入 REPowerEU 章节，重点涉及电网接入、可再生能源与能源安全。该记录连接欧盟资金、能源进口依赖和制造业指标，只表达事件与指标的研究关联。",
    sourceLabel: "European Commission",
    sourceUrl: "https://commission.europa.eu/business-economy-euro/economic-recovery/recovery-and-resilience-facility/country-pages/czechias-recovery-and-resilience-plan_en",
    language: "en / zh",
    weekOf: "2023-10-16",
    dataStatus: "verified",
    actor: "Council of the EU / Czech government",
    eventType: "energy",
    direction: "positive",
    intensity: 2,
    affectedIndicators: ["eu_funds_received", "energy_import_dependency", "manufacturing_share_gdp"],
    affectedModels: ["External Vulnerability", "Industrial Dependency"],
    duration: "long_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "sk-2024-10-22-rrf-fourth-instalment",
    countrySlug: "slovakia",
    countryZh: "斯洛伐克",
    title: "欧盟委员会授权向斯洛伐克拨付第四笔复苏基金支持",
    topic: "欧盟",
    summary: "欧盟委员会 2024 年 10 月 22 日决定授权斯洛伐克第四笔非偿还支持拨付，文件记录金额为 9.23828 亿欧元。该事件与欧盟资金和财政指标关联，不据此评价政策优劣。",
    sourceLabel: "European Commission",
    sourceUrl: "https://commission.europa.eu/document/download/f8d60e98-0929-43ae-af64-fe3bd52fa3c2_en?filename=C_2024_7457_1_EN_ACT_part1_v3.pdf",
    language: "en / zh",
    weekOf: "2024-10-22",
    dataStatus: "verified",
    actor: "European Commission / Slovak government",
    eventType: "EU_funds",
    direction: "positive",
    intensity: 3,
    affectedIndicators: ["eu_funds_received", "government_revenue_gdp", "fiscal_balance_gdp"],
    affectedModels: ["Fiscal Pressure"],
    duration: "medium_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "hu-2022-08-12-catl-debrecen",
    countrySlug: "hungary",
    countryZh: "匈牙利",
    title: "CATL 公布德布勒森电池工厂投资计划",
    topic: "对华经贸",
    summary: "CATL 公告披露将在德布勒森建设电池工厂，并给出投资额、规划产能和地点。该记录只建立项目、FDI 与制造业指标之间的可追溯关系，不据此生成中国经济暴露指数或风险判断。",
    sourceLabel: "CATL",
    sourceUrl: "https://www.catl.com/en/news/983.html",
    language: "en / zh",
    weekOf: "2022-08-12",
    dataStatus: "verified",
    actor: "CATL / Hungarian government / Debrecen",
    eventType: "FDI",
    direction: "neutral",
    intensity: 3,
    affectedIndicators: ["fdi_inflow", "manufacturing_share_gdp", "automotive_export_share", "battery_investment"],
    affectedModels: ["Future China Exposure Index"],
    relatedProjectIds: ["hu-catl-debrecen"],
    duration: "long_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "pl-2024-04-23-nuctech-fsr-inspection",
    countrySlug: "poland",
    countryZh: "波兰",
    title: "欧盟委员会依外资补贴条例检查 Nuctech 在波兰的场所",
    topic: "对华经贸",
    summary: "欧盟委员会公告记录了针对安检设备企业 Nuctech 在波兰和荷兰场所的检查。该事件与波兰项目记录及制造业、FDI 指标建立关系，但项目金额和合同结构仍缺失，因此不进入模型。",
    sourceLabel: "European Commission",
    sourceUrl: "https://ec.europa.eu/commission/presscorner/detail/en/ip_24_1803",
    language: "en / zh",
    weekOf: "2024-04-23",
    dataStatus: "verified",
    actor: "European Commission / Nuctech",
    eventType: "China",
    direction: "neutral",
    intensity: 2,
    affectedIndicators: ["fdi_inflow", "manufacturing_share_gdp"],
    affectedModels: ["Future China Exposure Index"],
    relatedProjectIds: ["pl-nuctech-kobylka"],
    duration: "medium_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "sk-2023-11-22-gotion-inobat-surany",
    countrySlug: "slovakia",
    countryZh: "斯洛伐克",
    title: "Gotion InoBat Batteries 与斯洛伐克政府签署苏拉尼工厂谅解备忘录",
    topic: "对华经贸",
    summary: "InoBat 公告记录了 Gotion InoBat Batteries 与斯洛伐克政府围绕苏拉尼电池工厂签署谅解备忘录。该记录连接项目、FDI、电池与制造业指标；补贴、股权和实际建设进度仍需继续核验。",
    sourceLabel: "InoBat",
    sourceUrl: "https://www.inobat.eu/newsroom/gotion-inobat-batteries-gib-has-signed-a-memorandum-of-understanding-with-the-government-of-the-slovak-republic-to-support-the-construction-of-a-battery-gigafactory/",
    language: "en / zh",
    weekOf: "2023-11-22",
    dataStatus: "verified",
    actor: "Gotion InoBat Batteries / Slovak government",
    eventType: "FDI",
    direction: "neutral",
    intensity: 3,
    affectedIndicators: ["fdi_inflow", "manufacturing_share_gdp", "automotive_export_share", "battery_investment"],
    affectedModels: ["Future China Exposure Index"],
    relatedProjectIds: ["sk-gotion-inobat-surany", "sk-gotion-inobat-equity"],
    duration: "long_term",
    confidence: "high",
    sourceStatus: "official",
    codingStatus: "coded",
    entersModel: false,
  },
  {
    id: "hu-2026-w23-policy-investment",
    countrySlug: "hungary",
    countryZh: "匈牙利",
    title: "新政府与产业投资政策成为本周观察重点",
    topic: "经济",
    summary: "此处用于验证事件库结构。后续将替换为经人工审核并完成编码的事件记录。",
    sourceLabel: "来源未接入",
    language: "hu / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "pl-2026-w23-security-eu",
    countrySlug: "poland",
    countryZh: "波兰",
    title: "政府继续强调安全、基础设施和欧盟资金议题",
    topic: "欧盟",
    summary: "第一版新闻只保存标题、来源链接、主题标签和中文摘要，不保存全文。",
    sourceLabel: "来源未接入",
    language: "pl / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "cz-2026-w23-industry-energy",
    countrySlug: "czechia",
    countryZh: "捷克",
    title: "产业竞争力、能源供应与政府经济政策受到关注",
    topic: "能源",
    summary: "后续可按国家、主题、是否涉及中国经贸进行筛选。",
    sourceLabel: "来源未接入",
    language: "cs / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "sk-2026-w23-auto-regional",
    countrySlug: "slovakia",
    countryZh: "斯洛伐克",
    title: "政府政策、汽车产业链和区域发展是本周重点",
    topic: "区域",
    summary: "此处用于验证事件库版式和编码字段。",
    sourceLabel: "来源未接入",
    language: "sk / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "de-2026-w23-industry-trade",
    countrySlug: "germany",
    countryZh: "德国",
    title: "产业链、能源转型和对华贸易议题是本周观察入口",
    topic: "经济",
    summary: "正式版将接入德语新闻、官方公告和人工审核摘要。",
    sourceLabel: "来源未接入",
    language: "de / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "ro-2026-w23-black-sea-economy",
    countrySlug: "romania",
    countryZh: "罗马尼亚",
    title: "黑海、能源、港口和制造业政策进入事件观察框架",
    topic: "能源",
    summary: "正式版将接入罗马尼亚语新闻、官方公告和中文摘要。",
    sourceLabel: "来源未接入",
    language: "ro / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "si-2026-w23-port-logistics",
    countrySlug: "slovenia",
    countryZh: "斯洛文尼亚",
    title: "港口、物流和欧盟内部产业联系作为本周观察入口",
    topic: "区域",
    summary: "正式版将接入斯洛文尼亚语新闻和官方来源。",
    sourceLabel: "来源未接入",
    language: "sl / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "rs-2026-w23-infrastructure-china",
    countrySlug: "serbia",
    countryZh: "塞尔维亚",
    title: "基础设施、矿业和对华经贸项目成为事件观察入口",
    topic: "对华经贸",
    summary: "正式版需特别标注项目来源、融资状态和政治口径。",
    sourceLabel: "来源未接入",
    language: "sr / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "at-2026-w23-eu-industry",
    countrySlug: "austria",
    countryZh: "奥地利",
    title: "欧盟政策、制造业和区域物流是本周观察入口",
    topic: "欧盟",
    summary: "正式版将接入奥地利德语新闻和官方统计资料。",
    sourceLabel: "来源未接入",
    language: "de / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
  {
    id: "hr-2026-w23-adriatic-infrastructure",
    countrySlug: "croatia",
    countryZh: "克罗地亚",
    title: "亚得里亚港口、旅游和基础设施项目进入事件观察框架",
    topic: "区域",
    summary: "正式版将接入克罗地亚语新闻和官方公告。",
    sourceLabel: "来源未接入",
    language: "hr / en / zh",
    weekOf: "2026-06-01",
    dataStatus: "sample",
  },
];

export function getEventSourceItemsByCountry(countrySlug: string) {
  return eventLibraryItems.filter((item) => item.countrySlug === countrySlug);
}

