import { giscoLicenseVerificationDecision } from "./giscoLicenseVerification";

export type RegionSourceRecord = {
  region_source_id: string;
  source_name_zh: string;
  source_name_en: string;
  source_type: string;
  country_coverage: string;
  admin_level_coverage: string;
  indicator_coverage: string;
  boundary_coverage: string;
  source_url: string;
  source_reliability: "A" | "B" | "C" | "D";
  source_status: "官方来源" | "人工整理" | "待接入" | "结构样例";
  update_frequency: string;
  license_status: string;
  license_source?: string;
  license_url?: string;
  attribution_required?: boolean;
  attribution_text?: string;
  license_checked?: boolean;
  license_review_status?: string;
  license_review_date?: string;
  license_decision_note?: string;
  usage_note?: string;
  can_be_used_for_boundary: boolean;
  can_be_used_for_regional_statistics: boolean;
  can_be_used_for_election_data: boolean;
  can_be_used_for_project_location: boolean;
  is_supplementary_only: boolean;
  is_excluded_from_analysis: boolean;
  last_checked: string;
  notes: string;
};

const checkedAt = "2026-08-15";
const v4PriorityCoverage = "V4 四国优先；非 V4 暂保留国家级待接入。";
const noBoundaryLicenseIssue = "不用于边界渲染；按具体统计表或页面版权说明复核。";
const pendingLicense = "待接入具体来源后复核公开展示、下载、再分发和商业使用限制。";

export const regionSourceRecords: RegionSourceRecord[] = [
  {
    region_source_id: "eurostat_regional_lfs_unemployment",
    source_name_zh: "Eurostat 区域 LFS 失业率",
    source_name_en: "Eurostat regional LFS unemployment rate",
    source_type: "Eurostat regional statistics",
    country_coverage: "九个 EU 样本国；只在平台当前层级可直接对应时进入地图。",
    admin_level_coverage: "NUTS1 / NUTS2；NUTS3 不向下复制。",
    indicator_coverage: "regional_unemployment_rate / regional_unemployment_change_pp",
    boundary_coverage: "不提供边界；通过 NUTS code 与 GISCO 对应。",
    source_url: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/lfst_r_lfu3rt?sex=T&age=Y15-74&isced11=TOTAL&unit=PC",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "annual",
    license_status: noBoundaryLicenseIssue,
    usage_note: "统一使用 sex=T、age=Y15-74、isced11=TOTAL、unit=PC；不得与登记失业率混用。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "v0.89 劳动力主源；当前地图层级不匹配时保留 unavailable。",
  },
  {
    region_source_id: "eurostat_regional_lfs_employment",
    source_name_zh: "Eurostat 区域 LFS 就业率",
    source_name_en: "Eurostat regional LFS employment rate",
    source_type: "Eurostat regional statistics",
    country_coverage: "九个 EU 样本国；只在平台当前层级可直接对应时进入地图。",
    admin_level_coverage: "NUTS1 / NUTS2；NUTS3 不向下复制。",
    indicator_coverage: "regional_employment_rate",
    boundary_coverage: "不提供边界；通过 NUTS code 与 GISCO 对应。",
    source_url: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/lfst_r_lfe2emprt?sex=T&age=Y20-64&unit=PC",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "annual",
    license_status: noBoundaryLicenseIssue,
    usage_note: "统一使用 sex=T、age=Y20-64、unit=PC；不与就业人数或登记就业混用。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "v0.89 只接入这一项就业指标。",
  },
  {
    region_source_id: "eurostat_regional_gva",
    source_name_zh: "Eurostat 区域经济账户 GVA",
    source_name_en: "Eurostat regional economic accounts GVA",
    source_type: "Eurostat regional statistics",
    country_coverage: "九个 EU 样本国。",
    admin_level_coverage: "NUTS1 / NUTS2 / NUTS3；绝对 GVA 可按明确代码加总后计算比重。",
    indicator_coverage: "regional_manufacturing_share",
    boundary_coverage: "不提供边界；通过 NUTS code 与 GISCO 对应。",
    source_url: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/nama_10r_3gva",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "annual",
    license_status: noBoundaryLicenseIssue,
    usage_note: "制造业比重由 NACE C / NACE TOTAL 的同年同区 CP_MEUR 计算；不能替换为就业比重或国家值。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "计算值保留分子、分母、NACE 和区域代码。",
  },
  {
    region_source_id: "eurostat_regional_statistics",
    source_name_zh: "Eurostat 区域统计",
    source_name_en: "Eurostat regional statistics",
    source_type: "Eurostat regional statistics",
    country_coverage: "欧盟成员国优先；V4 四国均可作为候选来源。",
    admin_level_coverage: "NUTS1 / NUTS2 / NUTS3",
    indicator_coverage: "区域人口、区域 GDP、区域人均 GDP、区域失业率、区域就业率、区域产业结构、区域制造业 GVA 比重候选。",
    boundary_coverage: "不直接作为边界文件来源；与 GISCO 边界层通过 NUTS 代码关联。",
    source_url: "https://ec.europa.eu/eurostat/web/regions/database",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "按 Eurostat 数据集频率更新，通常为年度或季度。",
    license_status: noBoundaryLicenseIssue,
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "区域统计优先来源；真实观测值进入 region_observations 前必须保留具体数据集链接和 NUTS/ADM 映射说明。",
  },
  {
    region_source_id: "national_statistical_offices_regional",
    source_name_zh: "各国统计局区域数据",
    source_name_en: "National statistical offices regional data",
    source_type: "各国统计局区域数据",
    country_coverage: "十国；V4 优先接入。",
    admin_level_coverage: "ADM1 / NUTS2 / NUTS3，视各国统计体系而定。",
    indicator_coverage: "区域人口、区域 GDP、劳动力、产业结构和制造业 GVA 比重候选。",
    boundary_coverage: "通常不作为边界文件来源；可用于行政区代码和区域名称核验。",
    source_url: "",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "按各国统计局发布频率更新。",
    license_status: noBoundaryLicenseIssue,
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "用于补充 Eurostat 之外的官方区域口径；必须逐国保留具体表页或 API 链接。",
  },
  {
    region_source_id: "official_administrative_division_sites",
    source_name_zh: "各国行政区划官网",
    source_name_en: "Official administrative division websites",
    source_type: "各国行政区划官网",
    country_coverage: "十国。",
    admin_level_coverage: "ADM1 / ADM2 / country-level metadata",
    indicator_coverage: "区域名称、行政区代码、首府/主要城市、历史边界变动说明。",
    boundary_coverage: "可作为行政区划说明来源；边界文件需另行核验下载和复用许可。",
    source_url: "",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "按政府行政区划更新。",
    license_status: "行政说明可用于核验；边界文件公开展示和复用许可需逐站复核。",
    can_be_used_for_boundary: true,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "主要服务 regions 与 region_boundaries 的行政区代码、名称和历史边界复核。",
  },
  {
    region_source_id: "eurostat_gisco_nuts_2024",
    source_name_zh: "Eurostat GISCO NUTS 2024",
    source_name_en: "Eurostat GISCO NUTS 2024",
    source_type: "欧盟 GIS / GISCO",
    country_coverage: "九个欧盟成员国的统一候选边界来源；匈牙利已完成现有 NUTS3 证据记录，其余国家仍待文件、层级与主键核验。",
    admin_level_coverage: "NUTS3 / NUTS2 / NUTS1",
    indicator_coverage: "边界、NUTS 代码、空间关联键。",
    boundary_coverage: "NUTS 2024 多层级边界候选；匈牙利锁定 1:1M、EPSG:4326、Level 3 GeoJSON，其余欧盟国家按分析意义选择 NUTS/ADM 对应层级。",
    source_url: "https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_01M_2024_4326_LEVL_3.geojson",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "随 NUTS 版本更新。",
    license_status: "公开非商业研究展示许可已核验；必须显示指定署名，商业使用需另行联系 EuroGeographics。",
    license_source: giscoLicenseVerificationDecision.license_source,
    license_url: giscoLicenseVerificationDecision.license_url,
    attribution_required: giscoLicenseVerificationDecision.attribution_required,
    attribution_text: giscoLicenseVerificationDecision.attribution_text,
    license_checked: giscoLicenseVerificationDecision.license_checked,
    license_review_status: giscoLicenseVerificationDecision.license_review_status,
    license_review_date: giscoLicenseVerificationDecision.license_review_date,
    license_decision_note: giscoLicenseVerificationDecision.license_decision_note,
    usage_note: "仅核验公开非商业研究展示；地图或电子发布物必须保留 Eurostat/GISCO 来源与 © EuroGeographics 边界署名。许可通过不代表权威拓扑或正式地图展示通过。",
    can_be_used_for_boundary: true,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: giscoLicenseVerificationDecision.license_review_date,
    notes: "v0.85 复用匈牙利既有证据并扩展为九个欧盟国家的候选来源。许可记录不自动使其他国家的几何、拓扑或主键通过；所有公开展示状态仍由逐国 gate 决定。",
  },
  {
    region_source_id: "serbia_rpj_spatial_units",
    source_name_zh: "塞尔维亚空间单位登记与 GIS",
    source_name_en: "Statistical Office of the Republic of Serbia spatial unit register and GIS",
    source_type: "各国统计局区域数据 / 官方空间单位登记",
    country_coverage: "serbia",
    admin_level_coverage: "Republic / autonomous province / administrative district / municipality / NSTJ1 / NSTJ2 / NSTJ3",
    indicator_coverage: "区域名称、官方空间单位分类、行政区与统计区域对应关系候选。",
    boundary_coverage: "官方登记确认存在地理空间数据；具体可下载几何文件、版本、许可和复用条件尚待逐项核验。",
    source_url: "https://www.stat.gov.rs/sr-Latn/oblasti/registar-prostornih-jedinica-i-gis",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "按塞尔维亚空间单位登记和年度行政区划变更更新。",
    license_status: "官方公共登记已确认；边界文件公开展示、再分发和简化许可待核验。",
    usage_note: "不得伪造 EU NUTS code；跨国比较前必须记录 NSTJ/行政区与欧盟区域尺度的对应限制。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: true,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: "2026-08-14",
    notes: "v0.85 Serbia spatial comparability candidate。许可和具体几何文件未通过前，不进入真实地图展示。",
  },
  {
    region_source_id: "eu_gis_gisco",
    source_name_zh: "欧盟 GIS / GISCO",
    source_name_en: "EU GIS / GISCO",
    source_type: "欧盟 GIS / GISCO",
    country_coverage: "欧盟及相关欧洲统计地理范围；V4 四国可优先使用。",
    admin_level_coverage: "NUTS1 / NUTS2 / NUTS3",
    indicator_coverage: "边界、NUTS 代码、空间关联键。",
    boundary_coverage: "NUTS 边界候选；当前 region_boundaries 使用 GISCO NUTS 2024 作为 V4 A 级边界候选来源。",
    source_url: "https://gisco-services.ec.europa.eu/distribution/v2/nuts/nuts-2024-files.html",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "随 NUTS 版本更新。",
    license_status: "可公开使用需标注 © EuroGeographics for the administrative boundaries；商业使用需联系 EuroGeographics；上线真实边界前必须保留版权标注。",
    can_be_used_for_boundary: true,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "v0.9 仅登记来源与许可；geometry_available=false 时不渲染真实边界。",
  },
  {
    region_source_id: "official_open_data_portals",
    source_name_zh: "官方开放数据门户",
    source_name_en: "Official open data portals",
    source_type: "官方开放数据门户",
    country_coverage: "十国及其地方政府。",
    admin_level_coverage: "ADM1 / ADM2 / municipality，视门户而定。",
    indicator_coverage: "区域统计、交通、产业、公共项目、开放 GIS 数据候选。",
    boundary_coverage: "可作为边界或项目坐标候选；必须逐数据集核验许可证。",
    source_url: "",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "按门户或数据集更新频率。",
    license_status: "逐数据集核验；需确认公开展示、下载、再分发、简化和商业使用限制。",
    can_be_used_for_boundary: true,
    can_be_used_for_regional_statistics: true,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: true,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "许可状态是该类来源的核心字段；不得用门户名称替代具体数据集许可证。",
  },
  {
    region_source_id: "local_government_sites",
    source_name_zh: "地方政府官网",
    source_name_en: "Local government websites",
    source_type: "地方政府官网",
    country_coverage: "十国地方政府。",
    admin_level_coverage: "ADM1 / ADM2 / municipality",
    indicator_coverage: "地方项目、产业园区、招商信息、行政说明和局部统计。",
    boundary_coverage: "一般只作边界和行政说明补充线索；边界文件需许可复核。",
    source_url: "",
    source_reliability: "B",
    source_status: "官方来源",
    update_frequency: "不固定，按地方页面更新。",
    license_status: "页面内容可作线索；边界文件、地图素材和项目坐标复用许可需逐项复核。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: true,
    is_supplementary_only: true,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "更适合项目位置和背景核验，不单独作为区域统计主源。",
  },
  {
    region_source_id: "electoral_bodies_regional",
    source_name_zh: "选举机构区域数据",
    source_name_en: "Electoral bodies regional data",
    source_type: "选举机构区域数据",
    country_coverage: "十国；后续按国家选举机构接入。",
    admin_level_coverage: "选区 / ADM1 / ADM2，视选举体系而定。",
    indicator_coverage: "区域选举结果、投票率、选区映射候选。",
    boundary_coverage: "选区边界需单独核验；不等同于行政边界。",
    source_url: "",
    source_reliability: "A",
    source_status: "官方来源",
    update_frequency: "按选举周期和机构发布频率。",
    license_status: "选举数据和选区边界许可需分别核验；当前不进入地图风险图层或预测图层。",
    can_be_used_for_boundary: true,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: true,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "v0.9 只做来源字典，不接入真实区域选举数据，不做预测。",
  },
  {
    region_source_id: "manual_regional_sources",
    source_name_zh: "人工整理来源",
    source_name_en: "Manual regional sources",
    source_type: "人工整理来源",
    country_coverage: "十国。",
    admin_level_coverage: "ADM1 / ADM2 / project location",
    indicator_coverage: "区域项目位置、区域首府、项目状态、背景说明。",
    boundary_coverage: "不得作为正式边界来源。",
    source_url: "",
    source_reliability: "C",
    source_status: "人工整理",
    update_frequency: "按人工复核节奏。",
    license_status: "必须回溯到原始来源；不能用人工整理记录替代原始许可证。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: true,
    is_supplementary_only: true,
    is_excluded_from_analysis: false,
    last_checked: checkedAt,
    notes: "只作过渡和补充线索；正式使用前必须绑定原始来源链接。",
  },
  {
    region_source_id: "pending_region_sources",
    source_name_zh: "待接入来源",
    source_name_en: "Pending regional sources",
    source_type: "待接入来源",
    country_coverage: v4PriorityCoverage,
    admin_level_coverage: "待接入",
    indicator_coverage: "待接入区域指标和观测值的占位来源。",
    boundary_coverage: "不覆盖边界。",
    source_url: "",
    source_reliability: "D",
    source_status: "待接入",
    update_frequency: "not_applicable",
    license_status: pendingLicense,
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: true,
    last_checked: checkedAt,
    notes: "用于 region_observations 等待接入行；不进入地图图层、区域比较或模型候选。",
  },
  {
    region_source_id: "structural_sample_region_sources",
    source_name_zh: "结构样例来源",
    source_name_en: "Structural sample regional sources",
    source_type: "结构样例来源",
    country_coverage: "结构演示用途。",
    admin_level_coverage: "not_applicable",
    indicator_coverage: "结构样例，不代表真实来源。",
    boundary_coverage: "不覆盖边界。",
    source_url: "",
    source_reliability: "D",
    source_status: "结构样例",
    update_frequency: "not_applicable",
    license_status: "不适用；不得作为真实边界、统计、选举或项目位置来源。",
    can_be_used_for_boundary: false,
    can_be_used_for_regional_statistics: false,
    can_be_used_for_election_data: false,
    can_be_used_for_project_location: false,
    is_supplementary_only: false,
    is_excluded_from_analysis: true,
    last_checked: checkedAt,
    notes: "只用于页面结构测试；不进入正式数据、导出分析或模型候选。",
  },
];
