export type RegionIndicatorRecord = {
  region_indicator_id: string;
  name_zh: string;
  name_en: string;
  indicator_category: string;
  section: string;
  unit: string;
  frequency: string;
  applicable_countries: string;
  applicable_admin_levels: string;
  primary_source: string;
  fallback_source: string;
  source_reliability: "A" | "B" | "C" | "D";
  is_official_regional_data: boolean;
  is_manual: boolean;
  is_calculated: boolean;
  is_in_map_layer: boolean;
  is_in_regional_comparison: boolean;
  is_future_model_candidate: boolean;
  missing_value_rule: string;
  pending_value_rule: string;
  last_updated: string;
  notes: string;
};

const updatedAt = "2026-07-26";
const v4Adm1Scope = "V4 四国优先：poland, hungary, czechia, slovakia；非 V4 暂不下放复杂区域指标。";
const adm1Only = "ADM1";
const officialRegionalSource = "Eurostat regional statistics / 各国统计局区域统计";
const nationalFallbackSource = "各国统计局、Eurostat、官方区域统计年鉴";
const manualProjectSource = "china_projects / project_locations 待接入后汇总";
const boundarySource = "regions / region_boundaries";
const notAvailableRule = "不得填 0；保留空值并标记待接入或待核验。";
const pendingRule = "显示为待接入，不参与地图图层、区域比较或未来模型候选输入。";

export const regionIndicatorRecords: RegionIndicatorRecord[] = [
  {
    region_indicator_id: "regional_population",
    name_zh: "区域人口",
    name_en: "Regional population",
    indicator_category: "人口",
    section: "区域基础数据",
    unit: "人",
    frequency: "annual",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: officialRegionalSource,
    fallback_source: nationalFallbackSource,
    source_reliability: "A",
    is_official_regional_data: true,
    is_manual: false,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: notAvailableRule,
    pending_value_rule: pendingRule,
    last_updated: updatedAt,
    notes: "第一批区域基础指标；真实观测值应进入 region_observations，不与国家级 observations 混写。",
  },
  {
    region_indicator_id: "regional_gdp",
    name_zh: "区域 GDP",
    name_en: "Regional GDP",
    indicator_category: "经济",
    section: "区域基础数据",
    unit: "百万欧元",
    frequency: "annual",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: officialRegionalSource,
    fallback_source: nationalFallbackSource,
    source_reliability: "A",
    is_official_regional_data: true,
    is_manual: false,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: notAvailableRule,
    pending_value_rule: pendingRule,
    last_updated: updatedAt,
    notes: "区域 GDP 仅用于区域事实展示和比较准备，不下推国家级 GDP 数据。",
  },
  {
    region_indicator_id: "regional_gdp_per_capita",
    name_zh: "区域人均 GDP",
    name_en: "Regional GDP per capita",
    indicator_category: "经济",
    section: "区域基础数据",
    unit: "欧元",
    frequency: "annual",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: officialRegionalSource,
    fallback_source: nationalFallbackSource,
    source_reliability: "A",
    is_official_regional_data: true,
    is_manual: false,
    is_calculated: true,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: "区域 GDP 或区域人口任一缺失时不得计算；保留待接入。",
    pending_value_rule: pendingRule,
    last_updated: updatedAt,
    notes: "由区域 GDP / 区域人口计算；必须保留计算公式和原始来源。",
  },
  {
    region_indicator_id: "regional_unemployment_rate",
    name_zh: "区域失业率",
    name_en: "Regional unemployment rate",
    indicator_category: "劳动力",
    section: "区域劳动力",
    unit: "%",
    frequency: "annual",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: officialRegionalSource,
    fallback_source: nationalFallbackSource,
    source_reliability: "A",
    is_official_regional_data: true,
    is_manual: false,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: notAvailableRule,
    pending_value_rule: pendingRule,
    last_updated: updatedAt,
    notes: "区域劳动力指标，后续需统一年龄口径和统计频率。",
  },
  {
    region_indicator_id: "regional_industry_structure",
    name_zh: "区域产业结构",
    name_en: "Regional industrial structure",
    indicator_category: "产业",
    section: "区域产业",
    unit: "分类 / 占比",
    frequency: "annual",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: officialRegionalSource,
    fallback_source: nationalFallbackSource,
    source_reliability: "A",
    is_official_regional_data: true,
    is_manual: false,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: notAvailableRule,
    pending_value_rule: pendingRule,
    last_updated: updatedAt,
    notes: "可用于区域产业结构图层；必须先统一行业分类口径。",
  },
  {
    region_indicator_id: "regional_manufacturing_share",
    name_zh: "区域制造业比重",
    name_en: "Regional manufacturing share",
    indicator_category: "产业",
    section: "区域产业",
    unit: "%",
    frequency: "annual",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: officialRegionalSource,
    fallback_source: nationalFallbackSource,
    source_reliability: "A",
    is_official_regional_data: true,
    is_manual: false,
    is_calculated: true,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: "制造业 GVA 或区域总 GVA 缺失时不得计算；保留待接入。",
    pending_value_rule: pendingRule,
    last_updated: updatedAt,
    notes: "由区域制造业增加值 / 区域总增加值计算；不直接复用国家级制造业占 GDP 比重。",
  },
  {
    region_indicator_id: "regional_main_city",
    name_zh: "区域首府/主要城市",
    name_en: "Regional capital or main city",
    indicator_category: "区域元数据",
    section: "区域基础档案",
    unit: "文本",
    frequency: "not_applicable",
    applicable_countries: "十国；V4 已有 ADM1 主键，非 V4 暂保留国家级待接入。",
    applicable_admin_levels: "ADM1 / COUNTRY",
    primary_source: "regions",
    fallback_source: "各国官方行政区划说明",
    source_reliability: "B",
    is_official_regional_data: false,
    is_manual: true,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: false,
    is_future_model_candidate: false,
    missing_value_rule: "缺失时显示待核验，不填入推测城市。",
    pending_value_rule: "显示为待接入或待核验，不参与区域比较。",
    last_updated: updatedAt,
    notes: "来自 regions 元数据表；作为地图标签候选，不作为数值型指标。",
  },
  {
    region_indicator_id: "regional_china_project_count",
    name_zh: "区域对华项目数量",
    name_en: "Regional China-related project count",
    indicator_category: "对华项目",
    section: "区域对华经贸",
    unit: "项",
    frequency: "annual / snapshot",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: manualProjectSource,
    fallback_source: "企业公告、官方年报、地方政府公告、主流通讯社",
    source_reliability: "B",
    is_official_regional_data: false,
    is_manual: true,
    is_calculated: true,
    is_in_map_layer: true,
    is_in_regional_comparison: true,
    is_future_model_candidate: true,
    missing_value_rule: "project_locations 未接入前不得显示为 0；显示待接入。",
    pending_value_rule: "项目坐标和 region_id 映射完成前不进入地图图层或区域比较。",
    last_updated: updatedAt,
    notes: "由项目表按 region_id 聚合；当前不是中国经济暴露指数。",
  },
  {
    region_indicator_id: "regional_china_project_status",
    name_zh: "区域对华项目状态",
    name_en: "Regional China-related project status",
    indicator_category: "对华项目",
    section: "区域对华经贸",
    unit: "分类",
    frequency: "event / snapshot",
    applicable_countries: v4Adm1Scope,
    applicable_admin_levels: adm1Only,
    primary_source: manualProjectSource,
    fallback_source: "企业公告、官方年报、地方政府公告、主流通讯社",
    source_reliability: "B",
    is_official_regional_data: false,
    is_manual: true,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: false,
    is_future_model_candidate: true,
    missing_value_rule: "缺少项目状态时间线时显示待核验，不推断项目状态。",
    pending_value_rule: "显示为待接入或待核验，不参与区域比较。",
    last_updated: updatedAt,
    notes: "用于项目状态图层候选；不生成风险判断或政策评价。",
  },
  {
    region_indicator_id: "regional_boundary_status",
    name_zh: "区域边界状态",
    name_en: "Regional boundary status",
    indicator_category: "地图边界",
    section: "区域边界",
    unit: "分类",
    frequency: "snapshot",
    applicable_countries: "十国；V4 为 ADM1 候选，非 V4 为国家级待接入。",
    applicable_admin_levels: "ADM1 / COUNTRY",
    primary_source: boundarySource,
    fallback_source: "官方行政区划边界源",
    source_reliability: "A",
    is_official_regional_data: false,
    is_manual: true,
    is_calculated: false,
    is_in_map_layer: true,
    is_in_regional_comparison: false,
    is_future_model_candidate: false,
    missing_value_rule: "无边界来源时显示待接入；不得显示为真实边界已上线。",
    pending_value_rule: "geometry_available=false 时只作为地图工作台准备状态，不渲染真实边界。",
    last_updated: updatedAt,
    notes: "由 region_boundaries 读取边界来源、许可、格式、几何接入和拓扑检查状态。",
  },
];
