import type { Metadata } from "next";
import { PLATFORM_BASE_URL, PLATFORM_NAME, PLATFORM_RELEASE_DATE, PLATFORM_VERSION, getResearchPackageFilename } from "@/lib/releaseMetadata";

// Share images are real PNG files generated by scripts/build-og-images.mjs (public/og/).
// Per-route metadata: canonical URL (trailing slash, matching the static export), Open Graph and Twitter card.
// Next replaces the layout's openGraph object when a page sets one, so every field is filled here.
export function pageMetadata({ title, description, path, image = "/og/site.png", imageAlt = "Central Europe Political Atlas" }: { title: string; description: string; path: string; image?: string; imageAlt?: string }): Metadata {
  const canonical = path === "/" ? "/" : `/${path.replace(/^\/+|\/+$/g, "")}/`;
  const fullTitle = path === "/" ? `${PLATFORM_NAME} | ${title}` : `${title} | ${PLATFORM_NAME}`;
  return {
    title: path === "/" ? { absolute: fullTitle } : title,
    description,
    alternates: { canonical },
    openGraph: { type: "website", siteName: PLATFORM_NAME, locale: "zh_CN", title: fullTitle, description, url: canonical, images: [{ url: image, width: 1200, height: 630, alt: imageAlt, type: "image/png" }] },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [image] },
  };
}

// JSON-LD for the dataset pages (Data Explorer, Methodology): the site plus the downloadable research package.
export function datasetJsonLd({ path, name, description }: { path: string; name: string; description: string }) {
  const url = `${PLATFORM_BASE_URL.replace(/\/$/, "")}${path}`;
  return [
    { "@context": "https://schema.org", "@type": "WebSite", name: PLATFORM_NAME, url: PLATFORM_BASE_URL, inLanguage: "zh-CN" },
    {
      "@context": "https://schema.org", "@type": "Dataset", name, description, url, inLanguage: "zh-CN",
      version: PLATFORM_VERSION, dateModified: PLATFORM_RELEASE_DATE, isAccessibleForFree: true,
      creator: { "@type": "Organization", name: PLATFORM_NAME, url: PLATFORM_BASE_URL },
      license: `${PLATFORM_BASE_URL.replace(/\/$/, "")}/legal/`,
      spatialCoverage: ["Austria", "Croatia", "Czechia", "Germany", "Hungary", "Poland", "Romania", "Serbia", "Slovakia", "Slovenia"].map((name) => ({ "@type": "Place", name })),
      distribution: [{ "@type": "DataDownload", encodingFormat: "application/zip", contentUrl: `${PLATFORM_BASE_URL.replace(/\/$/, "")}/research-data/${getResearchPackageFilename()}` }],
    },
  ];
}
