import type { Metadata } from "next";
import { PLATFORM_BASE_URL, PLATFORM_NAME, PLATFORM_RELEASE_DATE, PLATFORM_VERSION, getResearchPackageFilename } from "@/lib/releaseMetadata";
import { localizedRoute, unlocalizedPath, type Locale } from "@/i18n/config";

// Share images are real PNG files generated by scripts/build-og-images.mjs (public/og/).
// Per-route metadata: canonical URL (trailing slash, matching the static export), Open Graph and Twitter card.
// Next replaces the layout's openGraph object when a page sets one, so every field is filled here.
export function pageMetadata({ title, description, path, image = "/og/site.png", imageAlt = "Central Europe Political Atlas", locale = "zh-CN" }: { title: string; description: string; path: string; image?: string; imageAlt?: string; locale?: Locale }): Metadata {
  const canonical = path === "/" ? "/" : `/${path.replace(/^\/+|\/+$/g, "")}/`;
  const fullTitle = path === "/" ? `${PLATFORM_NAME} | ${title}` : `${title} | ${PLATFORM_NAME}`;
  return {
    title: path === "/" ? { absolute: fullTitle } : title,
    description,
    alternates: { canonical, ...(unlocalizedPath(canonical).startsWith("/historical-extension") ? {} : { languages: { "zh-CN": localizedRoute(canonical, "zh-CN"), en: localizedRoute(canonical, "en"), "x-default": localizedRoute(canonical, "zh-CN") } }) },
    openGraph: { type: "website", siteName: PLATFORM_NAME, locale: locale === "en" ? "en_GB" : "zh_CN", alternateLocale: [locale === "en" ? "zh_CN" : "en_GB"], title: fullTitle, description, url: canonical, images: [{ url: image, width: 1200, height: 630, alt: imageAlt, type: "image/png" }] },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [image] },
  };
}

// JSON-LD for the dataset pages (Data Explorer, Methodology): the site plus the downloadable research package.
/** JSON-LD for an inline <script>: escapes characters that could end the element or break parsing. */
export function jsonLdHtml(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

export function datasetJsonLd({ path, name, description, locale = "zh-CN" }: { path: string; name: string; description: string; locale?: Locale }) {
  const url = `${PLATFORM_BASE_URL.replace(/\/$/, "")}${path}`;
  return [
    { "@context": "https://schema.org", "@type": "WebSite", name: PLATFORM_NAME, url: new URL(localizedRoute("/", locale), PLATFORM_BASE_URL).toString(), inLanguage: locale },
    {
      "@context": "https://schema.org", "@type": "Dataset", name, description, url, inLanguage: locale,
      version: PLATFORM_VERSION, dateModified: PLATFORM_RELEASE_DATE, isAccessibleForFree: true,
      creator: { "@type": "Organization", name: PLATFORM_NAME, url: PLATFORM_BASE_URL },
      license: `${PLATFORM_BASE_URL.replace(/\/$/, "")}/legal/`,
      spatialCoverage: ["Austria", "Croatia", "Czechia", "Germany", "Hungary", "Poland", "Romania", "Serbia", "Slovakia", "Slovenia"].map((name) => ({ "@type": "Place", name })),
      distribution: [{ "@type": "DataDownload", encodingFormat: "application/zip", contentUrl: `${PLATFORM_BASE_URL.replace(/\/$/, "")}/research-data/${getResearchPackageFilename()}` }],
    },
  ];
}
