import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
import { PLATFORM_CONTACT_EMAIL, PLATFORM_NAME } from "@/lib/releaseMetadata";
import { CONTROLLER_NAME, LEGAL_NOTICES_UPDATED } from "@/content/legalNotices";
export const metadata = pageMetadata({ locale: "en", path: "/en/legal/", title: "Legal, copyright and corrections", description: "Independence, research boundaries, third-party rights, map attribution and correction requests." });
const sections = [
  ["Independence and research purpose", `${PLATFORM_NAME} is operated by ${CONTROLLER_NAME}, a natural person, as an independent, non-commercial public research project. It is not an official project of any university or other institution. It is not affiliated with, authorised by or endorsed by EU institutions, any government, political party, candidate, company, news organisation or data provider. Its content supports political economy research, factual comparison and methodological demonstration; it is not legal, investment, commercial or policy advice.`],
  ["Original content and third-party rights", "Original platform text, interface and code are protected by applicable copyright rules. Official statistics, map boundaries, news facts, trademarks, institutional names and external materials remain the property of their respective rights holders; the platform does not claim ownership of this third-party content. When reproducing original platform content, identify the platform, version, page link and access date."],
  ["Maps and spatial data", "Maps using Eurostat/GISCO data must retain the source, data version and applicable licence notice. Current attribution: Source: European Commission - Eurostat/GISCO; Administrative boundaries: © EuroGeographics. These boundaries are used only for non-commercial research display. Before any commercial, paid, advertising-supported or client-delivery use, the licence must be checked again and authorisation obtained from EuroGeographics where required."],
  ["News, events and citations", "The event collection stores only original summaries, structured coding and source links; it is not intended to replace original reporting. Citation does not transfer rights in copyrighted reporting, images, charts or long-form original text. Read full reports at the original publisher. Factual records, manual compilation, inference and model results must be labelled separately."],
  ["Political figures, parties and personal data", "The Atlas does not build personal political-opinion profiles and does not infer an identifiable person's political opinions, ideology, voting intentions or future political behaviour from speech, voting records, social media, party affiliation or other information. The platform processes only necessary information directly relevant to public office and the research question, with an explicit public source. Aggregate analysis of parties, election results and parliamentary composition is collective-level research; it differs from profiling an individual and is never turned into a judgment about a specific person's political opinions. The platform provides no election forecasting, voter modelling or individual political targeting."],
  ["Trademarks and names", "Party, company, institution, media and product names identify research subjects only. All trademarks and marks belong to their rights holders; a name appearing here does not imply cooperation, permission or endorsement. The platform does not use third-party logos to suggest an official or partnership relationship."],
  ["Boundaries and political positions", "Names, boundaries and materials on maps do not express a platform position on any country, territory, area, authority, legal status or boundary delimitation. Boundary files may differ from the latest legal documents or parties’ claims and should be interpreted alongside original sources and official texts."],
] as const;
export default function EnglishLegal() {
  return <main className="page-shell"><p className="eyebrow">Legal, Copyright & Corrections</p><h1 className="mt-4 text-4xl font-semibold">Legal, copyright and corrections</h1><p className="mt-4 leading-7 text-[var(--muted)]">Updated: {LEGAL_NOTICES_UPDATED}. This page describes the platform’s public research boundaries and handling rules. It does not replace professional legal advice for a particular jurisdiction.</p><div className="mt-7 grid gap-4">{sections.map(([title, body]) => <section key={title} className="card p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{body}</p></section>)}</div><section className="card mt-6 p-6"><h2 className="text-2xl font-semibold">Corrections, rights and takedown requests</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">If you find factual errors, outdated information, copyright, trademark or personal-data issues, or believe material should be corrected or removed, provide the relevant page, disputed content, reasons and verifiable supporting evidence. The platform retains only the minimum records needed for the request and its outcome.</p><a href={`mailto:${PLATFORM_CONTACT_EMAIL}?subject=Central%20Europe%20Political%20Atlas%20correction%20or%20rights%20request`} className="mt-4 inline-flex text-[var(--accent)]">{PLATFORM_CONTACT_EMAIL}</a><nav className="mt-5 flex gap-4"><Link href="/en/privacy/">Privacy</Link><Link href="/en/methodology/">Methodology and source rules</Link></nav></section></main>;
}
