import type { AnalysisSkillRuntimeManifest } from "@/types/AnalysisSkill";
import { analysisNames } from "./presentation";

// Presentation-only, stable-ID overlays. State, eligibility, outputs and gates
// always come from the canonical registry; this file cannot activate a method.
type Presentation = { description: string; limitations: string[]; reason?: string };
export const analysisPresentation: Record<string, Presentation> = {
  composite_indicators: { description: "Combine annual indicators using transparent fixed rules. Comparisons require a common year and consistent definitions.", limitations: ["Composite indices are not forecasts, causal effects or investment advice."] },
  panel_econometrics: { description: "Estimate pooled OLS, country fixed effects, and country plus year fixed effects using the official 2015–2025 annual panel.", limitations: ["Association is not causality; fixed effects alone do not identify causal effects.", "Partially comparable definitions and pending observations are excluded from estimation.", "HC1 uses asymptotic normal inference. Country-clustered covariance uses a Student-t reference distribution with G − 1 degrees of freedom.", "Estimation uses a joint multi-country sample. A single country URL parameter does not filter the panel; choose a country set within the workspace."] },
  network_dependency: { description: "Describe bilateral goods-trade partner concentration using complete 2015–2025 partner edges for ten countries (UN Comtrade TOTAL goods, imports and exports). Outputs include HHI, leading partners, China and Germany shares, and diversification measures.", limitations: ["Concentration measures are not general centrality. Betweenness, eigenvector centrality and PageRank remain deferred until a complete regional graph is defined.", "Centrality is not political influence, concentration is not risk, and China's trade share is not political dependence."] },
  event_window_analysis: { description: "Describe monthly indicator changes around verified events: pre-event means, event-period values, post-event means and differences. This is not causal identification.", limitations: ["Only changes near an event are described; no causal effects or impacts are estimated.", "Complete windows require at least 12 pre-event monthly observations and 6 genuinely post-event observations. Shorter windows are labelled exploratory."] },
  macro_driver_explorer: { description: "Explore the role, timing, orientation, transformation and identification status of official macro-driver data.", limitations: ["Data exploration only: no causal effects, forecasts, risk scores or shock responses."] },
  reduced_form_var: { description: "Country-specific monthly reduced-form VAR workflow: transformation, stationarity checks, lag selection, estimation, stability and residual diagnostics. Coefficient estimation is available for eligible specifications; formal dynamic responses remain unavailable. Insufficient data in one country do not block others.", limitations: ["Reduced-form innovations are not identified economic shocks; dynamic responses are not causal effects.", "Orthogonalised IRFs depend on variable ordering. Cholesky ordering is not structural identification.", "The current formal baseline dynamic-response-ready country count is zero. Formal IRF publication is unavailable.", "The existing h=12 adjusted Portmanteau production gate is retained. The v1.85 synthetic study did not validate the preregistered finite-sample gate for the joint lag-selection and residual-diagnostic procedure. Layer B rejection rates describe that joint procedure, not pure diagnostic size. No replacement passed the same gate; this edition neither replaces the gate nor activates formal IRFs.", "Orthogonalised reduced-form responses may be output only when dynamic-response readiness is satisfied.", "Readiness is assessed separately by country, variable set, window and transformation. Countries failing the complete gate remain unavailable."] },
  svar: { description: "An interface for structural shock identification requiring an explicit identification strategy.", limitations: ["Not run in this edition; registry_only is unchanged.", "Cholesky ordering does not automatically provide structural identification."] },
  event_study: { description: "A registered causal event-study interface. Event coding alone does not identify causal effects.", limitations: ["Not run in this edition; registry_only / blocked is unchanged.", "Low-confidence or pending-coded events must not enter estimation."] },
  local_projections: { description: "Display frozen JK MP / CBI shocks in country-specific joint-shock, lag-augmented Local Projections, estimated on a common sample across all horizons.", limitations: ["Pointwise intervals apply to a single horizon; sup-t simultaneous bands address joint coverage of the displayed path.", "Bias correction remains registered but not run (registry_only).", "Finite-sample simulation is not a bias estimate for the real data. Shock concentration is not a validity test.", "Non-euro-country results represent external ECB spillovers. CBI 0.25 is a numerical normalisation only.", "This single-country method does not provide Panel LP, state dependence, SVAR or BVAR. Cross-country responses may be placed side by side descriptively, not formally ranked."] },
  panel_local_projections: { description: "Estimate dynamic responses and pointwise differences for a fixed four-country euro group and a fixed four-country non-euro group using common ECB MP / CBI shocks, lag augmentation and month-clustered inference.", reason: "Pointwise inference remains enabled for the frozen 2015–2025 eight-country sample and four common outcomes. Baseline-definition warnings remain public. Four-indicator history extension and cross-horizon joint-inference research are closed and not enabled.", limitations: ["Eight countries do not provide eight independent shocks. Panel rows are not independent shock observations.", "Results represent only this platform's fixed four-country euro group and four-country non-euro group, not the entire region.", "Only pointwise inference by horizon is provided. The studied cross-horizon procedure did not meet the 95% joint-coverage gate; joint confidence bands and whole-path significance tests are unavailable.", "Formal country-to-country difference tests remain registry_only.", "IK small-sample correction remains registry_only because of applicability limits in the author's two-shock branch.", "Croatia is excluded for the 2023 euro-entry regime break; Serbia for insufficient common monthly coverage.", "Results do not enter the country-ranking matrix and do not replace frozen single-country LP."] },
  bayesian_var: { description: "A registered Bayesian macro-dynamics interface. No priors or posterior results are produced in this edition.", reason: "A reviewable prior, prior-sensitivity and posterior-validation design has not been established; the method cannot run.", limitations: ["The method remains blocked until a reviewable prior, sensitivity and posterior-validation design exists.", "Prior assumptions must not be concealed as objective facts."] },
  causal_policy_analysis: { description: "Register policy-evaluation designs. Causal effects require defensible identification assumptions and comparison groups.", limitations: ["Not run in this edition; registry_only / blocked is unchanged.", "Event associations and temporal ordering cannot replace causal identification."] },
  monetary_policy_identification: { description: "Display frozen validated MP / CBI decompositions using median sign restrictions and the pinned Jarociński–Karadi author reference.", limitations: ["Identification within the JK framework does not imply an objectively true shock.", "This entry displays frozen results and does not rerun PCA, rotations or shock identification."] },
};
export function englishAnalysisSkill(skill: AnalysisSkillRuntimeManifest): AnalysisSkillRuntimeManifest {
  const overlay = analysisPresentation[skill.skill_id];
  if (!overlay) throw new Error(`Missing English analysis presentation: ${skill.skill_id}`);
  return { ...skill, name: analysisNames[skill.skill_id], description: overlay.description, limitations: overlay.limitations, reason_zh: overlay.reason, method_kind: skill.method_kind === "综合指数" ? "Composite index" : skill.method_kind === "数据探索" ? "Data exploration" : skill.method_kind === "识别方法" ? "Identification method" : skill.method_kind === "描述性网络分析" ? "Descriptive network analysis" : skill.method_kind === "描述性事件分析" ? "Descriptive event analysis" : "Estimation method" };
}
