import Link from "next/link";
import { datasetJsonLd, pageMetadata } from "@/lib/seo";
import { runtimeAnalysisSkills } from "@/lib/analysisSkills";
import { analysisNames } from "@/i18n/presentation";
import { getResearchPackageFilename, PLATFORM_VERSION } from "@/lib/releaseMetadata";
import publicationBoundary from "@/data/macro/var_dynamic_response_publication_boundary.json";
export const metadata = pageMetadata({ locale: "en", path: "/en/methodology/", title: "Methodology and research boundaries", description: "Data definitions, comparability, model capabilities, inference boundaries, validation and citation rules." });
const sections = [
  ["data", "Data and comparability", [
    "Every formal observation requires a country or region, time, value, unit, source name and URL, reliability, status and update date. Official / verified records may enter the corresponding factual layer; pending records remain visible but are excluded from comparison. Samples and placeholders do not enter analysis. Reliability A denotes official statistics or institutions, B a verifiable authoritative source, C a lead only, and D exclusion.",
    "Cross-country comparison requires the same definition, unit, geographic level and common year. Calculated values retain their numerator, denominator, formula and sources. Missing observations are neither zero-filled nor interpolated. Descriptive historical and Serbian SORS series remain outside all formal models, indices and scenarios. National CPI is not HICP; original SORS units, quarterly labels and breaks are retained.",
  ]],
  ["baseline-data-definitions", "Frozen baseline definitions", [
    "Polish industrial production changed statistical units from LEU to KAU in 2021. Official material allows a small break for some aggregates. The frozen 2015–2025 formal sample remains analysis-eligible with a non-blocking methodological warning, not a claim of complete comparability. Hungarian monthly unemployment uses state-space estimation from 2023; Eurostat states that 2011–2022 were revised retrospectively. The baseline is interpreted as a latest-revised series, not a consistent real-time vintage. Slovenian 2025 long-term yields carry an estimated-value quality flag, not a definition break or automatic eligibility change.",
    "These are definition and revision-transparency notes, not alternative specifications or causal robustness tests. The fixed eight-country, four-indicator historical extension audit is closed. Design A was blocked by industrial-production and unemployment definition-evidence gaps; no historical Panel LP was run.",
  ]],
  ["models", "Transparent analysis", [
    "Methods share the Analysis Runner: inputs, calculation, diagnostics, result and consistency checks. Composite indicators retain their registered normalisation and weights. Scenarios are conditional parameter presets, not independent models, predictions, probabilities or causal effects; they do not rewrite raw data.",
    "Annual panel econometrics requires at least eight countries, eight years and four key comparable variables with 75% coverage. Pooled OLS, country fixed effects and country-plus-year fixed effects are supported. HC1 uses asymptotic normal inference. Country-clustered covariance uses Student-t with G−1 degrees of freedom; fewer than 20 clusters triggers an imprecision warning and fewer than eight blocks estimation. Coefficients are conditional associations; fixed effects alone do not identify causality.",
    "The trade network uses UN Comtrade bilateral goods edges for the ten-country scope, 2015–2025. The formal coverage gate counts only network-eligible partners: eligible partner sum / World total must be at least 0.95. World and Other … nes aggregates remain recorded but are not nodes and cannot help the gate pass. Ineligible country-year-flow combinations have no formal network metrics. Concentration is not economic risk, China’s trade share is not political dependence, and network position is not political influence.",
  ]],
  ["var-publication-boundary", "VAR: estimation is available; formal dynamic responses are not", [
    "Keep five questions separate: estimator availability, country estimability, evidence of misspecification, validation of the diagnostic gate, and permission to publish formal dynamic responses. Reduced-form VAR coefficient estimation is active. Five formal country models are estimable: baseline v1 for Poland and Romania; baseline v2 for Czechia, Germany and Hungary. The finite-sample residual publication gate remains unresolved: no validated diagnostic is available. Formal IRFs, IRF uncertainty and structural identification are not available for publication.",
    "Baseline v1 uses a constant VAR and constant-only ADF. Baseline v2 retains variables, transformations, sample and BIC policy, adds eleven month dummies and uses finite-sample-calibrated seasonal-dummy ADF. The legacy MacKinnon-c seasonal-dummy judgement remains an archived reference, not a replacement. Month terms absorb residual calendar effects; they do not re-seasonally-adjust source series. Deterministic seasonality, seasonal unit roots, structural breaks and persistent stationary processes are different concepts. Seasonal-dummy ADF tests the zero-frequency unit root under the registered deterministic terms; HEGY is not implemented and Zivot–Andrews remains registry-only.",
    "VAR requires at least 60 consecutive valid months, registered transformations, profile-mapped stationarity, common-sample lag selection, parameter-count and stability gates. BIC remains the formal lag rule. Higher-order diagnostically adequate fits are sensitivity checks, not replacements chosen after observing results. ADF-borderline status permits only warned coefficient estimation, not dynamic responses. Romania, Czechia and Hungary have this independent stationarity obstacle.",
    "The existing h=12 adjusted Portmanteau gate is retained, but the lag-selection-plus-residual-diagnostic procedure failed finite-sample calibration. No eligible replacement was authorised. The h=18/24 checks concern longer horizons; passing a shorter horizon cannot authorise all horizons. Reduced-form innovations are not structural shocks. Order-dependent Cholesky responses are not structural identification or causal effects. Their implementation does not establish a publishable formal IRF. Bootstrap, Monte Carlo and delta-method IRF uncertainty remain unavailable.",
    "Seasonal-dummy ADF calibration uses the production regression and sample policy under a zero-frequency unit-root null with fixed monthly increments. It covers nine N=96–168 nodes, 50,000 repetitions each, fixed seeds and linear interpolation by input length. Calibration points and weights are recorded. Asymptotic equivalence does not imply finite-sample equality. The full empirical null CDF is not published, so p_value remains null. Independent OLS agreement verifies regression, standard errors and tau, not the critical values by itself.",
  ]],
  ["macro-drivers", "Macro drivers and identification", [
    "Policy rates are not market rates; bond yields are not policy rates; bilateral FX is not effective FX; HICP Energy is not a wholesale energy price. BIS supplies policy rates and FX, Eurostat supplies long-term yields and HICP Energy, and World Bank Pink Sheet supplies monthly Brent and European gas prices. Each record retains units, definitions, transformations, revision status, aggregation, economic role and identification status. An observed driver or rate change is not automatically an identified economic shock.",
    "Monthly changes require exactly adjacent calendar months; annual changes require exactly twelve-month spacing. Warm-up periods are not source missingness. Source gaps, warm-up, regime changes and definition changes are separate reasons. Policy-rate changes require consistent policy regime, instrument and source-series instance. Croatia’s January 2023 transition from national policy to ECB policy is excluded from cross-regime monthly changes. Shared ECB, EUR/USD and commodity series retain common IDs and applicability periods; they are not multiple statistically independent country shocks.",
    "EA-MPD is the formal scheduled-meeting baseline; EA-EMPD retains speeches and extended robustness material. Decision, press-conference and combined windows share parent-event IDs, and database overlaps are deduplicated. Frankfurt local time, CET/CEST and UTC conversion are retained. Monthly aggregation sums qualified event surprises; a month without a qualified event is zero with valid_no_event, while an expected event lacking its measure is missing. Speeches are not silently added to the formal decision series. Raw workbooks stay in the local audit; public packages contain derived records, checksums and official links.",
    "Ordinary OIS surprises are external innovation proxies, not automatically pure monetary-policy shocks. Only the two frozen, independently validated Jarociński–Karadi MP / CBI series may enter formal LP. Their deterministic construction uses uncentred PC1 of OIS_1M, OIS_3M, OIS_6M and OIS_1Y with STOXX50 and a positive-diagonal QR median rotation. Monetary tightening raises rates and lowers equities; central-bank information shocks move them in the same direction. The median rotation is a representative admissible rotation, not unique structural truth. Shock construction is distinct from the paper’s Bayesian VAR transmission model; SVAR and BVAR are not thereby activated.",
    "Austria, Germany, Slovakia and Slovenia have common euro-area exposure. Croatia switches from external ECB spillovers to common exposure in January 2023. Czechia, Hungary, Poland, Romania and Serbia are interpreted as external ECB spillovers, not domestic monetary-policy shocks. Brent, gas prices, ordinary policy rates and FX movements are not newly identified shocks. Event-related driver IDs express research relevance, not causation.",
  ]],
  ["local-projections", "Single-country Local Projections", [
    "Formal units are country × outcome × regime. MP and CBI enter each horizon regression jointly; the single-country estimator does not run pooled, state-dependent or Panel LP. HICP and industrial production use cumulative log-percent changes relative to t−1; unemployment, long yields and domestic policy rates use percentage-point level changes. Rising non-euro local-currency units per EUR means depreciation. CBI 0.25 is numerical normalisation, not a 25-basis-point tightening.",
    "All horizons use one common sample with N≥96 after trimming. AIC selects p once from 1…6. Non-augmented LP has p−1 lag blocks and lag-augmented production LP has p blocks, not p+1. Pointwise 90%/95% EHW-HC1 intervals concern individual horizons. Single-country simultaneous bands use joint cross-horizon HC1 covariance and a simulated plug-in sup-t critical value. A pointwise exclusion of zero is not a whole-path significance result; significance bands remain registry-only and are not parameter confidence bands.",
    "Fixed p=2, p=6 and predetermined lagged Brent, gas and applicable non-euro policy rates are sensitivities, not replacements selected by results. Current transmission channels are not inserted as contemporaneous controls. Shock concentration, leverage, standardised residuals, DFBETAs and leave-largest-shock-month checks are diagnostic and do not automatically delete observations. Cross-country plots are descriptive only: visual differences are not statistical heterogeneity, independent shock repetitions or a formal country-difference test.",
  ]],
  ["finite-sample", "Finite samples and shock support", [
    "Asymptotic inference robustness and finite-sample point-estimate bias are distinct. Lag-augmented inference results do not guarantee unbiased estimates in roughly 100–115 months. The formal AIC rule, p lag blocks, common sample, HC1 and 5,000-draw sup-t remain frozen. Bias correction remains registry-only: the referenced conditional-moment and optimal-control formulation has no validated mapping to the platform’s correlated dual shocks, monthly dummies and direct cumulative regression. Partial audit is not full replication and supplies no validated corrected standard errors.",
    "Effective shock support 1 / Σw², with squared-shock shares w, measures concentration, not the effective sample size of asymptotic inference. Monthly and event-level denominators differ because aggregation contains cross terms. No arbitrary concentration grade or robustness score is assigned. Dropping a regression month does not erase its shock from later lags; event deletion subtracts that event’s contribution and propagates it through affected lags without re-estimating the JK rotation or editing formal shock files.",
    "Eight key simulation designs used 10,000 repetitions and 5,000 sup-t draws per repetition; 378 exploratory designs used 200 repetitions and 256 draws. These fixed-p level-difference DGPs do not cover AIC-selection randomness, every log transformation or every external-control specification, and cannot calibrate actual coefficients. Joint covariance was independently checked for all 44 models. Correlation eigenvalues below −1e−8 block diagnostics; tiny negative-eigenvalue adjustments are explicitly recorded. Sup-t critical values are simulation estimates, checked for same-seed reproduction and independent-seed variation, not exact constants.",
  ]],
  ["panel-local-projections", "Panel LP: common shocks and group heterogeneity", [
    "The formal equal-country-weight balanced panel remains fixed at eight countries: euro group AT, DE, SK, SI; non-euro group CZ, HU, PL, RO. Croatia is excluded for its 2023 euro-entry break and Serbia for insufficient common monthly coverage. Eight countries are not eight independent shocks; panel rows are not independent shock observations and month clustering is not country clustering. Neither group represents an entire region, and panel estimation is not an average of separate country LP estimates.",
    "The independent offline estimator follows Almuzara–Sancibrián t-LAHR, jointly estimating frozen JK MP and CBI with country fixed effects, lag augmentation and month-clustered score covariance. HICP includes eleven month terms, not full time fixed effects that would absorb the common shock. Each horizon needs at least 96 valid months. The horizon may shorten transparently from 24 to 18, 12 or 6 months; missingness cannot silently reduce the panel to seven countries. Group differences are tested directly by horizon, with pointwise intervals only.",
    "Leave-one-country-out diagnostics preserve horizon calendars and shock support. Unequal 3-versus-4 or 4-versus-3 groups use +n_N/N for euro countries and −n_E/N for non-euro countries, giving a zero cross-sectional mean and unit group contrast. LOCO ranges are not confidence intervals or country-jackknife standard errors and do not measure a country’s causal contribution. Relative changes are withheld when the baseline magnitude is below max(10⁻¹⁰, 0.1 × baseline SE); this only avoids unstable ratios, not a robustness threshold. Reports cover h=0–6, 7–12 and 13–24, signs and pointwise zero-inclusion agreement.",
    "Country-plus-time-FE contrasts are group-difference sensitivity checks, not replacements of the country-FE baseline. A change in zero-inclusion classification is specification sensitivity, not automatic invalidation. Path correlation is descriptive, not a path-significance test. IK small-sample correction and formal country-to-country tests remain registry-only.",
  ]],
  ["panel-lp-whole-path-inference", "Panel LP whole-path inference is blocked", [
    "Validated pointwise intervals cannot be combined into a whole-path confidence band. The completed joint-inference programme failed the nominal 95% joint-coverage gate. It therefore publishes neither Panel LP joint bands nor whole-path significance tests. This is a conclusion for the fixed panel, registered programme and tested designs, not a mathematical impossibility theorem. R2 was NOT CONFIRMED and no path was authorised; scope reduction confirmed after results remains labelled post hoc.",
    "Point estimation, pointwise inference, composition diagnostics, time-FE sensitivity and descriptive fitted-model comparisons remain available. Fitted-model paths are off by default, not structural IRFs or forecasts, and carry no intervals or inferential p-values. The independent historical monthly extension programme is also closed and did not re-estimate Panel LP. Reopening requires new methodological grounds, preregistration, an unused seed namespace and owner approval; future directions are not current production tasks.",
  ]],
  ["events", "Events and high-frequency comparisons", [
    "Source → event → coding → affected indicator/project → research context. Event date, actor, type, direction and confidence aid retrieval and interpretation; they do not establish causality or directly alter model scores. Incompletely coded, low-confidence and sample events retain enters_model=false. Untranslated original event prose is explicitly identified in the English interface.",
    "The formal Eurostat high-frequency baseline starts in January 2015. HICP index and annual rate are separate; unemployment is SA and industrial production SCA. Definition, index reference, revision and value semantics are retained. HICP uses prc_hicp_minr, ECOICOP ver.2 TOTAL, with the registered 2015=100 index; it is not spliced with 2025=100. Retired datasets and overlap migration checks are recorded. Harmonised unemployment is not an identical raw monthly survey in every country. Coverage counts missing API months and distinguishes normal publication lag from unexpected stagnation.",
    "Descriptive event windows separate pre-event, event month and post-event observations. The event month does not enter the post-event mean or count. A complete window needs twelve pre-event and six genuinely post-event months. Rates use percentage-point changes; indices use index-point and relative-percent changes. Missing chart months are not joined; concurrent verified events are flagged. Observed changes cannot be attributed to one event. Formal causal event study remains registry-only.",
  ]],
  ["spatial", "Spatial facts and licences", [
    "Regional records join by stable region ID, administrative level, boundary version, source, licence and year. National values are not allocated to regions, and NUTS2 and NUTS3 are not mixed. Boundaries require provenance, licence, coordinate-system, geometry, topology and key checks. Serbia’s regional comparison remains unconnected. Risk, forecast, scenario-impact and actual party-support layers are not enabled. Missing regional values remain missing.",
    "Maps retain European Commission - Eurostat/GISCO attribution, the boundary version and © EuroGeographics administrative-boundary notice. Commercial, paid, advertising-supported or client use requires a new licence review and any required authorisation; map display expresses no platform position on territorial or legal status.",
  ]],
  ["validation", "Validation and interpretation", [
    "Checks cover determinism, weights, normalisation, missingness, year alignment, zero-shock scenarios, parameter bounds and reproduction. Expected unavailable means a gate correctly withheld output, not an implementation error. Validation is not scientific proof. Historical reconstruction readiness and directional checks do not establish forecast accuracy without point-in-time vintage data. Event association is not causality, the project collection is not a census, and confidence is not occurrence probability.",
  ]],
] as const;
const archives = [
  ["var-residual-diagnostic-calibration", "v1.85 / v1.851", "Adjusted Portmanteau, BG LM and Edgerton–Shukur did not pass the joint preregistered procedure gate. Layer A concerns correctly specified fixed-lag diagnostic size; Layer B combines lag selection, specification and diagnostics, and its rejection rate is not pure Type-I error. Deterministic decomposition did not change the no-eligible-replacement decision.", "var-residual-diagnostics/var_residual_diagnostic_research_conclusion.json"],
  ["var-selection-aware-bootstrap", "v1.86", "The synthetic selected-model-adequacy bootstrap study passed its restricted registered target, not a general production-validation gate. The full procedure rate is report-only; true VAR(2) selection-aware size remained untested in the original setting. It did not authorise a production diagnostic.", "var-selection-bootstrap/var_selection_bootstrap_research_conclusion.json"],
  ["var-lag-selection-characterization", "v1.87", "Lag recovery varied with second-lag signal strength. Underselecting the true order differs from whether a lower-order model is an adequate approximation. Infeasible stationary combinations were preserved; AIC and HQIC were comparisons, not proposed replacements for BIC.", "var-lag-characterization/var_lag_characterization_research_conclusion.json"],
  ["var-country-identifiability", "v1.88", "The authorised five-country audit and bootstrap evaluation are research evidence, not readiness changes. The empirical identifiability index is descriptive, not the true synthetic ψ or the probability of a second lag. Bootstrap non-rejection did not establish adequacy or validate publication.", "var-country-identifiability/var_phase_b_bootstrap_results.json"],
  ["var-country-matched-bootstrap", "v1.89", "Country-matched synthetic calibration found marked conservatism and weak power in the relevant moderate second-lag signal range. This does not support production adoption; non-rejection there is weak adequacy evidence. Production diagnostics and readiness were unchanged.", "var-country-matched-bootstrap/var_country_matched_bootstrap_research_conclusion.json"],
  ["var-residual-attribution", "v1.90", "Residual dependence was weak and dispersed, with pandemic-period concentration. Diagnostic refits did not create new baselines or production specifications. A preregistered labelling issue is retained with an explicit post-hoc note. Neither asymptotic rejection nor bootstrap non-rejection proves a model wrong or validated.", "var-residual-attribution/var_residual_attribution_research_conclusion.json"],
] as const;
export default function EnglishMethodology() {
  return <main className="page-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(datasetJsonLd({ locale: "en", path: "/en/methodology/", name: "Central Europe Political Atlas — data and methodology", description: "Data definitions, model availability, inference boundaries and citation rules." })).replace(/</g, "\\u003c") }} /><header className="max-w-4xl border-b border-[var(--line)] pb-8"><p className="editorial-kicker">Research · {PLATFORM_VERSION}</p><h1 className="mt-4 text-5xl font-semibold">Methodology and research boundaries</h1><p className="mt-5 leading-8 text-[var(--muted)]">This English edition summarises the current public workflow and its limits. Frozen research records and numerical outputs are shared with the Chinese edition.</p><nav aria-label="Methodology sections" className="mt-5 flex flex-wrap gap-3">{sections.map(([id, title]) => <a href={`#${id}`} key={id} className="text-sm text-[var(--accent)]">{title}</a>)}</nav></header>
    {sections.map(([id, title, paragraphs]) => <section id={id} key={id} className="scroll-mt-24 border-t border-[var(--line)] py-8">{id === "events" ? <span id="high-frequency" className="scroll-mt-24" /> : null}<h2 className="text-2xl font-semibold">{title}</h2>{paragraphs.map(text => <p key={text} className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">{text}</p>)}{id === "var-publication-boundary" && <p className="mt-4 font-semibold">Formal dynamic-response-ready countries: {publicationBoundary.formal_dynamic_response_ready_country_count}. <a className="text-[var(--accent)] underline underline-offset-2" href="/research-data/var-publication-boundary/var_dynamic_response_publication_boundary.json">Publication boundary registry</a></p>}{id === "panel-lp-whole-path-inference" && <a href="/research-data/panel-local-projections/panel_lp_joint_inference_research_conclusion.json" className="mt-4 inline-flex text-[var(--accent)]">Joint-inference conclusion and registered provenance</a>}</section>)}
    <section id="analysis-registry" className="scroll-mt-24 border-t border-[var(--line)] py-8"><h2 className="text-2xl font-semibold">Registered method states</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">States below come directly from the canonical registry. Active means an implementation is available, not that every input combination or inferential claim passes its gates.</p><ul className="mt-4 grid gap-3 md:grid-cols-2">{runtimeAnalysisSkills.map(skill => <li key={skill.skill_id} className="card p-4"><h3 className="font-semibold">{analysisNames[skill.skill_id] ?? skill.skill_id}</h3><p className="mt-2 text-sm">{skill.state === "active" ? "Active — subject to method and input gates" : skill.state === "blocked" ? "Blocked — not runnable" : "Registry only — not runnable"}</p><code className="text-xs">{skill.skill_id}</code></li>)}</ul></section>
    <section className="border-t border-[var(--line)] py-8"><h2 className="text-2xl font-semibold">Closed VAR diagnostic research archive</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">v1.85–v1.90 identify research programmes, not the current platform release. The programme is frozen after v2.0. Reopening requires new method evidence or a separately preregistered question and owner approval. There is no authorised replacement diagnostic or model expansion.</p>{archives.map(([id, title, summary, file]) => <article id={id} key={id} className="scroll-mt-24 mt-5 border-l-2 border-[var(--line)] pl-5"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 max-w-4xl text-sm leading-7 text-[var(--muted)]">{summary}</p><div className="mt-3 flex gap-4 text-sm text-[var(--accent)]"><a href={`/research-data/${file}`}>Shared research record</a><Link href={`/methodology/#${id}`} hrefLang="zh-CN">Full Chinese archive</Link></div></article>)}</section>
    <section id="citation" className="scroll-mt-24 border-t border-[var(--line)] py-8"><h2 className="text-2xl font-semibold">Citation and downloads</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Cite platform version, access date and stable URL. For an observation, event, project, model or scenario, also cite its stable record ID and original source. No DOI is fabricated. Descriptive snapshots record current filters and provenance; they do not publish formal model results.</p><div className="mt-4 flex flex-wrap gap-5 text-[var(--accent)]"><a href={`/research-data/${getResearchPackageFilename()}`}>Shared research package (ZIP)</a><a href="/research-data/release_manifest.json">Release manifest</a><Link href="/historical-extension/" hrefLang="zh-CN">Historical-extension conclusion (Chinese archive)</Link><Link href="/en/legal/">Legal and licences</Link></div></section>
  </main>;
}
