import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
import { PLATFORM_CONTACT_EMAIL } from "@/lib/releaseMetadata";
import { CONTROLLER_NAME, LEGAL_NOTICES_UPDATED } from "@/content/legalNotices";
export const metadata = pageMetadata({ locale: "en", path: "/en/privacy/", title: "Privacy notice", description: "Data minimisation, hosting logs, contact email and external-link privacy." });
const sections = [
  ["Browser-local storage", "The platform uses only two localStorage keys: the research notebook (central-europe-atlas:research-notebook:v1) and the appearance preference (atlas-theme, which records only the light or dark theme). Research notes are stored only in this browser unless you export them: no server upload, sync or tracking, and no claim of cryptographic protection. The platform uses no cookies, sessionStorage or IndexedDB. Other users of a shared browser may see it. Clearing browser data removes the notebook. Explicitly clear it on the Notebook page or export a backup first."],
  ["What the platform actively collects", "The current website uses no first-party analytics tools, advertising trackers, marketing pixels or non-essential cookies. It does not collect names, locations, political views or other personal information through web forms."],
  ["Hosting", "The site is hosted by GitHub Pages. GitHub may process IP addresses, request times, device information and access logs for security, operation and service provision. This processing is governed by GitHub’s privacy statement; the platform cannot read or control all its infrastructure logs."],
  ["Contact email", "When you email the public address, your sender address, message and attachments are used to respond, verify corrections or handle rights requests. Only information necessary to complete the request, maintain review records or fulfil necessary legal obligations is retained. It is not sold or used for political marketing."],
  ["No personal political profiling", "The Atlas does not build personal political-opinion profiles and does not infer an identifiable person's political opinions, ideology, voting intentions or future political behaviour from speech, voting records, social media, party affiliation or other information."],
  ["Aggregate analysis is not individual profiling", "The platform analyses collective public data such as parties, election results and macro statistics. Such aggregate analysis differs from profiling an individual and cannot and will not be used to judge the political opinions of any specific person. The platform does not profile visitors and makes no automated decisions about anyone."],
  ["External links", "After following links to statistical agencies, news organisations, governments, companies or other third parties, their privacy and cookie rules apply. The platform does not control external sites and does not treat external links as endorsements."],
] as const;
export default function EnglishPrivacy() {
  return <main className="page-shell"><p className="eyebrow">Privacy Notice</p><h1 className="mt-4 text-4xl font-semibold">Privacy notice</h1><p className="mt-4 leading-7 text-[var(--muted)]">Updated: {LEGAL_NOTICES_UPDATED}. The platform follows data minimisation. It currently provides no accounts, comments, uploads, subscriptions or personalised political targeting.</p><section className="card mt-6 p-6" data-controller="true"><h2 className="text-xl font-semibold">Controller and contact</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">The controller and operator of this website is {CONTROLLER_NAME}, a natural person, who runs the Central Europe Political Atlas as an independent, non-commercial research project. Contact: <a className="text-[var(--accent)] underline" href={`mailto:${PLATFORM_CONTACT_EMAIL}`}>{PLATFORM_CONTACT_EMAIL}</a>. The Atlas is not an official project of any university or other institution and is not sponsored or endorsed by one.</p></section><div className="mt-7 grid gap-4 md:grid-cols-2">{sections.map(([title, body]) => <section key={title} className="card p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{body}</p>{title === "Hosting" && <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noreferrer" className="mt-3 inline-flex text-[var(--accent)]">GitHub privacy statement</a>}</section>)}</div><section className="card mt-6 p-6"><h2 className="text-2xl font-semibold">Your rights, privacy requests and security reports</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Where the GDPR or similar data protection law applies, you may request access to, rectification or erasure of, or restriction of processing of personal information you submitted by email, or object to its processing. You also have the right to lodge a complaint with a data protection supervisory authority, for example in the place where you live, work or where the alleged infringement occurred. Browser-local data is under your own control and can be cleared at any time.</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]">To make such a request, or to report a possible data-exposure security issue, contact the public email address. Do not send passwords, API keys, access tokens, identity-document numbers or unnecessary sensitive material.</p><a className="mt-4 inline-flex text-[var(--accent)]" href={`mailto:${PLATFORM_CONTACT_EMAIL}?subject=Central%20Europe%20Political%20Atlas%20privacy%20or%20security%20request`}>{PLATFORM_CONTACT_EMAIL}</a><nav className="mt-5 flex gap-4"><Link href="/en/legal/">Legal and copyright</Link><Link href="/en/methodology/">Data and model methodology</Link></nav></section></main>;
}
