import type { Metadata } from "next";
import Link from "next/link";
import { CitationActions } from "@/components/CitationActions";
import { platformStatus } from "@/lib/platformStatus";
import { getResearchPackageFilename, platformApaCitation, platformBibtexCitation, platformCitation } from "@/lib/releaseMetadata";

export const metadata: Metadata = { title: "研究方法", description: "数据、模型、事件、空间、验证和引用规则。" };

const sections = [["data", "Data"], ["models", "Analysis"], ["events", "Events"], ["spatial", "Spatial"], ["validation", "Validation"], ["citation", "Citation"]] as const;

function Section({ id, label, title, children }: { id: string; label: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-24 border-t border-[var(--line)] py-10"><p className="editorial-kicker">{label}</p><h2 className="mt-3 text-3xl font-semibold">{title}</h2>{children}</section>;
}

export default function MethodologyPage() {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
  return <main className="page-shell">
    <header className="max-w-4xl border-b border-[var(--line)] pb-8"><p className="editorial-kicker">Research / {platformStatus.version}</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em]">研究方法与边界</h1><p className="mt-5 text-base leading-8 text-[var(--muted)]">本页说明公开研究流程和不能说明什么。完整字典、QA、版本记录与技术字段保留在研究数据包，不再占据主要页面。</p><nav className="mt-5 flex flex-wrap gap-3">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className="text-sm font-semibold text-[var(--accent)]">{label}</a>)}</nav></header>

    <Section id="data" label="01 / Data" title="数据如何进入平台"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">每条正式观测必须有国家或地区、时间、数值、单位、来源名称、来源链接、可靠性、状态和更新时间。official / verified 可进入相应事实层；pending 保留但不参与比较；sample 与 placeholder 不进入分析。A 级为官方统计或机构，B 级为可核验权威来源，C 级只作线索，D 级排除。</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]">跨国比较只使用同定义、同单位、同层级和共同年份。计算值必须保留分子、分母、公式和来源。</p><Link href="/data" className="mt-4 inline-flex text-sm font-semibold text-[var(--accent)]">打开 Data Explorer</Link></Section>

    <Section id="models" label="02 / Analysis" title="透明分析方法">
      <p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">所有方法统一通过 Analysis Runner：输入数据 → 计算 → diagnostics → result → consistency。综合指标继续使用既有标准化与权重；Scenario 仍是条件参数预设，不改写原始数据。</p>
      <div className="mt-5 grid gap-5 md:grid-cols-2">
        <div className="border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">Panel Econometrics</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">年度面板必须至少覆盖 8 国、8 年，并有至少 4 个关键可比变量达到 75% 覆盖。当前支持 Pooled OLS、Country FE、Country + Year FE。HC1 稳健标准误使用渐近正态推断；按国家聚类标准误使用聚类稳健协方差 + Student-t 参考分布（df = G − 1），聚类数小于 20 时给出不精确提示，小于 8 时阻止运行。系数表示条件关联，固定效应不自动构成因果识别。</p></div>
        <div className="border-l-2 border-[var(--line)] pl-5"><h3 className="font-semibold">Trade Network Analysis</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">贸易网络基于 UN Comtrade 十国 2015–2025 完整双边货物边。正式覆盖闸门只计算 network_eligible 伙伴：eligible partner sum / World total ≥ 0.95；World 与 Other … nes 等聚合记录保留但不进入网络节点，也不帮助闸门通过。未达标的国家 × 年份 × 流向组合不输出正式网络指标。贸易集中度 ≠ 经济风险，中国份额 ≠ 政治依赖，网络位置 ≠ 政治影响。</p></div>
        <div className="border-l-2 border-[var(--accent)] pl-5 md:col-span-2"><h3 className="font-semibold">Reduced-form VAR / 宏观动态</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">v1.44 并列保留两个预注册正式基线：baseline v1 使用 constant VAR + ADF constant；baseline v2 使用相同变量、变换、样本和 BIC 政策，但采用 constant + 11 个月份虚拟变量，并以 finite-sample calibrated seasonal-dummy ADF 作为正式平稳性闸门。旧 v1.43 MacKinnon-c 判断继续作为历史参考，不覆盖。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">HICP 月度指数与年率来源均为 NSA，但年率已包含 12 个月同比比较，不能机械套用月度指数的季节风险判断。工业生产来源为 SCA、失业率来源为 SA；v2 的系统月份项主要吸收剩余 calendar/month effects，不是重新季调这些来源序列，也不改写原始观测。探索性规格继续使用 constant-only ADF，只能沿登记链尝试替代变换，不能冒充任一正式基线。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Deterministic seasonality ≠ seasonal unit root ≠ structural break ≠ persistent stationary process。seasonal-dummy ADF 只检验登记确定性项下的零频单位根；HEGY 尚未实现。Zivot–Andrews 仍为 registry_only，因为生产实现与跨语言 reference fixture 尚未对齐；2020-03、2021-H2 与 2022-02 只是 historical candidate periods，statistically estimated breaks 单独登记且当前为空。事件时间邻近也不构成因果归因。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">每次运行使用共同连续月度样本，报告 AIC、BIC、HQIC，并按确定性项数量正确计算参数门和信息准则。BIC 选出的滞后始终是正式 baseline；完整滞后诊断网格可登记更高阶的“诊断充分备选”，但不会静默替换 baseline。调整 Portmanteau 的 h=12 是主诊断，h=18/24 是较长视野敏感性诊断：6/12 月动态响应要求 h=12 通过，18 月还要求 h=18，24 月还要求 h=24。动态响应是依赖变量排序、没有置信区间的正交化简化式点响应，不是结构冲击或因果效应。</p></div>
      </div>
      <div className="mt-5 border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">Finite-Sample Stationarity Calibration</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">平稳性规格由 profile 预先决定，不能看完结果再选择。baseline v2 的 Monte Carlo null 为带固定月度确定性增量的零频单位根，逐次使用与生产端完全相同的 constant、11 month dummies（January reference）、最大滞后、共同样本 AIC、最终样本重估与 tau 定义。校准表覆盖 N=96–168 九个节点、每节点 50,000 次、固定 seed，并按输入序列长度线性插值；每次正式判断记录上下校准点和权重。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">MacKinnon regression=c 仍是 constant-only ADF 的正式参考，也是 v1.43 seasonal-dummy tau 的历史复现值。标准条件下加入固定季节虚拟变量可能不改变零频 DF 的渐近分布，但 asymptotic equivalence 不等于 finite-sample equality，因此 v2 单独校准。完整经验 null CDF 未发布，p_value 保持 null；Python OLS 只验证回归、标准误和 tau，不单独证明临界值正确。</p></div>
      <div className="mt-5 border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">启用条件</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">来源、年份、单位、状态、更新时间、定义可比性和样本覆盖未通过时不运行。简化式 VAR 至少需要 60 个连续有效月度观测，并须通过已登记变换、profile-mapped stationarity specification、共同样本滞后选择、参数数量与稳定性闸门。ADF borderline 最多允许系数估计并显示警告，不开放动态响应；残差门按 6/12/18/24 月视野分别判定，不能用较短视野通过来宣称全部视野可用。KPSS、HEGY seasonal unit root、Zivot–Andrews structural break、残差 LM、bootstrap IRF 区间、SVAR、Local Projections、Bayesian VAR、Formal Event Study 与因果政策分析仍未启用。</p></div>
      <p className="mt-4 text-sm text-[var(--muted)]">所有输出是研究工具，不是客观风险真值、概率、投资建议、选举预测或因果结论。</p>
    </Section>

    <Section id="events" label="03 / Events" title="事件编码"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">Source → Event → Coding → Affected Indicator / Project → Research context。date、actor、event_type、direction 和 confidence 用于检索与解释；它们不自动构成因果关系，也不直接改变模型分数。未完整编码、低置信度或结构样例保持 enters_model=false。</p><Link href="/news" className="mt-4 inline-flex text-sm font-semibold text-[var(--accent)]">进入 Event Library</Link></Section>

    <Section id="high-frequency" label="03b / High-Frequency & Events" title="高频数据与事件窗口分析"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">高频层使用 Eurostat 月度序列（HICP 指数与年通胀率分列、统一失业率季调、工业生产指数季调日历调整），自 2015-01 起；缺口保持 missing，绝不插值。序列记录 seasonal adjustment、index reference、definition version、value semantics 与 revision 状态（latest revised）。v1.31 起 HICP 正式迁移到合并数据集 prc_hicp_minr（ECOICOP ver.2，全项代码 TOTAL）：月度指数固定使用 2015=100 参考基（该 unit 仍由 prc_hicp_minr 正式提供，不与 2025=100 拼接），旧表 prc_hicp_midx / prc_hicp_manr 已退役；迁移前后 2024-01 至 2025-12 重叠窗口一致性已逐国验证并记录在 hicp_migration_manifest.json，全项序列跨分类过渡保持连续（all-items continuity verified）。月度失业率（une_rt_m）为 15–74 岁活跃人口百分比的协调估计：各国月度构建方法可以不同，不是完全同质的原始调查月度值。工业生产指数（sts_inpr_m）为 B–D 合计、季调日历调整，index reference 逐条记录以避免参考基更新造成静默断点。覆盖检查使用起始月到最新可得月之间的完整月序列，API 未返回的月份同样计为缺失；每个序列记录 latest_available_period、expected_latest_period 与 publication lag 状态，区分正常发布滞后与异常停滞。</p><p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--muted)]">事件窗口分析（Event Window Analysis）是描述性第一级分析：严格区分事件前（relative_month &lt; 0）、事件期（relative_month = 0，单独报告）与事件后（relative_month &gt; 0），事件月不进入事件后均值与事件后观测计数；完整窗口要求至少 12 个事件前与 6 个真正的事件后月度观测。变化语义由数据定义驱动：比率类序列（失业率、HICP 年通胀率）只报告百分点变化，指数类序列报告指数点变化并附相对百分比变化；图表在缺失月份断线，不做视觉插值。窗口内存在其他已核验事件时给出同期事件提示。它不自动识别因果关系——观察到的变化不能归因于单一事件。Formal Event Study 保持 registry_only。</p></Section>

    <Section id="spatial" label="04 / Spatial" title="空间与边界"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">区域记录通过 region_id、行政层级、边界版本、来源、许可和年份关联。国家值不下推到区域，NUTS2 与 NUTS3 不混用。真实边界只有在来源、许可、坐标系、几何、拓扑和主键检查通过后才开放；地图不提供风险、预测、情景影响或真实党派支持率图层。</p></Section>

    <Section id="validation" label="05 / Validation" title="质量检查与已知限制"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">验证覆盖确定性、权重、标准化边界、缺失值、年份对齐、情景零冲击、参数界限和复现。Expected unavailable 表示准入闸门按规则阻止输出，不是错误。</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]"><strong>Validation ≠ scientific proof.</strong> 当前只声称 <strong>Historical reconstruction readiness</strong> 与方向性验证；没有 point-in-time vintage data 时，不报告预测准确率。事件关联不等于因果，项目库不等于项目普查，confidence 不等于发生概率。</p><div className="mt-5 flex flex-wrap gap-3"><a href={`${basePath}/research-data/validation_registry.json`} className="text-sm font-semibold text-[var(--accent)]">Validation registry</a><a href={`${basePath}/research-data/golden_test_cases.json`} className="text-sm font-semibold text-[var(--accent)]">Golden tests</a></div></Section>

    <Section id="citation" label="06 / Citation" title="引用与下载"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">引用应包含平台版本、访问日期和稳定 URL。具体 observation、事件、项目、模型或情景应同时引用其记录标识和原始来源；平台不会伪造 DOI。</p><div className="mt-5"><CitationActions plainText={platformCitation()} apaText={platformApaCitation()} bibtexText={platformBibtexCitation()} label="复制平台引用" /></div><div className="mt-5 flex flex-wrap gap-3"><a href={`${basePath}/research-data/${getResearchPackageFilename()}`} className="rounded-lg bg-[var(--foreground)] px-4 py-2 text-sm font-semibold text-white">下载完整研究数据包（ZIP）</a><a href={`${basePath}/research-data/release_manifest.json`} className="rounded-lg border border-[var(--line)] px-4 py-2 text-sm font-semibold">Release manifest</a></div></Section>
  </main>;
}
