import type { Locale } from "@/i18n/config";
const en = {
  periodCount: "Available periods in selected range", historicalLink: "Open historical archive (not a current map period)", sorsCpi: "Serbia CPI annual index (SORS; not HICP)", projectLocations: "Verified project locations", latestEvents: "Latest verified events", eventBoundary: "Original-language records (Chinese; untranslated). Events do not enter model estimates.", nav: "Workspaces",
  title: "Research Workspaces", intro: "Begin with a substantive question, discover existing evidence and continue into the established tools. No answers, new estimates or findings are generated here.",
  dataFirst: "Data-first: I need an indicator or dataset.", methodFirst: "Method-first: I need a particular estimator.", questionFirst: "Question-first: I have a substantive research question.",
  open: "Open workspace", countries: "Countries", secondary: "Compare with (optional)", none: "None", from: "From year", to: "To year", select: "Research setup", questions: "1. What can I study here?", data: "2. What data are available?", patterns: "3. What patterns can I inspect?", events: "4. What events provide historical context?", regions: "5. What regional evidence exists?", methods: "6. Which existing methods can be used?", boundaries: "7. What cannot be concluded?", continue: "8. Continue into existing tools", export: "9. Export the current research setup",
  dataLink: "Open in Data Explorer", modelLink: "Open in Models", mapLink: "Open in Map", eventLink: "Open in Event Library", coverage: "Available coverage", latest: "Latest available period", gaps: "Incomplete coverage / unavailable countries", count: "Non-missing records", source: "Source", empty: "No matching verified records in this selection.", noMethod: "Use the regional map for descriptive evidence; no separate estimation method is attached.", comparisonUnavailable: "Comparison unavailable for this indicator under the current definition/unit gate.", comparisonNote: "Separate country links only. The existing tool retains final sample and comparability gates; no new combined table, ranking or pooled sample is created here.",
  active: "active", registry_only: "registry_only — not runnable", blocked: "blocked — not runnable", limitation: "Existing limitation", original: "Original-language record (untranslated)", periodNote: "Endpoints do not guarantee continuous coverage. Layers and vintages remain separate; selected years filter evidence, not formal model samples. Macro-driver and SORS tools retain their own time controls; those links select the series, not this date range.", history: "Historical descriptive layers available where recorded; breaks remain excluded from continuous comparisons. Historical regional records open their archive, not an unsupported historical map period.", snapshot: "Export research workspace", preparing: "Preparing…", done: "Download initiated", error: "Export failed", exportNote: "The ZIP records this setup, evidence-source summary and reproducible tool links. It contains no underlying dataset or formal estimates. Links reproduce settings, not future data revisions.", evidence: "Evidence types: official indicators, verified events, regional records and existing methods.", titleCoverage: "Observed endpoints across relevant evidence; not coverage of every indicator.", rangeError: "From year must not exceed to year.", all: "All workspaces", sourceLayer: "Data layer", projectNote: "Project records preserve original provenance and location confidence; no investment-effect inference.",
};
type Messages = typeof en;
const zh: Messages = {
  periodCount: "所选范围有记录的时期数", historicalLink: "打开历史归档（不是当前地图时期）", sorsCpi: "塞尔维亚 CPI 年度同比指数（SORS；非 HICP）", projectLocations: "已核验项目位置", latestEvents: "近期已核验事件", eventBoundary: "原始语言记录（中文，未翻译）；事件不进入模型估计。", nav: "研究问题",
  title: "研究问题工作区", intro: "从实质研究问题出发，发现已有证据，再进入现有工具。本页不自动回答问题，不生成新估计或研究结论。",
  dataFirst: "数据优先：我需要一个指标或数据集。", methodFirst: "方法优先：我需要一个特定估计方法。", questionFirst: "问题优先：我有一个实质研究问题。",
  open: "打开工作区", countries: "国家", secondary: "对比国家（可选）", none: "无", from: "起始年份", to: "结束年份", select: "研究设置", questions: "1. 可以研究什么？", data: "2. 有哪些数据？", patterns: "3. 可以检查哪些模式？", events: "4. 哪些事件提供历史背景？", regions: "5. 有哪些区域证据？", methods: "6. 哪些现有方法可以使用？", boundaries: "7. 不能得出哪些结论？", continue: "8. 进入现有工具", export: "9. 导出当前研究设置",
  dataLink: "在数据浏览器打开", modelLink: "在模型中打开", mapLink: "在地图打开", eventLink: "在事件库打开", coverage: "实际覆盖范围", latest: "最新可用时期", gaps: "覆盖不完整 / 无记录国家", count: "非空记录数", source: "来源", empty: "当前选择没有匹配的已核验记录。", noMethod: "使用区域地图检查描述性证据；未挂接独立估计方法。", comparisonUnavailable: "该指标在当前定义 / 单位门禁下不可比较。", comparisonNote: "仅提供各国独立链接；现有工具保留最终样本与可比性门禁，本页不新建合并表、排名或池化样本。",
  active: "active · 已启用", registry_only: "registry_only · 不可运行", blocked: "blocked · 不可运行", limitation: "现有限制", original: "原始语言记录（未翻译）", periodNote: "起止时期不代表连续覆盖。数据层与地理版本保持分离；所选年份筛选证据，不改变正式模型样本。宏观驱动与 SORS 工具保留各自时间控件；链接选择序列，不应用这里的日期范围。", history: "存在记录时可查看历史描述层；断点仍不能连续比较。区域历史记录打开归档，不伪造工具未支持的历史地图时期。", snapshot: "导出研究工作区", preparing: "正在准备…", done: "已触发下载", error: "导出失败", exportNote: "ZIP 记录研究设置、证据来源摘要与可复现工具链接，不包含底层数据或正式估计。链接复现设置，不能锁定未来数据修订。", evidence: "证据类型：官方指标、已核验事件、区域记录与现有方法。", titleCoverage: "相关证据的实际起止时期，不代表所有指标的完整覆盖。", rangeError: "起始年份不能晚于结束年份。", all: "全部工作区", sourceLayer: "数据层", projectNote: "项目记录保留原来源与位置置信度，不作投资效应推断。",
};
export const workspaceMessages: Record<Locale, Messages> = { "zh-CN": zh, en };
