import Link from "next/link";
import { notFound } from "next/navigation";
import { pageMetadata } from "@/lib/seo";
import { CountryComparePanel } from "@/components/CountryComparePanel";
import { getCountryObservations, getEventsForCountry, getProjectsForCountry, getResearchCountryBySlug, researchCountries, researchIndicators } from "@/lib/researchData";
import { getModelOutputsForCountry } from "@/lib/modelFramework";
import { regionalCoverageMatrixV087 } from "@/lib/spatialDataV087";
import { countryDescriptions, englishCapital, englishUnit } from "@/i18n/presentation";
import { localeNumber } from "@/i18n/config";
const compareIds = new Set(["gdp_current_eur", "gdp_per_capita_eur", "real_gdp_growth", "hicp_inflation", "unemployment_rate", "government_debt_gdp"]);
type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return researchCountries.map(country => ({ slug: country.slug })); }
export async function generateMetadata({ params }: Props) {
  const { slug } = await params;
  const country = getResearchCountryBySlug(slug);
  return country ? pageMetadata({ locale: "en", path: `/en/countries/${slug}/`, title: `${country.name} research profile`, description: countryDescriptions[slug], image: `/og/countries/${slug}.png`, imageAlt: `${country.name} — country research profile` }) : {};
}
export default async function EnglishCountry({ params }: Props) {
  const { slug } = await params;
  const country = getResearchCountryBySlug(slug);
  if (!country) notFound();
  const observations = getCountryObservations(slug);
  const latest = researchIndicators.map(indicator => ({ indicator, observation: observations.filter(row => row.indicator === indicator.id).at(-1) })).filter(item => item.observation);
  const events = getEventsForCountry(slug).filter(event => event.data_status === "verified");
  const projects = getProjectsForCountry(slug);
  const modelOutputs = getModelOutputsForCountry(slug);
  const regionalMapAvailable = Boolean(regionalCoverageMatrixV087.find(row => row.country_id === slug)?.public_layer_count);
  return <main className="page-shell"><header className="max-w-4xl border-b border-[var(--line)] pb-8"><p className="editorial-kicker">Country Research Profile</p><h1 className="mt-4 text-5xl font-semibold">{country.name}</h1><p className="mt-3 text-lg text-[var(--muted)]">{englishCapital(country.capital)} · {country.currency}</p><p className="mt-5 leading-7 text-[var(--muted)]">{countryDescriptions[slug]}</p></header>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Latest annual observations</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Each indicator retains its latest available year, original source and status. Different years are not a common-year comparison. Missing values remain missing.</p><div className="data-table-viewport mt-4" tabIndex={0} role="region" aria-label="Latest annual observations (scrollable)"><table className="research-data-table min-w-[650px] w-full text-left text-sm"><thead><tr>{["Indicator", "Year", "Value", "Unit", "Status", "Source"].map(label => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{latest.map(({ indicator, observation: row }) => <tr key={indicator.id}><th scope="row" className="px-3 py-2">{indicator.name}</th><td className="px-3 py-2">{row!.year}</td><td className="metric-number px-3 py-2">{localeNumber(row!.value, "en")}</td><td className="px-3 py-2">{englishUnit(row!.unit)}</td><td className="px-3 py-2">{row!.status}</td><td className="px-3 py-2"><a href={row!.source_url} target="_blank" rel="noreferrer" className="text-[var(--accent)]">{row!.source_name}</a></td></tr>)}</tbody></table></div><Link href={`/en/data/?country=${slug}`} className="mt-4 inline-flex text-[var(--accent)]">Explore all observations and descriptive history</Link></section>
    <CountryComparePanel current={slug} countries={researchCountries.map(c => ({ slug: c.slug, name_zh: c.name_zh }))} mapCountries={regionalCoverageMatrixV087.filter(row => row.public_layer_count).map(row => row.country_id)} points={researchCountries.flatMap(c => getCountryObservations(c.slug).filter(row => compareIds.has(row.indicator)).map(row => ({ country: c.slug, indicator: row.indicator, year: row.year, value: row.value, unit: row.unit, source_name: row.source_name, source_url: row.source_url, source_reliability: row.source_reliability, updated_at: row.updated_at, status: row.status })))} />
    <section className="card mt-8 p-6"><h2 className="text-2xl font-semibold">Research tools and boundaries</h2><p className="mt-3 leading-7 text-[var(--muted)]">Review model availability and inputs in the model workspace. Descriptive observations do not establish causal effects. Scenarios remain conditional illustrations, not forecasts.</p><nav className="mt-4 flex flex-wrap gap-5"><Link href={`/en/models/?country=${slug}`}>Models</Link><Link href={`/en/map/?country=${slug}`}>Regional facts</Link><Link href={`/en/scenarios/?country=${slug}`}>Scenarios</Link><Link href="/en/methodology/">Methodology</Link></nav></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Events and original reporting</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Original event summaries below are in Chinese and have not been translated. They remain separate from model results and causal claims.</p>{events.map(event => <article className="card mt-4 p-5" key={event.event_id}><p className="text-xs text-[var(--muted)]">{event.date} · {event.event_type} · {event.data_status}</p><div lang="zh-CN" data-original-language="zh-CN"><h3 className="mt-2 text-lg font-semibold">{event.title}</h3><p className="mt-3 text-sm leading-7">{event.summary}</p></div>{event.source_url && <a className="mt-3 inline-flex text-[var(--accent)]" href={event.source_url} target="_blank" rel="noreferrer">Original source: <span lang="zh-CN" data-original-language="zh-CN">{event.source_name}</span></a>}</article>)}</section>
    <section className="card mt-8 p-6"><h2 className="text-2xl font-semibold">Country research availability</h2><dl className="mt-4 grid gap-4 sm:grid-cols-3">{[["Regional facts", regionalMapAvailable ? "Public regional layers available" : "Pending public regional coverage"], ["Event records", String(events.length)], ["Registered projects", String(projects.length)]].map(([label, value]) => <div key={label}><dt className="text-sm text-[var(--muted)]">{label}</dt><dd className="mt-2 font-semibold">{value}</dd></div>)}</dl><p className="mt-4 text-sm leading-7 text-[var(--muted)]">No registered record does not mean no activity exists. Regional coverage is descriptive and does not imply comparable national or cross-country model support.</p><h3 className="mt-6 text-xl font-semibold">Descriptive composite-model outputs</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Scores below retain canonical country coverage and completeness. A score is not a causal estimate, prediction, risk probability or authorization for formal inference.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{modelOutputs.map(output => <article key={output.model_id} className="border border-[var(--line)] p-4"><h4 className="font-semibold">{output.model_id.replaceAll("_", " ")}</h4><p className="mt-2 text-sm">{output.availability} · completeness {localeNumber(output.data_completeness, "en")}%</p><p className="metric-number mt-2 text-xl">{localeNumber(output.score, "en", { maximumFractionDigits: 1 })}</p></article>)}</div></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Registered project evidence</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Project names, attributed record prose and source titles remain in their original language. Verification status is not evidence of a causal effect.</p>{projects.length ? projects.map(project => <article key={project.id} className="card mt-4 p-5"><div lang="zh-CN" data-original-language="zh-CN"><h3 className="font-semibold">{project.name}</h3><p className="mt-2 text-sm">{project.city} · {project.sector}</p><p className="mt-3 text-sm leading-7">{project.verification_note}</p></div><p className="mt-3 text-xs">Verification status: {{ "可量化": "Quantifiable", "部分可量化": "Partly quantifiable", "仅作背景": "Context only", "不进入分析": "Excluded from analysis" }[project.verification_status]}</p><a href={project.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-[var(--accent)]">Original source: <span lang="zh-CN" data-original-language="zh-CN">{project.source_name}</span></a></article>) : <p className="mt-4 text-sm text-[var(--muted)]">No projects are currently registered.</p>}</section>
  </main>;
}
