import { BIS_TRANSLATION_NOTICE_ZH, SOURCE_ATTRIBUTIONS } from "@/lib/sourceAttribution";
import type { Metadata } from "next";
import { datasetJsonLd, jsonLdHtml, pageMetadata } from "@/lib/seo";
import Link from "next/link";
import { runtimeAnalysisSkills } from "@/lib/analysisSkills";
import { AnalysisSkillCard } from "@/components/AnalysisSkillCard";
import { CitationActions } from "@/components/CitationActions";
import { platformStatus } from "@/lib/platformStatus";
import publicationBoundary from "@/data/macro/var_dynamic_response_publication_boundary.json";
import residualAttribution from "@/data/macro/var_portmanteau_attribution.json";
import residualPeriods from "@/data/macro/var_residual_period_concentration.json";
import residualProbes from "@/data/macro/var_residual_specification_probe_results.json";
import countryMatched from "@/data/macro/var_country_matched_bootstrap_calibration_summary.json";
import countryAudit from "@/data/macro/var_country_lag_identifiability_results.json";
import countryPhaseB from "@/data/macro/var_phase_b_bootstrap_results.json";
import lagCharacterization from "@/data/macro/var_lag_characterization_research_conclusion.json";
import selectionBootstrapSummary from "@/data/macro/var_selection_bootstrap_calibration_summary.json";
import layerBDecomposition from "@/data/macro/var_residual_diagnostic_layerB_selection_decomposition.json";
import { getResearchPackageFilename, platformApaCitation, platformBibtexCitation, platformCitation } from "@/lib/releaseMetadata";
import { KickerVersion } from "@/components/KickerVersion";

export const metadata: Metadata = pageMetadata({ title: "研究方法", description: "数据、模型、事件、空间、验证和引用规则。", path: "/methodology/" });

const pct = (value: number, digits = 2) => `${(value * 100).toFixed(digits)}%`;
const layerBByLag = layerBDecomposition.layer_B_by_true_lag;
const layerBSpecLabels = { constant: "常数项", constant_plus_11_month_dummies: "常数项 + 11 个月份虚拟变量" } as const;
const worstLayerBEs = layerBDecomposition.worst_layer_B_es_cell;
const layerAEs = layerBDecomposition.layer_A_summary.edgerton_shukur_f;
const p2Under = layerBByLag["2"].by_deterministic_spec;
const p1MonthRanges = layerBByLag["1"].by_deterministic_spec.constant_plus_11_month_dummies.h12_rejection_rate_range;

const attributionTop3 = residualAttribution.units.map((unit) => unit.top_3_lag_share);
const pandemicMass = residualPeriods.units.map((unit) => unit.periods.P2_pandemic_aftermath.mahalanobis_share);
const maxProbeReduction = Math.max(...residualProbes.units.flatMap((unit) => Object.values(unit.probes).map((probe) => probe.change_vs_production.q_star_12_reduction)));
const matchedSize = (design: string) => countryMatched.null_by_design_primary_size.find((row) => row.design === design)?.bootstrap_range ?? [0, 0];
const matchedPower = (alternative: string, strength: number) => countryMatched.power_by_alternative.find((row) => row.alternative === alternative && row.strength === strength)?.bootstrap_median ?? 0;
const countryNames: Record<string, string> = { poland: "波兰", romania: "罗马尼亚", czechia: "捷克", germany: "德国", hungary: "匈牙利" };
const lagRecovery = lagCharacterization.true_lag_2_bic_exact_recovery_range_by_design_primary;
const lagRange = (design: keyof typeof lagRecovery) => `${pct(lagRecovery[design][0], 1)}–${pct(lagRecovery[design][1], 1)}`;
const bootstrapIid = selectionBootstrapSummary.families.recursive_iid_residual;
const bootstrapWild = selectionBootstrapSummary.families.recursive_wild_rademacher;

const sections = [["data", "Data"], ["baseline-data-definitions", "Baseline definitions"], ["panel-lp-whole-path-inference", "Panel LP whole-path boundary"], ["models", "Analysis"], ["var-residual-diagnostic-calibration", "VAR residual diagnostics"], ["var-selection-aware-bootstrap", "VAR bootstrap research"], ["var-lag-selection-characterization", "VAR lag-selection research"], ["var-country-identifiability", "VAR country audit"], ["var-country-matched-bootstrap", "VAR bootstrap calibration"], ["var-residual-attribution", "VAR residual attribution"], ["var-publication-boundary", "VAR publication boundary"], ["events", "Events"], ["macro-drivers", "Macro Drivers"], ["spatial", "Spatial"], ["validation", "Validation"], ["citation", "Citation"]] as const;

function Section({ id, label, title, children }: { id: string; label: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-24 border-t border-[var(--line)] py-10"><p className="editorial-kicker">{label}</p><h2 className="mt-3 text-3xl font-semibold">{title}</h2>{children}</section>;
}

export default function MethodologyPage() {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
  return <main className="page-shell">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLdHtml(datasetJsonLd({ path: "/methodology/", name: "Central Europe Political Atlas — research data and methodology", description: "Data definitions, analysis methods, inference boundaries, validation and citation rules for the Central Europe Political Atlas research package." })) }} />
    <header className="max-w-4xl border-b border-[var(--line)] pb-8"><p className="editorial-kicker">Research / <KickerVersion version={platformStatus.version} /></p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em]">研究方法与边界</h1><p className="mt-5 text-base leading-8 text-[var(--muted)]">本页说明公开研究流程和不能说明什么。完整字典、QA、版本记录与技术字段保留在研究数据包，不再占据主要页面。</p><nav className="mt-5 flex flex-wrap gap-3">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className="text-sm font-semibold text-[var(--accent)]">{label}</a>)}</nav></header>

    <Section id="data" label="01 / Data" title="数据如何进入平台"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">每条正式观测必须有国家或地区、时间、数值、单位、来源名称、来源链接、可靠性、状态和更新时间。official / verified 可进入相应事实层；pending 保留但不参与比较；sample 与 placeholder 不进入分析。A 级为官方统计或机构，B 级为可核验权威来源，C 级只作线索，D 级排除。</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]">跨国比较只使用同定义、同单位、同层级和共同年份。计算值必须保留分子、分母、公式和来源。</p><Link href="/data" className="mt-4 inline-flex text-sm font-semibold text-[var(--accent)]">打开 Data Explorer</Link></Section>

    <Section id="baseline-data-definitions" label="01b / Baseline Data Definition Notes" title="正式基线的数据定义说明">
      <p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">波兰工业生产指数在 2021 年由 LEU 统计单位切换到 KAU。官方材料允许部分 aggregate 出现轻微断点；当前 2015–2025 formal sample 继续保留并保持 analysis-eligible，但只表述为非阻断方法学警示，不宣称完全可比。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--muted)]">匈牙利月度失业率从 2023 年采用 state-space 估计，Eurostat 说明 2011–2022 已回溯修订。因此当前基线按 latest-revised series 解释，不扩展为实时历史版本一致性的主张。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--muted)]">斯洛文尼亚长期收益率的 2025 年观测带 estimated-value flag。这是质量标记，不是定义断点，也不自动改变分析准入。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--muted)]">这些记录属于 data-definition / revision transparency，不是 alternative specifications，也不是 causal robustness tests。固定八国四指标的<Link href="/historical-extension" className="text-[var(--accent)] underline">历史扩展研究已结案</Link>：审计完成，但 Design A 因 IPI 与失业率定义证据缺口而受阻，未运行历史 Panel LP。</p>
    </Section>

    <Section id="panel-local-projections" label="Aggregate-Shock Panel LP" title="共同冲击、时间聚类与组间异质性">
      <p className="mt-4 text-sm leading-7">v1.81 保持等国家权重的正式平衡八国面板不变。逐一删去一国仅作固定组成诊断，保留基准各预测期月份日历和冲击支持；3 对 4 或 4 对 3 的对比编码为欧元组 +n_N/N、非欧元组 −n_E/N，横截面均值为零且两组编码之差为一。</p>
      <p className="mt-3 text-sm leading-7">LOCO 范围不是置信区间，不计算国家 jackknife 标准误，不表示某国因果贡献。报告 h=0–6、7–12、13–24 的绝对变化及符号、95% 点态含零分类一致率；基准绝对值小于 max(10⁻¹⁰, 0.1×基准标准误) 时不报告相对变化，该规则仅避免不稳定比例，不是稳健性判定阈值。</p>
      <p className="mt-3 text-sm leading-7">基准与 time-FE 的含零分类不同称为“规格敏感”，不自动宣布结果无效，也不替换国家固定效应基准。整条路径相关系数只是描述统计，不是路径显著性检验；跨预测期联合推断研究已按 v1.82 正式结案，当前不发布联合带或全路径检验。</p>
      <p className="mt-4 text-sm leading-7">Panel LP 采用独立离线实现，依据 Almuzara–Sancibrián 的 t-LAHR 方法，联合估计冻结的 JK MP 与 CBI。主设计使用国家固定效应、滞后增广和按月份聚类的得分协方差；HICP 加入 11 个月份季节项，不加入会吸收共同冲击的完整时间固定效应。</p>
      <p className="mt-3 text-sm leading-7">固定欧元组为 AT、DE、SK、SI，固定非欧元组为 CZ、HU、PL、RO。8 国不等于 8 次独立冲击；面板行数不等于独立冲击观测数；时间聚类不等于国家聚类。两组都不代表其所在整个地区，面板估计也不是单国 LP 结果的简单平均。</p>
      <p className="mt-3 text-sm leading-7">每期直接检验欧元组减非欧元组的差异，只提供点态区间，不作整条路径显著不同的结论。国家加时间固定效应的对比项回归仅作为组间差异敏感性分析。面板跨预测期联合置信带已研究但未达到 95% 联合覆盖门槛，当前被阻断；IK 小样本修正和国家对国家正式检验保持 registry_only。</p>
      <p className="mt-3 text-sm leading-7">克罗地亚因 2023 年加入欧元的制度断点排除；塞尔维亚因共同月度覆盖不足排除。固定 8 国不得因缺测改为 7 国；每期至少 96 个有效月份，预测期从 24 个月依次尝试 18、12、6，缩短必须公开说明。</p>
    </Section>
    <Section id="panel-lp-whole-path-inference" label="Panel LP / v1.82" title="Panel LP Whole-Path Inference Research Outcome">
      <p className="mt-4 max-w-4xl text-sm leading-7">逐期（点态）区间回答某一个预测期的响应范围；把整条 0–24 个月路径作为一个整体判断，需要联合置信带并控制整条路径的覆盖。本页只提供已验证的逐期区间，点态区间不能合起来当整条路径置信带。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">跨预测期联合推断已经研究，但当前验证程序未达到 95% 联合覆盖门槛，因此不发布联合置信带，也不提供全路径显著性检验。这是当前固定八国 Panel LP、当前研究程序及已完成验证范围内的结论，不表示联合推断在数学上不可能。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">冻结标准误下的高斯联合临界值约为 2.51–2.92；拟合模型模拟所需的联合临界值约为 3.71–5.18。最佳 bootstrap 联合覆盖约为 90.0%（90% 区间 88.6–91.4%），低于名义 95%。R2 裁决为 NOT CONFIRMED，没有路径获准启用；缩减范围及其负责人确认发生在结果已知之后，仍标记为事后事项。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">Panel LP 估计、点态推断、组成诊断、time-FE 敏感性和无推断的描述性拟合模型对照继续有效。拟合模型路径默认关闭，不是结构脉冲响应或预测，也不附带区间或推断 p 值。完整研究来源以文件名和 SHA-256 登记在 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/panel-local-projections/panel_lp_joint_inference_research_conclusion.json`}>联合推断研究结论记录</a>；研究档案中的模拟数组、checkpoint 和 solver 日志不随包公开。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">重新开启这条研究线需要新的方法依据、事前注册、未使用过的随机种子命名空间和负责人批准，并将新研究保存在独立档案中。可能方向仅作未来研究登记，不是当前待办事项。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">另有独立的<Link href="/historical-extension" className="text-[var(--accent)] underline">历史月度数据延伸研究结论</Link>：审计已经完成，固定八国四指标扩展受阻；当前研究程序关闭，没有重新估计 Panel LP。</p>
    </Section>
    <Section id="analysis-registry" label="Analysis Registry" title="分析方法与当前状态">
      <p className="mt-4 text-sm">方法状态、解释边界与工作台导航共同读取同一份 canonical registry。方法已启用不表示所有数据组合均通过准入。</p>
      <div className="grid gap-4 md:grid-cols-2">{runtimeAnalysisSkills.map((skill) => <AnalysisSkillCard key={skill.skill_id} skill={skill} />)}</div>
    </Section>
    <Section id="models" label="02 / Analysis" title="透明分析方法">
      <p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">所有方法统一通过 Analysis Runner：输入数据 → 计算 → diagnostics → result → consistency。综合指标继续使用既有标准化与权重；Scenario 仍是条件参数预设，不改写原始数据。</p>
      <div className="mt-5 grid gap-5 md:grid-cols-2">
        <div className="border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">Panel Econometrics</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">年度面板必须至少覆盖 8 国、8 年，并有至少 4 个关键可比变量达到 75% 覆盖。当前支持 Pooled OLS、Country FE、Country + Year FE。HC1 稳健标准误使用渐近正态推断；按国家聚类标准误使用聚类稳健协方差 + Student-t 参考分布（df = G − 1），聚类数小于 20 时给出不精确提示，小于 8 时阻止运行。系数表示条件关联，固定效应不自动构成因果识别。</p></div>
        <div className="border-l-2 border-[var(--line)] pl-5"><h3 className="font-semibold">Trade Network Analysis</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">贸易网络基于 UN Comtrade 十国 2015–2025 完整双边货物边。正式覆盖闸门只计算 network_eligible 伙伴：eligible partner sum / World total ≥ 0.95；World 与 Other … nes 等聚合记录保留但不进入网络节点，也不帮助闸门通过。未达标的国家 × 年份 × 流向组合不输出正式网络指标。贸易集中度 ≠ 经济风险，中国份额 ≠ 政治依赖，网络位置 ≠ 政治影响。</p></div>
        <div className="border-l-2 border-[var(--accent)] pl-5 md:col-span-2"><h3 className="font-semibold">Reduced-form VAR / 宏观动态</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">v1.44 并列保留两个预注册正式基线：baseline v1 使用 constant VAR + ADF constant；baseline v2 使用相同变量、变换、样本和 BIC 政策，但采用 constant + 11 个月份虚拟变量，并以 finite-sample calibrated seasonal-dummy ADF 作为正式平稳性闸门。旧 v1.43 MacKinnon-c 判断继续作为历史参考，不覆盖。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">HICP 月度指数与年率来源均为 NSA，但年率已包含 12 个月同比比较，不能机械套用月度指数的季节风险判断。工业生产来源为 SCA、失业率来源为 SA；v2 的系统月份项主要吸收剩余 calendar/month effects，不是重新季调这些来源序列，也不改写原始观测。探索性规格继续使用 constant-only ADF，只能沿登记链尝试替代变换，不能冒充任一正式基线。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Deterministic seasonality ≠ seasonal unit root ≠ structural break ≠ persistent stationary process。seasonal-dummy ADF 只检验登记确定性项下的零频单位根；HEGY 尚未实现。Zivot–Andrews 仍为 registry_only，因为生产实现与跨语言 reference fixture 尚未对齐；2020-03、2021-H2 与 2022-02 只是 historical candidate periods，statistically estimated breaks 单独登记且当前为空。事件时间邻近也不构成因果归因。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">每次运行使用共同连续月度样本，报告 AIC、BIC、HQIC，并按确定性项数量正确计算参数门和信息准则。BIC 选出的滞后始终是正式 baseline；完整滞后诊断网格可登记更高阶的“诊断充分备选”，但不会静默替换 baseline。调整 Portmanteau 的 h=12 是主诊断，h=18/24 是较长视野敏感性诊断：6/12 月动态响应要求 h=12 通过，18 月还要求 h=18，24 月还要求 h=24。动态响应是依赖变量排序、没有置信区间的正交化简化式点响应，不是结构冲击或因果效应。</p></div>
        <div className="border-l-2 border-[var(--warning)] pl-5 md:col-span-2"><h3 className="font-semibold">Estimation vs Dynamic-Response Readiness</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]"><strong>Estimable</strong> 只表示登记变量、变换与样本下可以估计 VAR 系数；<strong>dynamic_response_ready</strong> 还要求平稳性、稳定性、参数门以及对应视野的残差诊断通过。两者不是同一状态。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">当前正式 baseline v1 可估计国家为 2 个（波兰、罗马尼亚），正式 baseline v2 可估计国家为 3 个（捷克、德国、匈牙利），但正式 dynamic-response-ready 国家为 0。VAR estimation active；formal dynamic-response currently unavailable。实现了依赖排序的正交化简化式响应，不表示当前存在可发布的正式 IRF。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">更高阶诊断充分滞后只保留为 sensitivity / diagnostic，不会在看过结果后替换 BIC 正式基线。简化式 innovation ≠ structural shock；Cholesky ordering ≠ structural identification。IRF uncertainty、bootstrap/Monte Carlo/delta-method 区间仍不可用；至少一个预设正式 profile 的至少一个国家通过完整动态响应门后，才存在进一步研究不确定性推断的发布目标。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">v1.85 状态：VAR 系数估计继续启用；正式 IRF 不可发布；v1.85 残差诊断校准研究已结案，没有符合条件的替代诊断（见 <a className="text-[var(--accent)] underline" href="#var-residual-diagnostic-calibration">VAR Residual Diagnostic Calibration Research Outcome</a>）。</p></div>
      </div>
      <div className="mt-5 border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">Finite-Sample Stationarity Calibration</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">平稳性规格由 profile 预先决定，不能看完结果再选择。baseline v2 的 Monte Carlo null 为带固定月度确定性增量的零频单位根，逐次使用与生产端完全相同的 constant、11 month dummies（January reference）、最大滞后、共同样本 AIC、最终样本重估与 tau 定义。校准表覆盖 N=96–168 九个节点、每节点 50,000 次、固定 seed，并按输入序列长度线性插值；每次正式判断记录上下校准点和权重。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">MacKinnon regression=c 仍是 constant-only ADF 的正式参考，也是 v1.43 seasonal-dummy tau 的历史复现值。标准条件下加入固定季节虚拟变量可能不改变零频 DF 的渐近分布，但 asymptotic equivalence 不等于 finite-sample equality，因此 v2 单独校准。完整经验 null CDF 未发布，p_value 保持 null；Python OLS 只验证回归、标准误和 tau，不单独证明临界值正确。</p></div>
      <div className="mt-5 border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">启用条件</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">来源、年份、单位、状态、更新时间、定义可比性和样本覆盖未通过时不运行。简化式 VAR 至少需要 60 个连续有效月度观测，并须通过已登记变换、profile-mapped stationarity specification、共同样本滞后选择、参数数量与稳定性闸门。ADF borderline 最多允许系数估计并显示警告，不开放动态响应；残差门按 6/12/18/24 月视野分别判定，不能用较短视野通过来宣称全部视野可用。Local Projections 使用后文独立的 identified-shock、N≥96、共同 horizon 和跨语言验证门禁。KPSS、HEGY seasonal unit root、Zivot–Andrews structural break、残差 LM、bootstrap VAR IRF 区间、SVAR、Bayesian VAR、Formal Event Study 与未登记因果政策分析仍未启用。</p></div>
      <p className="mt-4 text-sm text-[var(--muted)]">所有输出是研究工具，不是客观风险真值、概率、投资建议、选举预测或因果结论。</p>
    </Section>

    <Section id="var-residual-diagnostic-calibration" label="VAR / v1.85 · v1.851" title="VAR Residual Diagnostic Calibration Research Outcome">
      <p className="mt-4 max-w-4xl text-sm leading-7">VAR 的 h=12 残差自相关诊断决定的是<strong>动态响应能否发布</strong>，不决定系数估计能否进行。v1.85 在事前注册（SHA-256 f9ddab6a…18bb0b）下，用合成数据检验现行 adjusted Portmanteau 与两个预先登记的备选（Breusch–Godfrey LM、Edgerton–Shukur F）在有限样本下的实际拒绝率。本研究没有读取任何国家的真实数据，共 2,160,000 次模拟。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">72 个主单元分为两层。<strong>Layer A</strong> 按真实滞后阶数估计 VAR，只检验诊断统计量本身；<strong>Layer B</strong> 使用平台实际的共同样本 BIC 滞后选择，检验“选滞后 + 诊断”整个流程。合格门槛为：每个主单元的拒绝率 ≤ 7.5%，且至少 90% 的主单元落在 3.5%–6.5% 区间内。名义水平 5%。</p>
      <div className="mt-4 max-w-4xl overflow-x-auto" tabIndex={0} role="region" aria-label="数据表（可横向滚动）"><table className="w-full text-left text-sm"><thead><tr className="text-[var(--muted)]"><th className="py-2 pr-4 font-semibold">诊断</th><th className="py-2 pr-4 font-semibold">落在 3.5%–6.5% 的主单元</th><th className="py-2 pr-4 font-semibold">最大拒绝率（Layer A 与 B 合计）</th><th className="py-2 font-semibold">联合门槛</th></tr></thead><tbody><tr className="border-t border-[var(--line)]"><td className="py-2 pr-4">Adjusted Portmanteau（现行）</td><td className="py-2 pr-4">37.5%（27/72）</td><td className="py-2 pr-4">45.23%</td><td className="py-2">不合格</td></tr><tr className="border-t border-[var(--line)]"><td className="py-2 pr-4">Breusch–Godfrey LM</td><td className="py-2 pr-4">30.56%（22/72）</td><td className="py-2 pr-4">37.81%</td><td className="py-2">不合格</td></tr><tr className="border-t border-[var(--line)]"><td className="py-2 pr-4">Edgerton–Shukur F</td><td className="py-2 pr-4">79.17%（57/72）</td><td className="py-2 pr-4">12.88%</td><td className="py-2">不合格</td></tr></tbody></table></div>
      <p className="mt-3 max-w-4xl text-sm leading-7">两层指标含义不同。<strong>Layer A</strong> 已知真实滞后，并按真实滞后估计，是正确设定下诊断统计量的有限样本 size（conditional diagnostic size）。<strong>Layer B</strong> 先由 BIC 选滞后再做诊断；如果选出的滞后低于真实滞后，被选 VAR 本身欠拟合，残差白噪声原假设未必成立。因此 Layer B 的拒绝频率是“选滞后 + 设定 + 诊断”整个流程的拒绝率（selection-plus-diagnostic procedure rejection rate），不是纯粹的检验 size，表中 Layer B 数值不能读作 Type-I error。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">Edgerton–Shukur 在 Layer A 的正确设定、固定滞后设计中有限样本 size 校准良好：{layerAEs.cells_inside_0_035_to_0_065} / {layerAEs.cell_count} 个单元落在区间内，最大拒绝率 {pct(layerAEs.maximum_rejection_rate)}。这一结果不能外推为考虑滞后选择的平台验证。在 Layer B 中，完整流程校准不足：ES 最高流程拒绝率为 {pct(worstLayerBEs.es_h12_rejection_rate)}，未满足预注册的启用门。因此 ES 不是经过验证的替代诊断，也不作为正式门槛。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">v1.851 按冻结的 v1.85 模拟结果做了确定性分解（未产生新的随机数，也未重新模拟）。真实滞后为 1 时，BIC 几乎总是选中 1 阶；真实滞后为 2 时，按确定性项设定汇总，BIC 以 {pct(Math.min(p2Under.constant.pooled_underselection_rate, p2Under.constant_plus_11_month_dummies.pooled_underselection_rate))}–{pct(Math.max(p2Under.constant.pooled_underselection_rate, p2Under.constant_plus_11_month_dummies.pooled_underselection_rate))} 的频率选成 1 阶（单个单元 {pct(layerBByLag["2"].cell_underselection_rate_range[0])}–{pct(layerBByLag["2"].cell_underselection_rate_range[1])}）。在 true VAR(2) 主设计中，BIC 几乎总是选择 VAR(1)，因此 Layer B 的额外拒绝同时包含 lag underfitting 所造成的真实残差自相关；不能把全部超额拒绝解释为诊断统计量本身的 size distortion。</p>
      <div className="mt-4 max-w-4xl overflow-x-auto" tabIndex={0} role="region" aria-label="数据表（可横向滚动）"><table className="w-full text-left text-sm"><thead><tr className="text-[var(--muted)]"><th className="py-2 pr-4 font-semibold">Layer B 设计</th><th className="py-2 pr-4 font-semibold">BIC 选对</th><th className="py-2 pr-4 font-semibold">选少（underselection）</th><th className="py-2 pr-4 font-semibold">选多（overselection）</th></tr></thead><tbody>{(["1", "2"] as const).flatMap((lag) => (["constant", "constant_plus_11_month_dummies"] as const).map((spec) => { const row = layerBByLag[lag].by_deterministic_spec[spec]; return <tr key={`${lag}-${spec}`} className="border-t border-[var(--line)]"><td className="py-2 pr-4">真实滞后 {lag}，{layerBSpecLabels[spec]}</td><td className="py-2 pr-4">{pct(row.pooled_correct_selection_rate)}</td><td className="py-2 pr-4">{pct(row.pooled_underselection_rate)}</td><td className="py-2">{pct(row.pooled_overselection_rate)}</td></tr>; }))}</tbody></table></div>
      <p className="mt-3 max-w-4xl text-sm leading-7">例如 ES 流程拒绝率最高的单元（T=144、真实滞后 2、ρ=0.95、月份虚拟变量）中，BIC 在 {worstLayerBEs.selected_lag_counts["1"].toLocaleString("en-US")} 次重复里选 1 阶、{worstLayerBEs.selected_lag_counts["2"].toLocaleString("en-US")} 次选 2 阶，ES 拒绝率为 {pct(worstLayerBEs.es_h12_rejection_rate)}：该 cell 的高 rejection frequency 与几乎完全的 lag underselection 同时出现。冻结结果只保留了逐单元的选滞后频率和总体拒绝率，没有保留逐次重复的联合分布，所以无法重建“选对滞后时”或“选少滞后时”的条件拒绝率，也不能说有多少比例的拒绝由欠拟合造成。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">adjusted Portmanteau 未通过当前预注册的平台级门槛；在固定滞后的 Layer A 中，它的表现也明显不如 ES（Layer A 最大拒绝率 {pct(layerBDecomposition.layer_A_summary.pt_adjusted.maximum_rejection_rate)}）。在真实滞后为 1、BIC 几乎全部选对的 Layer B 单元中，PT 与 BG 的拒绝率在月份虚拟变量设定下仍达 {pct(Math.min(p1MonthRanges.pt_adjusted[0], p1MonthRanges.bg_lm[0]))}–{pct(Math.max(p1MonthRanges.pt_adjusted[1], p1MonthRanges.bg_lm[1]))}，因此这部分超额拒绝不能归因于滞后欠选。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">处置结论为 no_eligible_replacement：现行 h=12 adjusted Portmanteau 仍保留为既有 production gate，但当前 lag-selection + residual-diagnostic 联合流程未通过预注册的有限样本门（joint procedure gate failure）；预注册选择规则要求 Layer A 与 Layer B 一起通过，这一规则不因事后分解而改变，v1.85 决定仍为 no_eligible_replacement；没有替代诊断获准，Phase B 真实国家比较未获授权，国家就绪状态和生产引擎均未改变。残差诊断结果不否定 VAR 系数估计，它影响的只是动态响应发布门。正式 dynamic-response-ready 国家仍为 0，正式正交化 IRF 不可发布。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">事前注册、第 001 号笔误修正（只更正一个冻结输入的哈希，研究设计未改）、参照验证（4 个案例，最大数值差异 8.3×10⁻¹²）、种子登记、模拟设计、校准汇总、方法决定和研究结论均公开于 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-residual-diagnostics/var_residual_diagnostic_research_conclusion.json`}>残差诊断研究结论记录</a>。完整的逐单元模拟结果随研究数据包发布，并以 SHA-256 登记。逐单元选滞后分解见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-residual-diagnostics/var_residual_diagnostic_layerB_selection_decomposition.json`}>Layer B 选滞后分解</a>，解释修正见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-residual-diagnostics/var_residual_diagnostic_research_conclusion_amendment_001.json`}>研究结论修正 001</a>。未来的“VAR Lag-Selection × Residual-Diagnostic Joint Procedure Research”尚未开始，需要负责人批准和新的事前注册；它应首先研究滞后阶数恢复、欠选、过选、残差白噪声充分性与参数成本之间的关系，而不是寻找能让真实国家通过的新滞后规则。</p>
    </Section>
    <Section id="var-selection-aware-bootstrap" label="VAR / v1.86 research" title="Selection-Aware Bootstrap Calibration Research">
      <p className="mt-4 max-w-4xl text-sm leading-7"><strong>研究状态，不是生产方法。</strong>v1.86 事前注册并运行了一项合成数据研究：用 bootstrap 为现行 h=12 adjusted Portmanteau 构造参照分布，并在每个 bootstrap 样本内重新执行平台的 BIC 滞后选择（selection-aware bootstrap）。沿用 v1.85 的 36 个 DGP 单元，共 252,000 次 Monte Carlo 重复，每次 199 个 bootstrap 样本；研究两种预注册方案（递归残差重抽样、递归 wild bootstrap）。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">负责人事先选定的检验目标是“被选模型是否充分”（selected-model adequacy）：固定真实滞后时的拒绝率，以及 BIC 选出的滞后不低于真实滞后时的拒绝率。两种方案都通过了预注册门：固定真实滞后 {bootstrapIid.gate_A_fixed_true_lag.cells_inside_strict_interval}/{bootstrapIid.gate_A_fixed_true_lag.cell_count} 个单元落在 3.5%–6.5%（残差重抽样 {pct(bootstrapIid.gate_A_fixed_true_lag.minimum_rate)}–{pct(bootstrapIid.gate_A_fixed_true_lag.maximum_rate)}，wild {pct(bootstrapWild.gate_A_fixed_true_lag.minimum_rate)}–{pct(bootstrapWild.gate_A_fixed_true_lag.maximum_rate)}）；被选模型充分的条件拒绝率 {bootstrapIid.gate_C_adequacy_conditional.cells_inside_strict_interval}/{bootstrapIid.gate_C_adequacy_conditional.support_cell_count} 个支持单元落在区间内。按预注册的平局规则选定残差重抽样方案。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">整个流程的拒绝率（selection-aware procedure rejection rate）为 {pct(bootstrapIid.full_procedure_D_report_only.minimum_rate)}–{pct(bootstrapIid.full_procedure_D_report_only.maximum_rate)}，只作报告，不称为检验 size：高值出现在真实滞后为 2、BIC 几乎总是选成 1 阶的设计中，被选模型确实欠拟合，拒绝反映的是模型不充分。限制：由于 BIC 在该设计下几乎不选 2 阶，真实 VAR(2) 过程下 selection-aware 的 size 仍未经检验。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">这项结果只来自合成数据。尚未对真实国家数据做评估（Phase B 未运行，需负责人批准）；生产残差诊断、BIC 滞后选择、国家就绪状态均未改变，正式 dynamic-response-ready 国家仍为 0，正式 IRF 仍不可发布。完整记录见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-selection-bootstrap/var_selection_bootstrap_research_conclusion.json`}>v1.86 研究结论记录</a>。</p>
    </Section>
    <Section id="var-lag-selection-characterization" label="VAR / v1.87 research" title="VAR Lag-Selection Finite-Sample Characterization">
      <p className="mt-4 max-w-4xl text-sm leading-7"><strong>研究状态，只作描述。</strong>v1.87 事前注册了一项合成数据研究，描述平台现行 BIC 滞后选择在有限样本下能否识别真实的第二阶滞后，共 {lagCharacterization.total_replications.toLocaleString("en-US")} 次模拟。新增维度是第二阶滞后信号强度 ψ（总体第二阶信息与 BIC 多一阶惩罚之比，ψ &gt; 1 时 BIC 渐近倾向选 2 阶）。真实滞后为 1 时，BIC 选对的比例为 {pct(lagCharacterization.true_lag_1_bic_exact_recovery_range_primary[0])}–{pct(lagCharacterization.true_lag_1_bic_exact_recovery_range_primary[1])}。真实滞后为 2 时，选对比例随信号强度变化：v1.85 原设计 {lagRange("p2_v185")}，ψ=0.25 为 {lagRange("p2_psi0.25")}，ψ=0.5 为 {lagRange("p2_psi0.50")}，ψ=1 为 {lagRange("p2_psi1.00")}，ψ=2 为 {lagRange("p2_psi2.00")}（跨样本长度、持续性与确定性项的范围）。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">没能选出真实滞后，与“选出的低阶模型是否仍是充分近似”是两回事：研究按设计层面的可检出性，把欠选区分为充分的低阶近似与不充分的低阶模型，并报告 v1.86 bootstrap 诊断在各类情形下的拒绝率。有 {lagCharacterization.infeasible_combinations} 个（信号强度, 持续性）组合在保持平稳的前提下无法达到，已如实登记。AIC 与 HQIC 只作对照，不据此推荐替换准则；BIC 仍是生产准则，残差诊断、国家就绪状态和正式 IRF 不可发布的状态均未改变，也未运行真实国家评估。完整记录见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-lag-characterization/var_lag_characterization_research_conclusion.json`}>v1.87 研究结论记录</a>。</p>
    </Section>
    <Section id="var-country-identifiability" label="VAR / v1.88 research" title="Country VAR Lag-Identifiability Audit">
      <p className="mt-4 max-w-4xl text-sm leading-7"><strong>研究证据，不是就绪状态。</strong>v1.88 在查看任何国家结果之前完成事前注册，然后经负责人批准，对五个正式可估计的国家 VAR 做了滞后可识别性审计（Phase A），并用 v1.86 的 selection-aware bootstrap 做了国家层面的诊断评估（Phase B，B={countryPhaseB.bootstrap_replications_B}）。审计完全复现生产流程（最大差异 {countryAudit.production_agreement.maximum_difference.toExponential(1)}）。</p>
      <div className="mt-4 max-w-4xl overflow-x-auto" tabIndex={0} role="region" aria-label="数据表（可横向滚动）"><table className="w-full text-left text-sm"><thead><tr className="text-[var(--muted)]"><th className="py-2 pr-4 font-semibold">国家</th><th className="py-2 pr-4 font-semibold">BIC 滞后</th><th className="py-2 pr-4 font-semibold">经验滞后可识别性指数（90% 区间）</th><th className="py-2 pr-4 font-semibold">渐近 Portmanteau p</th><th className="py-2 font-semibold">bootstrap p</th></tr></thead><tbody>{countryAudit.units.map((unit) => { const eli = unit.empirical_lag_identifiability_index; const boot = countryPhaseB.units.find((row) => row.unit_id === unit.unit_id); return <tr key={unit.unit_id} className="border-t border-[var(--line)]"><td className="py-2 pr-4">{countryNames[unit.country] ?? unit.country}</td><td className="py-2 pr-4">{unit.selected_bic_lag}</td><td className="py-2 pr-4">{eli.eli_bias_adjusted.toFixed(2)}（{eli.eli_90[0].toFixed(2)}–{eli.eli_90[1].toFixed(2)}）</td><td className="py-2 pr-4">{unit.by_lag[String(unit.selected_bic_lag) as keyof typeof unit.by_lag]?.portmanteau_h12.p_value.toFixed(4)}</td><td className="py-2">{boot?.bootstrap_p_value?.toFixed(4)}</td></tr>; })}</tbody></table></div>
      <p className="mt-3 max-w-4xl text-sm leading-7">经验滞后可识别性指数是描述性指标，不是 v1.87 的真实 ψ，也不是“真实滞后为 2”的概率，ψ=1 不作门槛。现行渐近 Portmanteau 对四个 2 阶模型给出接近 5% 的拒绝；经过 bootstrap 校准后，五个国家在 0.05 水平下均不拒绝。这些结果只是研究证据：v1.87 显示在中等第二阶信号区间 bootstrap 可能偏保守，且 v1.86 未检验真实 VAR(2) 下的 selection-aware size。国家就绪状态、生产残差诊断、BIC 与正式 IRF 不可发布的状态均未改变；若要改动生产诊断，需要另行事前注册和负责人决定。完整记录见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-country-identifiability/var_phase_b_bootstrap_results.json`}>v1.88 Phase B 结果</a>。</p>
    </Section>
    <Section id="var-country-matched-bootstrap" label="VAR / v1.89 research" title="Country-Matched Bootstrap Calibration">
      <p className="mt-4 max-w-4xl text-sm leading-7"><strong>研究结果：不支持生产采用。</strong>v1.89 事前注册了一项与平台国家环境匹配的合成校准（T=137、K=3、候选滞后 1–10，持续性、协方差与第二阶信号范围取自 v1.88 的合并区间，不针对单个国家调参），检验 v1.86 selection-aware bootstrap 的有限样本 size 与 power，并在每次重复中同时记录现行渐近诊断。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">真实滞后为 1 时，bootstrap 的 size 接近名义水平（{pct(matchedSize("p1")[0], 1)}–{pct(matchedSize("p1")[1], 1)}）。但在 v1.88 四个 2 阶国家所处的中等第二阶信号区间，bootstrap 明显保守：被选模型设定充分时的拒绝率在 ψ=0.75 为 {pct(matchedSize("p2_psi0.75")[0], 1)}–{pct(matchedSize("p2_psi0.75")[1], 1)}，ψ=1 为 {pct(matchedSize("p2_psi1.00")[0], 1)}–{pct(matchedSize("p2_psi1.00")[1], 1)}，ψ=1.25 为 {pct(matchedSize("p2_psi1.25")[0], 1)}–{pct(matchedSize("p2_psi1.25")[1], 1)}（名义 5%）。检验力也弱：对强度 0.3 的残差 AR(1) 相依，中位拒绝率仅 {pct(matchedPower("common_ar1", 0.3), 1)}；对季节性 AR(12) 相依为 {pct(matchedPower("seasonal_ar12", 0.3), 1)}。预注册结论为 C（明显保守且检验力弱），因此 v1.88 中 bootstrap 在该区间的不拒绝只是较弱的充分性证据。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">现行渐近诊断在仅含常数项时接近名义水平，但含月份虚拟变量时约为 21%，与 v1.85 一致。本版本不授权任何生产改动：BIC、生产残差诊断、国家就绪状态和正式 IRF 不可发布的状态均未改变。完整记录见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-country-matched-bootstrap/var_country_matched_bootstrap_research_conclusion.json`}>v1.89 研究结论记录</a>。</p>
    </Section>
    <Section id="var-residual-attribution" label="VAR / v1.90 research" title="VAR Residual Dependence Attribution">
      <p className="mt-4 max-w-4xl text-sm leading-7"><strong>研究结果，只作描述。</strong>v1.90 事前注册并经负责人批准，对五个正式可估计国家 VAR 在生产滞后下的残差相依结构做了归因：逐方程自相关、跨方程滞后相关，以及对生产 h=12 Portmanteau 统计量的精确分解（与变量排序无关），还包括季节性、方差稳定性，以及按预设时段（2020 年前、2020–2021、2022 年后）的集中度。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">剩余相依较弱且分散：统计量分布在多个滞后上（前三个滞后合计只占 {pct(Math.min(...attributionTop3), 0)}–{pct(Math.max(...attributionTop3), 0)}），经多重检验校正后，没有任何单一方程或跨方程滞后分量显著。2020–2021 年只占约 18% 的观测，却占残差马氏距离总量的 {pct(Math.min(...pandemicMass), 0)}–{pct(Math.max(...pandemicMass), 0)}；HICP 在三个国家有约 0.2 的 12 阶残差自相关。三个仅作诊断用途的对照拟合（多一阶滞后、加入 12 阶滞后项、只用 2020 年前样本）最多只使统计量下降 {pct(maxProbeReduction, 0)}，都不构成新的设定或生产基线。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">跨方程份额的预注册标签规则低于白噪声基准 0.67，因此已在研究结论中以事后说明标注，标签本身保持不变。本版本不引入新诊断、不改变 BIC、生产残差诊断、国家就绪状态和正式 IRF 不可发布的状态。完整记录见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-residual-attribution/var_residual_attribution_research_conclusion.json`}>v1.90 研究结论记录</a>。</p>
    </Section>
    <Section id="var-publication-boundary" label="VAR / v2.0" title="VAR Dynamic-Response Publication Boundary">
      <p className="mt-4 max-w-4xl text-sm leading-7">五件事需要分开理解：<strong>估计器可用</strong>（简化式 VAR 与系数估计均已启用）；<strong>国家可估计</strong>（五个正式国家模型可估计）；<strong>是否存在设定错误的证据</strong>；<strong>诊断门是否经过验证</strong>；<strong>正式动态响应是否可发布</strong>。当前状态：残差发布门为“未解决：没有经过有限样本验证的诊断”，正式 dynamic-response-ready 国家为 {publicationBoundary.formal_dynamic_response_ready_country_count}，正式 IRF、IRF 不确定性与结构识别均不可发布。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">v1.85–v1.90 的研究表明：现行渐近 Portmanteau 在平台流程下未通过有限样本校准；BG 与 Edgerton–Shukur 不合格；研究过的 selection-aware bootstrap 在国家所处区间明显保守且检验力弱；残差归因只发现较弱、分散的相依。因此，历史上的渐近拒绝保留为诊断证据，但不能据此认定这些国家模型已被证明设定错误；bootstrap 的不拒绝也不能据此认定模型已通过。罗马尼亚、捷克与匈牙利另有 ADF 平稳性 borderline 的独立阻碍。</p>
      <p className="mt-3 max-w-4xl text-sm leading-7">系数估计器本身没有失败。目前没有获准的替代诊断或模型扩展；这一研究项目在 v2.0 后冻结，只有出现新的方法证据或另行事前注册的研究问题时才会重新开启。机器可读记录见 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-publication-boundary/var_dynamic_response_publication_boundary.json`}>发布边界登记</a> 与 <a className="text-[var(--accent)] underline" href={`${basePath}/research-data/var-publication-boundary/var_diagnostic_research_program_closure.json`}>研究项目结案记录</a>。</p>
    </Section>
    <Section id="events" label="03 / Events" title="事件编码"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">Source → Event → Coding → Affected Indicator / Project → Research context。date、actor、event_type、direction 和 confidence 用于检索与解释；它们不自动构成因果关系，也不直接改变模型分数。未完整编码、低置信度或结构样例保持 enters_model=false。</p><Link href="/news" className="mt-4 inline-flex text-sm font-semibold text-[var(--accent)]">进入 Event Library</Link></Section>

    <Section id="high-frequency" label="03b / High-Frequency & Events" title="高频数据与事件窗口分析"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">高频层使用 Eurostat 月度序列（HICP 指数与年通胀率分列、统一失业率季调、工业生产指数季调日历调整），自 2015-01 起；缺口保持 missing，绝不插值。序列记录 seasonal adjustment、index reference、definition version、value semantics 与 revision 状态（latest revised）。v1.31 起 HICP 正式迁移到合并数据集 prc_hicp_minr（ECOICOP ver.2，全项代码 TOTAL）：月度指数固定使用 2015=100 参考基（该 unit 仍由 prc_hicp_minr 正式提供，不与 2025=100 拼接），旧表 prc_hicp_midx / prc_hicp_manr 已退役；迁移前后 2024-01 至 2025-12 重叠窗口一致性已逐国验证并记录在 hicp_migration_manifest.json，全项序列跨分类过渡保持连续（all-items continuity verified）。月度失业率（une_rt_m）为 15–74 岁活跃人口百分比的协调估计：各国月度构建方法可以不同，不是完全同质的原始调查月度值。工业生产指数（sts_inpr_m）为 B–D 合计、季调日历调整，index reference 逐条记录以避免参考基更新造成静默断点。覆盖检查使用起始月到最新可得月之间的完整月序列，API 未返回的月份同样计为缺失；每个序列记录 latest_available_period、expected_latest_period 与 publication lag 状态，区分正常发布滞后与异常停滞。</p><p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--muted)]">事件窗口分析（Event Window Analysis）是描述性第一级分析：严格区分事件前（relative_month &lt; 0）、事件期（relative_month = 0，单独报告）与事件后（relative_month &gt; 0），事件月不进入事件后均值与事件后观测计数；完整窗口要求至少 12 个事件前与 6 个真正的事件后月度观测。变化语义由数据定义驱动：比率类序列（失业率、HICP 年通胀率）只报告百分点变化，指数类序列报告指数点变化并附相对百分比变化；图表在缺失月份断线，不做视觉插值。窗口内存在其他已核验事件时给出同期事件提示。它不自动识别因果关系——观察到的变化不能归因于单一事件。Formal Event Study 保持 registry_only。</p></Section>

    <Section id="macro-drivers" label="03c / Macro Drivers & Identification" title="宏观驱动与冲击识别边界">
      <p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">v1.51 将 macro_driver_observations 与 high_frequency_observations 逻辑关联、概念分离。政策利率来自 BIS，长期政府债券收益率与 HICP Energy 来自 Eurostat，汇率与有效汇率来自 BIS，Brent 与欧洲天然气月价来自 World Bank Pink Sheet。每条记录保留频率、时间、单位、转换、来源、定义版本、修订状态、月度聚合方式、经济角色与识别状态；缺失值不插值。</p>
      <p className="mt-2 max-w-4xl text-xs leading-6 text-[var(--muted)]" data-translation-notice="bis">{BIS_TRANSLATION_NOTICE_ZH}</p>
      <div className="mt-5 grid gap-4 md:grid-cols-2">
        <div className="border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">数据定义</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Policy rate ≠ market rate；bond yield ≠ policy rate；bilateral FX ≠ effective FX；HICP Energy ≠ wholesale energy price。非欧元区双边汇率统一为每 1 欧元对应的本币单位，上升表示本币贬值；欧元区只登记共同 EUR/USD 外部变量，不伪造国家专属汇率。政策利率使用月末值，债券收益率、BIS 汇率与商品价格按来源登记月均值。</p></div>
        <div className="border-l-2 border-[var(--line)] pl-5"><h3 className="font-semibold">识别状态</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Observed driver ≠ identified shock。Policy-rate change ≠ monetary-policy shock；energy-price movement ≠ energy-supply shock；exchange-rate movement ≠ external shock。只有外部工具、高频意外、叙事识别或充分的时间/符号设计通过登记和验证后，序列才可以标记 identified_shock。当前 identified_shock 数量为 0。</p></div>
      </div>
      <div className="mt-5 grid gap-4 md:grid-cols-3">
        <div className="border-l-2 border-[var(--line)] pl-5"><h3 className="font-semibold">时间对齐与预热</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">月度变化只使用严格相邻日历月，12 个月变化只使用恰好相隔 12 个月的原值。首月或前 12 个月属于 transformation warm-up，不计作 source missing；源缺口、预热、制度切换和定义切换分别登记，所有不可计算值保留 availability_reason。</p></div>
        <div className="border-l-2 border-[var(--line)] pl-5"><h3 className="font-semibold">政策制度切换</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">政策利率水平、可比政策利率变化和政策制度切换是三种不同记录。只有月份连续、policy_regime_id、policy_instrument_id 与 source series instance 均一致时才计算月度基点变化。克罗地亚 2023-01 的本国制度至 ECB 制度切换被明确阻断。</p></div>
        <div className="border-l-2 border-[var(--line)] pl-5"><h3 className="font-semibold">共同序列与适用范围</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">ECB 政策利率、EUR/USD、Brent 与欧洲天然气保留共同 series_instance_id 和逐国适用期。共同序列可生成兼容前台的国家解析视图，但不得在 panel、stacked LP 或跨国冲击分析中当作多个统计独立冲击。</p></div>
      </div>
      <p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">SVAR 继续 registry_only。v1.7 的 LP readiness 只允许冻结的两个 JK identified_shock，并使用时间对齐且未被制度或定义闸门排除的观测；只要识别、适用范围、结果定义、样本、估计器或推断任一门禁未通过，causal_lp_ready 就必须为 false。Brent、天然气、政策利率或普通汇率变动仍不是已识别冲击。事件的 related_driver_ids 只表示研究相关性，不表示事件造成了驱动变化；事件窗口仍是描述性分析。</p>
      <div className="mt-5 border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">High-Frequency Monetary Policy Identification / v1.6</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">v1.6 已从 ECB 官方附件获取 EA-MPD 与 EA-EMPD，记录原始文件大小、SHA-256、工作表结构和官方来源。原始 Excel 仅用于本地审计，不进入公开 ZIP；公开包只含派生机器可读记录、校验和与官方链接。EA-MPD 作为正式会议基线，EA-EMPD 保留讲话事件和扩展稳健性。同一政策会议的 decision、press conference 与 combined window 共享 parent_event_id；跨数据库相同会议通过 overlap registry 去重，不会被计作两次冲击。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">所有时间保留 Frankfurt 本地时点、CET/CEST 和 UTC 转换，不能全年固定使用 UTC+1。月度预注册采用 monthly_sum_of_event_surprises，并分为 official_decisions_only、speeches_only 与 all_policy_events：无合格事件的月份记为 0 和 valid_no_event；只有预期事件存在而登记度量缺失时才记 missing。讲话不会静默并入正式决策序列。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Official ECB dataset ≠ automatic causal identification；intraday rate change ≠ pure monetary-policy shock；policy surprise ≠ policy-rate change；speech surprise ≠ scheduled decision surprise。当前工作簿直接提供 OIS 等窗口变化，但没有为本平台的规范序列单独分离政策立场与 central-bank information effect。Target、Timing、Forward Guidance 与 QE 在方法论文献中有定义，但当前附件没有可直接复用的正式因子列，因此平台没有静默重建。现有月度 OIS 序列最多登记为 external_innovation_proxy，identified_shock_count = 0。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">奥地利、德国、斯洛伐克和斯洛文尼亚按共同欧元区政策创新代理解释；克罗地亚在 2023-01 前为外部 ECB 溢出、之后为共同欧元区暴露；捷克、匈牙利、波兰、罗马尼亚和塞尔维亚只能表述为 external ECB spillover，不能称为本国货币政策冲击。信息效应、独立复现和冲击识别未通过前，causal_lp_ready 必须为 false，Local Projections 保持 registry_only。</p></div>
      <p className="mt-3 max-w-4xl text-xs leading-6 text-[var(--muted)]" data-source-attribution="ea-mpd ea-empd">来源与许可：{SOURCE_ATTRIBUTIONS.filter((entry) => entry.id === "ea-mpd" || entry.id === "ea-empd").map((entry) => entry.zh).join("。")}。</p>
      <div className="mt-5 border-l-2 border-[var(--warning)] pl-5"><h3 className="font-semibold">Central-Bank Information Effects / Jarociński–Karadi / v1.62 frozen</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">作者维护仓库的确定性 shock-construction 使用 Monetary Event Window 的 OIS_1M、OIS_3M、OIS_6M、OIS_1Y 构造不居中的 PC1，并与 STOXX50 通过正对角 QR 的中位旋转分解。纯货币紧缩要求利率上升、股票下降；央行信息冲击要求利率与股票同向。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">v1.62 在固定作者提交上逐事件与逐月复刻通过，信息效应标记为 separated_under_jk_framework。Median rotation 是符号限制集合中的代表性旋转，不是唯一结构真值；poor-man 版本更严格，只用于稳健性诊断。v1.7 不改动冲击构造、ID、符号或截至 2025-10 的月度样本。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Shock construction 与原论文的 Bayesian VAR macro-transmission model 分开登记。只有两个冻结并验证的 JK 序列进入正式 LP；SVAR 与 Bayesian VAR 仍为 registry_only。</p></div>
      <div id="local-projections" className="scroll-mt-24 mt-5 border-l-2 border-[var(--accent)] pl-5"><h3 className="font-semibold">Lag-Augmented Local Projections / v1.71</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">正式估计单元是 country × outcome × regime，MP_t 与 CBI_t 同时进入每个 horizon 回归，不运行 panel、pooled 或 state-dependent LP。HICP 与工业生产使用相对 t−1 的累计对数百分比；失业率、长期收益率与国内政策利率使用水平百分点变化；非欧元国家本币/欧元汇率上升表示本币贬值。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">所有 horizon 使用同一 common-horizon sample，完整修剪后 N≥96。基础 VAR 阶数 p 由 AIC 在 1…6 中只选择一次；非增强 LP 使用 p−1 个滞后块，lag-augmented LP 实际使用 p 个滞后块。因此 augmentation 是相对非增强规格增加 1 阶，但生产回归绝不使用 p+1 个滞后。该元数据迁移未改变任何 baseline coefficient 或 standard error。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">单 horizon 推断继续使用 90%/95% pointwise EHW-HC1 区间。95% simultaneous confidence band 使用跨 horizon 联合 HC1 covariance、相关矩阵特征分解与多元正态模拟得到 plug-in sup-t 临界值，用于整条显示路径的联合覆盖。Pointwise CI 不等于 simultaneous band；一个点态区间不含 0 不等于整条 response path 显著。Inoue–Jordà–Kuersteiner significance band 仍为 registry_only，不能与参数置信带混用。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">固定 p=2、固定 p=6 与预定控制变量仅是 sensitivity。控制变量只使用 Brent、欧洲天然气及适用非欧元国家政策利率的滞后，不加入当期传导渠道；比较使用 common sample，不按结果挑选替代 baseline。Shock concentration、leverage、standardized residual、DFBETAs 与 leave-largest-shock-month 均为诊断，不自动删除观测。</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">跨国并排图仅为描述性比较：视觉差异不等于统计异质性。共享 ECB shock 不是独立跨国冲击重复；本版不做 euro/non-euro pooled effect 或正式 country-difference test。CBI 的 0.25 只是数值归一化，不能称为“25bp tightening”。</p></div>
      <div className="mt-5 flex flex-wrap gap-3"><a href={`${basePath}/research-data/macro_driver_dictionary.json`} className="text-sm font-semibold text-[var(--accent)]">Macro driver dictionary</a><a href={`${basePath}/research-data/driver_applicability_registry.json`} className="text-sm font-semibold text-[var(--accent)]">Driver applicability</a><a href={`${basePath}/research-data/shock_identification_registry.json`} className="text-sm font-semibold text-[var(--accent)]">Shock identification registry</a><a href={`${basePath}/research-data/identified_shock_source_candidates.json`} className="text-sm font-semibold text-[var(--accent)]">Identification source candidates</a><a href={`${basePath}/research-data/ecb_event_dataset_overlap_registry.json`} className="text-sm font-semibold text-[var(--accent)]">ECB overlap registry</a><a href={`${basePath}/research-data/ecb_monetary_policy_monthly_series.json`} className="text-sm font-semibold text-[var(--accent)]">Monthly proxy series</a><a href={`${basePath}/research-data/shock_applicability_registry.json`} className="text-sm font-semibold text-[var(--accent)]">Shock applicability</a><a href={`${basePath}/research-data/lp_readiness_registry.json`} className="text-sm font-semibold text-[var(--accent)]">LP readiness registry</a></div>
    </Section>

    <Section id="finite-sample" label="LP / v1.72" title="有限样本与冲击支持">
      <p className="mt-4 text-sm leading-7 text-[var(--muted)]">渐近推断稳健性与有限样本点估计偏差是不同问题。Montiel Olea–Plagborg-Møller 的 lag-augmented LP 推断结果，不意味着约 100–115 个月的样本必然无偏；Herbst–Johannsen 的有限样本分析也不是对渐近理论的否定。正式 AIC p=1…6、实际 p 个 lag blocks、共同样本、HC1 和 5,000 draws sup-t 均保持冻结，不按诊断结果改选 BIC 或替代 baseline。</p>
      <p className="mt-3 text-sm leading-7 text-[var(--muted)]">Fed 的 feds2020010r.zip 是无障碍 HTML/GIF 材料，不包含可执行复现代码。参考论文的条件矩、最优预测控制、标量冲击及样本修剪，与当前相关双冲击、月度虚拟变量和直接累计回归尚无经过验证的映射。偏差修正保留 registry_only；不得把部分审计称作完整复现，不提供未经验证的修正后标准误。</p>
      <p className="mt-3 text-sm leading-7 text-[var(--muted)]">effective_shock_support_count = 1 / Σw²，其中 w 为冲击平方占比。这只是集中度支持计数，不是渐近推断的有效样本量；月份和事件分别采用各自的平方和分母，月度聚合含交叉项，二者不可混为一谈。不设置任意集中度等级或稳健性分数。</p>
      <p className="mt-3 text-sm leading-7 text-[var(--muted)]">逐月诊断删除非零冲击月份的回归观测，但不抹掉后续滞后项中的已发生冲击。逐事件诊断则从冻结的月度 MP/CBI 中减去该事件贡献，并传播到所有受影响的滞后项，不重新估计 JK 旋转，也不修改正式冲击文件。两类诊断不是同一种删除。DFBETAS 的 2/√N 与 1、leverage 的 2k/N 与 3k/N、内部学生化残差的 2 与 3 都是提示性阈值，不自动删除观测。</p>
      <p className="mt-3 text-sm leading-7 text-[var(--muted)]">有限样本模拟覆盖 N=96/108/114、p=1/2/4/6、H=6/12/18/24、ρ=0.2/0.6/0.9/0.99，以及稠密和经验校准稀疏双冲击。8 个关键设计各 10,000 次重复和每次 5,000 sup-t draws；其余 378 个探索性设计各 200 次重复和每次 256 draws。它们是固定 p 的水平差分 DGP，不覆盖 AIC 选择随机性、所有对数变换或所有外部控制规格，更不能据此校准真实系数。</p>
      <p className="mt-3 text-sm leading-7 text-[var(--muted)]">全部 44 个模型进行联合协方差跨语言核对。相关矩阵最小特征值低于 −1e−8 时阻断诊断；微小负值的数量与裁剪幅度显式记录。sup-t 临界值是模拟估计值：检查同种子复现与五个独立种子的经验变动，而非把临界值视为精确常数。</p>
      <div className="mt-3 flex flex-wrap gap-4 text-sm text-[var(--accent)]"><a href="https://www.federalreserve.gov/econres/feds/bias-in-local-projections.htm">Fed：Bias in Local Projections</a><a href="https://www.nber.org/papers/w33871">LP/VAR Primer（NBER Volume 40 方法背景）</a><a href="https://economics.princeton.edu/working-papers/double-robustness-of-local-projections-and-some-unpleasant-varithmetic/">Double Robustness 与 LP/VAR 偏差—方差权衡</a></div>
    </Section>

    <Section id="spatial" label="04 / Spatial" title="空间与边界"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">区域记录通过 region_id、行政层级、边界版本、来源、许可和年份关联。国家值不下推到区域，NUTS2 与 NUTS3 不混用。真实边界只有在来源、许可、坐标系、几何、拓扑和主键检查通过后才开放；地图不提供风险、预测、情景影响或真实党派支持率图层。</p></Section>

    <Section id="validation" label="05 / Validation" title="质量检查与已知限制"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">验证覆盖确定性、权重、标准化边界、缺失值、年份对齐、情景零冲击、参数界限和复现。Expected unavailable 表示准入闸门按规则阻止输出，不是错误。</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]"><strong>Validation ≠ scientific proof.</strong> 当前只声称 <strong>Historical reconstruction readiness</strong> 与方向性验证；没有 point-in-time vintage data 时，不报告预测准确率。事件关联不等于因果，项目库不等于项目普查，confidence 不等于发生概率。</p><div className="mt-5 flex flex-wrap gap-3"><a href={`${basePath}/research-data/validation_registry.json`} className="text-sm font-semibold text-[var(--accent)]">Validation registry</a><a href={`${basePath}/research-data/golden_test_cases.json`} className="text-sm font-semibold text-[var(--accent)]">Golden tests</a></div></Section>

    <Section id="citation" label="06 / Citation" title="引用与下载"><p className="mt-4 max-w-4xl text-sm leading-7 text-[var(--muted)]">引用应包含平台版本、访问日期和稳定 URL。具体 observation、事件、项目、模型或情景应同时引用其记录标识和原始来源；平台不会伪造 DOI。</p><div className="mt-5"><CitationActions plainText={platformCitation()} apaText={platformApaCitation()} bibtexText={platformBibtexCitation()} label="复制平台引用" /></div><div className="mt-5 flex flex-wrap gap-3"><a href={`${basePath}/research-data/${getResearchPackageFilename()}`} className="rounded-lg cta-dark px-4 py-2 text-sm font-semibold">下载完整研究数据包（ZIP）</a><a href={`${basePath}/research-data/release_manifest.json`} className="rounded-lg border border-[var(--line)] px-4 py-2 text-sm font-semibold">Release manifest</a></div></Section>
  </main>;
}
