import type { WeeklyNewsItem } from "../newsData";

type Row = [id:string, countrySlug:string, countryZh:string, date:string, title:string, topic:WeeklyNewsItem["topic"], summary:string, sourceLabel:string, sourceUrl:string, language:string, sourceStatus:"official"|"manual", eventType:WeeklyNewsItem["eventType"]];

const rows: Row[] = [
  ["hu-2026-08-20-magyar-reacts-lazar-resignation","hungary","匈牙利","2026-08-20","马扎尔·彼得回应拉扎尔·亚诺什辞职","政治","马扎尔·彼得就拉扎尔·亚诺什辞职作出回应，相关表态发生在蒂萨党政府执政百日节点前后。\n\n该记录只呈现政治回应，不把辞职原因或后续党派影响作因果推断。","Index","https://index.hu/belfold/2026/08/20/magyar-peter-lazar-janos-lemondas-fidesz-tisza-part/","hu / zh","manual","election"],
  ["hu-2026-08-21-tisza-islands-oversight","hungary","匈牙利","2026-08-21","蒂萨基层组织讨论政府监督角色","政治","蒂萨基层组织成员表示，除社区建设外，也希望监督政府并反馈地方情况。\n\n报道基于活动参与者采访，不将个别受访者意见等同于全体支持者立场。","Index","https://index.hu/belfold/2026/08/21/tisza-sziget-agusztus-20-ellenorzes-a-kormany-100-napja-magyar-peter-ellenorzes-jovo-agusztus-20/","hu / zh","manual","election"],
  ["hu-2026-08-25-nvvh-fourth-candidate","hungary","匈牙利","2026-08-25","蒂萨党说明国家资产保护局增补候选人原因","政治","蒂萨党议会党团表示，为扩大竞争范围，建议在三名入围者之外听取第四名候选人的陈述。\n\n该事项属于机构负责人遴选程序，报道未显示最终任命已在当日完成。","Index","https://index.hu/belfold/2026/08/25/tisza-part-nemzeti-vagyonvisszaszerzesi-es-vagyonvedelmi-hivatal-elnokjelolt-palyazat-sarvari-nicholas/","hu / zh","manual","election"],
  ["hu-2026-08-27-nvvh-unger-nomination","hungary","匈牙利","2026-08-27","蒂萨党提名翁格尔·安娜领导国家资产保护局","政治","蒂萨党说明提名翁格尔·安娜担任国家资产保护与追回局负责人的理由。\n\n委员会程序仍需议会表决，报道同时记录副职遴选将另行推进。","Index","https://index.hu/belfold/2026/08/27/nemzeti-vagyonvedelmi-es-vagyonvisszaszerzesi-hivatal-nvvh-unger-anna-jeloles-hantosi-istvan-hallerne-nagy-aniko","hu / zh","manual","election"],
  ["hu-2026-08-29-tiszalok-hydropower-stop","hungary","匈牙利","2026-08-29","蒂萨洛克水电站因河流水位过低停运","能源","蒂萨河水位降至关键水平后，蒂萨洛克水电站停止运行。\n\n有关部门表示区域供电仍获保障，水电站的主要职能是水量调节，发电属于次要功能。","Index","https://index.hu/belfold/2026/08/29/tisza-alacsony-vizallas-tiszalok-vizeromu-energiaellatas-paks-atomeromu-szakacs-peter-lajos","hu / zh","manual","energy"],
  ["hu-2026-09-02-cabinet-forty-items","hungary","匈牙利","2026-09-02","匈牙利内阁会议审议四十项议题","政治","匈牙利政府召开内阁会议，议程涵盖环境政策及政府行政事项。\n\n本记录按会议议程处理，不把议程项目视为已经实施的政策。","Index","https://index.hu/belfold/2026/09/02/magyar-peter-tisza-part-kormanyules-kornyezetvedelem-antonio-costa-talalkozo/","hu / zh","manual","regional"],
  ["hu-2026-09-03-publicus-party-support","hungary","匈牙利","2026-09-03","Publicus调查显示蒂萨党支持率回落","政治","Publicus公布8月政党支持度调查，报道称蒂萨党支持率下降、欧尔班·维克托的支持有所上升。\n\n民调是特定样本与时间点的调查结果，不作为选举预测。","Index","https://index.hu/belfold/2026/09/03/publicus-intezet-kutatas-partok-tamogatottsaga-augusztus-felmeres/","hu / zh","manual","election"],
  ["hu-2026-08-26-public-consultation-ai","hungary","匈牙利","2026-08-26","蒂萨党公共咨询平台引发人工智能程序讨论","政治","蒂萨党推出公共咨询平台后，专家讨论人工智能参与汇总公众意见可能带来的程序问题。\n\n报道指出平台具体机制尚未公开，因此本记录不判断其结果代表性。","Index","https://index.hu/belfold/2026/08/26/ai-summit-nemzeti-konzultacio-mesterseges-intelligencia-kozhang-tarsadalmi-egyeztetes-aisummit2026/","hu / zh","manual","industrial_policy"],
  ["hu-2026-09-05-education-policy-criticism","hungary","匈牙利","2026-09-05","教育界人士批评蒂萨政府教育政策准备不足","政治","教育政策活动中有与会者批评政府在政策准备和执行方面存在不足，决策者也作出回应。\n\n批评内容作为明确归因的观点保存，不作为平台评价。","Index","https://index.hu/belfold/2026/09/05/oktataspolitika-pedagogusfesztival-tisza-kormany-kritika/","hu / zh","manual","regional"],

  ["pl-2026-08-21-ngos-court-candidate","poland","波兰","2026-08-21","波兰非政府组织要求宪法法院候选人退出","政治","多个非政府组织要求总理的前高级助手马切伊·贝雷克退出宪法法院法官遴选。\n\n组织方认为其政治联系可能影响法院去政治化，相关说法属于倡议方立场。","Notes from Poland","https://notesfrompoland.com/2026/08/21/polish-ngos-urge-pms-right-hand-man-to-withdraw-constitutional-court-candidacy/","en / zh","manual","election"],
  ["pl-2026-08-24-ukraine-pantheon-warning","poland","波兰","2026-08-24","波兰就乌克兰国家先贤祠纪念对象提出交涉","区域","乌克兰筹建国家先贤祠之际，波兰方面反对纪念被其认定与战时屠杀有关的人物。\n\n争议涉及两国历史记忆与外交关系，记录不裁定历史责任。","Notes from Poland","https://notesfrompoland.com/2026/08/24/ukraine-to-establish-new-national-pantheon-as-poland-warns-against-honouring-massacre-figures/","en / zh","manual","regional"],
  ["pl-2026-08-26-us-border-equipment","poland","波兰","2026-08-26","美国向波兰提供边境防护设备和培训","政治","美国向波兰边防部门提供价值210万美元的设备，包括45架无人机和9套热成像设备。\n\n该批援助属于面向波兰及波罗的海国家边境安全计划的一部分。","Notes from Poland","https://notesfrompoland.com/2026/08/26/us-provides-equipment-and-training-to-protect-polish-border-from-migratory-pressures/","en / zh","manual","regional"],
  ["pl-2026-08-28-draft-budget-2027","poland","波兰","2026-08-28","波兰公布2027年预算草案框架","经济","波兰政府公布2027年预算草案，预计财政赤字仍相当于国内生产总值的7.1%。\n\n草案仍须完成政府和议会程序，记录不将目标值视为最终执行结果。","Notes from Poland","https://notesfrompoland.com/2026/08/28/polish-government-sets-out-draft-2027-budget-with-deficit-remaining-at-7-1-of-gdp/","en / zh","manual","fiscal"],
  ["pl-2026-08-28-krakow-fireworks-ban","poland","波兰","2026-08-28","克拉科夫在法院裁决后撤回烟花禁令","政治","克拉科夫在法院作出不利裁决后撤回地方烟花禁令。\n\n事件反映地方公共管理措施受到司法审查，不推广为全国性禁令变化。","Notes from Poland","https://notesfrompoland.com/2026/08/28/krakow-withdraws-fireworks-ban-after-negative-court-ruling/","en / zh","manual","regional"],
  ["pl-2026-09-01-domestic-defence-production","poland","波兰","2026-09-01","波兰扩大本土国防生产能力","政治","波兰在扩军背景下调整采购与产业政策，提高国内国防企业在装备供应中的作用。\n\n报道聚焦产业能力建设，不把规划产能视为已交付装备。","Reuters","https://www.reuters.com/business/aerospace-defense/poland-pivots-home-grown-defence-production-it-builds-europes-biggest-army-2026-09-01/","en / zh","manual","industrial_policy"],
  ["pl-2026-09-02-drone-plant-arson","poland","波兰","2026-09-02","图斯克称无人机工厂火灾为蓄意纵火","政治","唐纳德·图斯克称斯卡日斯科-卡缅纳无人机企业火灾为蓄意破坏，并表示可能受俄罗斯指使。\n\n俄罗斯关联属于总理及调查机关当时的判断，案件仍由检察和安全机构调查。","Notes from Poland","https://notesfrompoland.com/2026/09/02/polish-drone-plant-fire-undoubtedly-arson-and-likely-ordered-by-russia-says-tusk/","en / zh","manual","regional"],
  ["pl-2026-09-03-russian-ambassador-summoned","poland","波兰","2026-09-03","波兰召见俄罗斯大使声援德国","区域","波兰外交部门召见俄罗斯大使，以表达对德国处理安全事件的声援。\n\n本记录关联德国但只保留一个以波兰为主的canonical记录。","Notes from Poland","https://notesfrompoland.com/2026/09/03/poland-summons-russian-ambassador-in-show-of-solidarity-with-germany/","en / zh","manual","regional"],
  ["pl-2026-09-03-short-term-rental-bans","poland","波兰","2026-09-03","波兰拟允许地方政府限制短期出租","政治","政府推进法规调整，拟授权地方社区限制短期住房出租。\n\n措施仍处程序阶段，地方是否采用禁令将取决于后续立法和本地决定。","Notes from Poland","https://notesfrompoland.com/2026/09/03/poland-moves-to-allow-local-communities-to-ban-short-term-rentals/","en / zh","manual","regional"],
  ["pl-2026-09-03-presidential-business-delegations","poland","波兰","2026-09-03","波兰为企业提供参加总统外访代表团机会","经济","波兰方面向企业开放总统外访商务代表团席位，以配合对外经济活动。\n\n该安排是参与机制，不等于企业获得合同或投资成果。","Notes from Poland","https://notesfrompoland.com/2026/09/03/poland-offers-businesses-seats-on-presidential-plane-for-foreign-visits/","en / zh","manual","FDI"],
  ["pl-2026-09-04-sewage-water-power-plants","poland","波兰","2026-09-04","波兰电厂将试用再生污水作为冷却水","能源","波兰推进以处理后的污水替代部分常规水源用于电厂冷却。\n\n该措施旨在缓解水资源约束，具体覆盖范围仍以项目实施为准。","Notes from Poland","https://notesfrompoland.com/2026/09/04/poland-to-begin-using-sewage-water-to-cool-power-plants/","en / zh","manual","energy"],
  ["pl-2026-09-04-berek-constitutional-court","poland","波兰","2026-09-04","波兰众议院选举马切伊·贝雷克为宪法法院法官","政治","波兰众议院以226票支持选举马切伊·贝雷克为宪法法院法官。\n\n总统此前反对该人选，后续宣誓和实际履职仍存在程序争议。","Notes from Poland","https://notesfrompoland.com/2026/09/04/prime-ministers-right-hand-man-elected-as-polish-constitutional-court-judge/","en / zh","manual","election"],

  ["cz-2026-08-29-military-crisis-system","czechia","捷克","2026-08-29","捷克军方开发危机信息系统","政治","捷克军方推进新的危机信息系统建设，用于安全事件中的信息协调。\n\n本记录只确认开发工作，不推定系统已经全面部署。","Radio Prague International","https://english.radio.cz/czech-military-developing-new-crisis-information-system-8895969","en / zh","manual","industrial_policy"],
  ["cz-2026-08-30-q2-wages","czechia","捷克","2026-08-30","捷克二季度工资继续较快增长","经济","捷克二季度工资数据继续显示较强名义增长。\n\n该新闻记录不替代项目中的统一宏观观测口径。","Radio Prague International","https://english.radio.cz/czech-wage-growth-remained-strong-second-quarter-8895982","en / zh","manual","macro"],
  ["cz-2026-08-31-draft-budget","czechia","捷克","2026-08-31","捷克政府讨论2027年国家预算草案","经济","捷克政府审议下一年度国家预算草案，财政收支安排仍需完成内阁和议会程序。\n\n记录按草案阶段处理，不把计划赤字视为执行值。","Radio Prague International","https://english.radio.cz/government-discuss-draft-state-budget-next-year-8896020","en / zh","manual","fiscal"],
  ["cz-2026-08-31-budget-deficit","czechia","捷克","2026-08-31","捷克政府提出历史第二高预算赤字方案","经济","政府提出2027年预算赤字方案，规模为捷克历史上第二高。\n\n该条与预算审议新闻信息互补，聚焦赤字规模而非重复会议进程。","Radio Prague International","https://english.radio.cz/czech-government-plans-second-highest-budget-deficit-history-8896048","en / zh","manual","fiscal"],
  ["cz-2026-09-01-unemployment-benefits","czechia","捷克","2026-09-01","捷克政府批准下调失业救济安排","政治","捷克政府批准调整失业救济政策，降低部分待遇。\n\n具体生效时间和适用对象以正式法规文本为准。","Radio Prague International","https://english.radio.cz/government-approves-reduction-unemployment-benefits-8896202","en / zh","manual","fiscal"],
  ["cz-2026-09-02-russian-ambassador","czechia","捷克","2026-09-02","捷克外长就莱比锡无人机事件召见俄罗斯大使","区域","捷克外交部门就德国莱比锡无人机袭击事件召见俄罗斯大使。\n\n该跨境安全新闻以捷克外交行动为主记录，不复制为德国新闻。","Radio Prague International","https://english.radio.cz/macinka-summoning-russian-ambassador-over-drone-attack-leipzig-8896242","en / zh","manual","regional"],

  ["si-2026-08-20-emergency-medical-rrf","slovenia","斯洛文尼亚","2026-08-20","斯洛文尼亚以复苏基金改善急救可及性","欧盟","斯洛文尼亚政府介绍复苏与韧性资金支持紧急医疗可及性的项目进展。\n\n记录资金用途与实施目标，不推定项目效果已经实现。","GOV.SI","https://www.gov.si/en/news/2026-08-20-european-recovery-and-resilience-funds-together-towards-the-goal-more-accessible-emergency-medical-assistance/","en / zh","official","EU_funds"],
  ["si-2026-08-24-maribor-research-eu-funds","slovenia","斯洛文尼亚","2026-08-24","欧盟拨款逾1700万欧元提升马里博尔大学研究能力","欧盟","斯洛文尼亚宣布逾1700万欧元欧盟资金用于提升马里博尔大学研究能力。\n\n资金用途按政府公告保存，不对未来科研产出作预测。","GOV.SI","https://www.gov.si/en/news/2026-08-24-over-17-million-in-eu-funding-to-strengthen-the-research-capacity-of-university-of-maribor/","en / zh","official","EU_funds"],
  ["si-2026-08-24-coalition-willing-summit","slovenia","斯洛文尼亚","2026-08-24","亚内兹·扬沙参加“志愿联盟”峰会","区域","斯洛文尼亚总理亚内兹·扬沙参加有关乌克兰与欧洲安全的“志愿联盟”峰会。\n\n本条记录外交参与，不将会议表态视为新的军事承诺。","GOV.SI","https://www.gov.si/en/news/2026-08-24-prime-minister-janez-jansa-attends-the-coalition-of-the-willing-summit/","en / zh","official","regional"],
  ["si-2026-08-26-migration-security","slovenia","斯洛文尼亚","2026-08-26","斯洛文尼亚与塞尔维亚讨论移民和有组织犯罪","区域","两国内政部门讨论移民管理、安全合作及打击有组织犯罪。\n\n这是跨境合作记录，以斯洛文尼亚政府公告作为canonical来源。","GOV.SI","https://www.gov.si/en/news/2026-08-26-ministers-matoz-and-dacic-discuss-migration-security-and-the-fight-against-organised-crime-208160/","en / zh","official","regional"],
  ["si-2026-08-27-eu-human-rights-envoy","slovenia","斯洛文尼亚","2026-08-27","斯洛文尼亚政府提出欧盟人权特别代表人选","欧盟","斯洛文尼亚政府通过向欧盟提出人权特别代表人选的建议。\n\n该决定属于提名程序，不等于欧盟已完成任命。","GOV.SI","https://www.gov.si/en/news/2026-08-27-government-proposal-for-the-nomination-of-a-european-union-special-representative-for-human-rights/","en / zh","official","regional"],
  ["si-2026-08-27-government-session-eight","slovenia","斯洛文尼亚","2026-08-27","斯洛文尼亚政府举行第八次例会","政治","政府第八次例会审议行政、社会和经济政策事项。\n\n各项措施以公告所载程序状态为准，不把审议等同于生效。","GOV.SI","https://www.gov.si/en/news/2026-08-27-8th-regular-session-of-the-government-of-the-republic-of-slovenia/","en / zh","official","regional"],
  ["si-2026-08-31-bled-bilateral-meetings","slovenia","斯洛文尼亚","2026-08-31","亚内兹·扬沙在布莱德战略论坛举行多场双边会谈","区域","斯洛文尼亚总理在布莱德战略论坛期间与多国官员举行双边会谈，讨论欧洲安全和合作。\n\n会议交流不自动登记为协议或项目。","GOV.SI","https://www.gov.si/en/news/2026-08-31-prime-minister-janez-jansa-holds-a-number-of-bilateral-meetings-on-the-sidelines-of-the-bled-strategic-forum/","en / zh","official","regional"],
  ["si-2026-08-31-flood-safety-rrf","slovenia","斯洛文尼亚","2026-08-31","斯洛文尼亚以复苏基金推进防洪安全","欧盟","政府介绍复苏与韧性资金支持防洪基础设施和风险降低项目。\n\n项目成果仍需按实施进度评估。","GOV.SI","https://www.gov.si/en/news/2026-08-31-european-recovery-and-resilience-funds-together-towards-the-goal-better-flood-safety/","en / zh","official","EU_funds"],
  ["si-2026-09-01-bled-security","slovenia","斯洛文尼亚","2026-09-01","斯洛文尼亚外长在布莱德论坛强调安全与稳定","区域","外长托内·凯泽尔在布莱德战略论坛闭幕时讨论欧洲安全、稳定与繁荣。\n\n相关判断明确归因于部长，不作为平台自身评价。","GOV.SI","https://www.gov.si/en/news/2026-09-01-minister-kajzer-at-the-close-of-the-bled-strategic-forum-without-security-there-can-be-no-stability-or-prosperity/","en / zh","official","regional"],
  ["si-2026-09-02-economy-environment","slovenia","斯洛文尼亚","2026-09-02","亚内兹·扬沙承诺改善企业发展环境","经济","总理在手工业和小企业论坛表示，政府将重视经济并提供稳定发展环境。\n\n承诺属于政府政策表态，不作为增长预测。","GOV.SI","https://www.gov.si/en/news/2026-09-02-prime-minister-janez-jansa-the-government-takes-the-economy-seriously-and-is-committed-to-creating-a-stable-environment-for-development/","en / zh","official","industrial_policy"],
  ["si-2026-09-03-energy-excise","slovenia","斯洛文尼亚","2026-09-03","斯洛文尼亚政府提出能源消费税修法","能源","政府第九次例会批准消费税法修正建议，以缓解高能源价格对家庭和企业的影响。\n\n会议同时讨论更平衡和更具韧性的能源政策，法案仍需后续程序。","GOV.SI","https://www.gov.si/en/news/2026-09-03-9th-regular-session-of-the-government-of-the-republic-of-slovenia/","en / zh","official","energy"],
  ["si-2026-09-04-eu-budget-costa","slovenia","斯洛文尼亚","2026-09-04","斯洛文尼亚与欧洲理事会主席讨论欧盟长期预算","欧盟","亚内兹·扬沙会见欧洲理事会主席安东尼奥·科斯塔，重点讨论欧盟下一期多年财政框架。\n\n斯方主张预算应更平衡并回应共同挑战，该主张按政府立场归因。","GOV.SI","https://www.gov.si/en/news/2026-09-04-slovenia-calls-for-a-balanced-european-budget-that-will-address-common-challenges/","en / zh","official","EU_funds"],

  ["hr-2026-08-21-gospic-waste-parliament","croatia","克罗地亚","2026-08-21","克罗地亚议会通过戈斯皮奇危险废物处理结论","政治","克罗地亚议会结束危险废物特别会议，通过执政多数提出的处理结论，并要求政府90天内报告清理进展。\n\n总统和反对派提出的其他结论未获通过。","HRT","https://glashrvatske.hrt.hr/en/politics/sabor-rejects-president-s-conclusions-on-gospic-waste-crisis-12871251","en / zh","manual","regional"],
  ["hr-2026-08-28-q2-gdp","croatia","克罗地亚","2026-08-28","克罗地亚二季度GDP增长放缓至1.7%","经济","克罗地亚经济连续第22个季度增长，但二季度同比增速放缓至1.7%。\n\n该增速为疫情以来最低，记录不对后续季度作预测。","HRT","https://glashrvatske.hrt.hr/hr/multimedia/tjedna-kronika/tjedna-kronika-28082026--12880816","hr / zh","manual","macro"],
  ["hr-2026-09-01-omis-disaster","croatia","克罗地亚","2026-09-01","奥米什火灾地区宣布自然灾害状态","政治","斯普利特-达尔马提亚县在奥米什火灾后宣布自然灾害状态。\n\n该行政决定为后续损失评估和救助提供程序基础。","HRT","https://glashrvatske.hrt.hr/en/multimedia/croatia-today/croatia-today-01-09-2026-12886845","en / zh","manual","regional"],
  ["hr-2026-09-01-august-inflation","croatia","克罗地亚","2026-09-01","克罗地亚8月通胀率升至4.1%","经济","克罗地亚统计局初步估计8月CPI同比上涨4.1%、环比上涨0.3%，能源价格同比上涨17.4%。\n\n协调口径HICP同比为3.7%，与国家CPI分开记录。","HRT","https://glashrvatske.hrt.hr/en/economy/inflation-at-41-energy-prices-rose-the-most-coric-ever-closer-to-the-european-average-12886882","en / zh","manual","macro"],
  ["hr-2026-09-01-plenkovic-mostar","croatia","克罗地亚","2026-09-01","安德烈·普连科维奇访问莫斯塔尔并讨论选举法","区域","克罗地亚总理安德烈·普连科维奇访问莫斯塔尔，重申支持修改波黑选举法。\n\n访问期间签署600份面向波黑克族项目的资助合同，金额2575万欧元。","HRT","https://glashrvatske.hrt.hr/en/foreign/plenkovic-expects-the-outvoting-of-croats-in-bih-will-not-be-repeated-in-elections-12886878","en / zh","manual","regional"],
  ["hr-2026-09-04-defence-procurement","croatia","克罗地亚","2026-09-04","克罗地亚批准近7亿欧元军备投资计划","政治","克罗地亚政府公布未来三年近7亿欧元军备投资，包括18套韩国K239火箭系统、反坦克装备、阵风战机升级和雷达现代化。\n\n金额为采购计划总额，不等于当日已经全部交付。","HRT","https://glashrvatske.hrt.hr/en/politics/government-plans-to-invest-almost-700-million-in-the-croatian-armed-forces-12891400","en / zh","manual","fiscal"],
  ["hr-2026-09-04-beijing-zagreb-flight","croatia","克罗地亚","2026-09-04","北京经布加勒斯特至萨格勒布航线开通","对华经贸","中国国际航空首个北京经布加勒斯特至萨格勒布航班抵达，载有120名乘客。\n\n该航线计划每周运行三班；开航不被解释为已经产生贸易或投资增长。","HRT","https://glashrvatske.hrt.hr/en/economy/the-first-flight-from-beijing-arrives-in-zagreb-12891440","en / zh","manual","China"],

  ["at-2026-08-21-drought-climate-deal","austria","奥地利","2026-08-21","奥地利政府就2.4亿欧元旱灾援助与气候法达成协议","能源","奥地利执政联盟同意为农业提供2.4亿欧元旱灾援助，并推进气候法及2040年气候中和路线图。\n\n具体实施路线图计划在2027年底前制定。","ORF","https://orf.at/stories/3439871/","de / zh","manual","fiscal"],
  ["at-2026-08-24-styria-drought-criticism","austria","奥地利","2026-08-24","施蒂里亚州长批评联邦旱灾援助力度","政治","施蒂里亚州长马里奥·库纳塞克批评联邦旱灾援助，认为现有安排不足。\n\n这一判断明确归因于州长，不作为平台对援助效果的评价。","ORF Steiermark","https://steiermark.orf.at/stories/3368209/","de / zh","manual","fiscal"],
  ["at-2026-09-01-august-inflation","austria","奥地利","2026-09-01","奥地利8月通胀初值升至3.2%","经济","奥地利统计局初值显示8月CPI同比上涨3.2%、环比上涨0.6%，能源价格同比上涨10%。\n\n协调口径HICP同比为2.9%。","ORF / Statistics Austria","https://orf.at/stories/3440842/","de / zh","manual","macro"],
  ["at-2026-08-25-carbon-storage-bill","austria","奥地利","2026-08-25","奥地利推进工业碳捕集与封存立法","能源","奥地利政府拟解除工业碳捕集与封存的普遍禁令，相关法案当时仍在执政联盟内部协调。\n\n水泥行业预计广泛工业应用最早可能在2040年前后出现，该判断属于行业预期。","ORF","https://orf.at/stories/3440180/","de / zh","manual","industrial_policy"],
  ["at-2026-08-26-public-procurement-industry","austria","奥地利","2026-08-26","奥地利拟以公共采购支持本国及欧洲产业","经济","奥地利经济部长提出强化公共采购中的本国及欧洲增加值考量，并计划在年底前制定指引。\n\n政府引用研究称公共部门每年采购约670亿欧元；指引尚未等同于完成采购规则修法。","ORF","https://orf.at/stories/3440288/","de / zh","manual","industrial_policy"],
  ["at-2026-08-28-energy-cost-increase","austria","奥地利","2026-08-28","奥地利能源机构估算油气涨价增加数十亿欧元成本","能源","奥地利能源机构估算，过去六个月油气价格上涨给家庭和企业带来数十亿欧元额外成本。\n\n估算将天然气和柴油成本分别列示，不被解释为宏观经济因果估计。","ORF","https://orf.at/stories/3440492/","de / zh","manual","energy"],
  ["at-2026-09-02-japan-economic-security","austria","奥地利","2026-09-02","奥地利与日本商定加强经济安全和高技术合作","区域","奥地利与日本外长在维也纳会晤，讨论供应链、机器人和人工智能等经济安全与高技术合作。\n\n双方表达继续促进企业和研究机构交流的意向，未登记为已实现投资。","ORF","https://orf.at/stories/3441016/","de / zh","manual","FDI"],
  ["at-2026-09-02-emissions-rise","austria","奥地利","2026-09-02","奥地利环境署估算2025年温室气体排放增加0.7%","能源","奥地利环境署近期预测显示，2025年温室气体排放约增加0.7%，达到约6700万吨二氧化碳当量。\n\n该数据为初步估算，环境署指出实现2030年欧盟目标仍需追加措施。","ORF","https://orf.at/stories/3440995/","de / zh","manual","energy"],
  ["at-2026-09-03-ai-public-administration","austria","奥地利","2026-09-03","奥地利议会审议公共管理自动化修法","政治","奥地利行政程序修法拟允许数字对话系统协助申请，并在特定条件下自动作出部分行政决定。\n\n公民组织和法律界对透明度、人类监督及救济提出意见，法案仍处议会程序。","ORF","https://orf.at/stories/3440894/","de / zh","manual","industrial_policy"],
  ["at-2026-09-04-eu-budget-position","austria","奥地利","2026-09-04","奥地利欧盟事务部长要求压缩欧盟长期预算","欧盟","奥地利欧盟事务部长克劳迪娅·鲍尔在欧盟会议上主张削减下一期长期预算，并将安全列为优先事项。\n\n该内容为奥方谈判立场，不代表欧盟成员国已经达成预算协议。","ORF","https://orf.at/stories/3441184/","de / zh","manual","EU_funds"],

  ["de-2026-08-25-vw-china-strategy","germany","德国","2026-08-25","大众评估将中国开发模式用于德国生产","对华经贸","大众在中国以更短开发周期和高度自动化生产较低成本车型，德国地方政府提出将部分中国开发成果用于德国生产。\n\n该建议尚不等于大众已决定调整德国工厂产品。","Tagesschau","https://www.tagesschau.de/wirtschaft/unternehmen/vw-china-136.html","de / zh","manual","China"],
  ["de-2026-09-01-leipzig-drone-russia","germany","德国","2026-09-01","德国认定俄罗斯应对莱比锡无人机袭击企图负责","政治","德国政府认定俄罗斯应对莱比锡/哈雷机场的爆炸物无人机袭击企图负责，并讨论追加制裁。\n\n归责基于德国安全机构当时掌握的证据，俄罗斯否认相关指控。","Tagesschau","https://www.tagesschau.de/inland/innenpolitik/drohnen-flughafen-bundesregierung-100.html","de / zh","manual","regional"],
  ["de-2026-09-05-berlin-cyber-data","germany","德国","2026-09-05","黑客公布柏林行政系统遭窃数据","政治","德国信息安全部门确认柏林行政系统遭网络攻击后，部分被窃数据被公开。\n\n调查仍在进行，本记录不推断攻击者身份。","Tagesschau","https://www.tagesschau.de/inland/regional/berlin/hackergruppe-berlin-daten-veroeffentlichung-100.html","de / zh","manual","industrial_policy"],
  ["de-2026-09-05-grid-sabotage","germany","德国","2026-09-05","德国警方追查多地电网破坏未遂事件","能源","警方调查勃兰登堡、北莱茵-威斯特法伦和萨克森州变电设施附近的破坏未遂事件。\n\n一名嫌疑人在信件中声称负责，警方当时仍在追捕。","Tagesschau","https://www.tagesschau.de/inland/fahndung-sabotage-stromnetz-100.html","de / zh","manual","energy"],
  ["de-2026-09-05-babyboomer-growth","germany","德国","2026-09-05","德国婴儿潮一代退休加大劳动力与增长压力","经济","德国统计部门预计到2040年将有1330万劳动年龄人口达到法定退休年龄，相当于当前就业人口约30%。\n\n报道讨论劳动力参与、移民与生产率等政策选项，不作为增长预测。","Tagesschau","https://www.tagesschau.de/wirtschaft/arbeitsmarkt/babyboomer-rente-deutschland-wachstum-100.html","de / zh","manual","macro"],
  ["de-2026-09-05-saxony-anhalt-economy","germany","德国","2026-09-05","萨克森-安哈尔特州经济差距成为州选举议题","经济","萨克森-安哈尔特州8月失业率为8.2%，高于全国6.5%，工资和可支配收入也相对较低。\n\n报道同时指出较低住房和劳动力成本可能构成区位优势。","Tagesschau","https://www.tagesschau.de/wirtschaft/konjunktur/sachsen-anhalt-wirtschaft-wahl-afd-100.html","de / zh","manual","macro"],

  ["ro-2026-08-28-government-consultations","romania","罗马尼亚","2026-08-28","尼库绍尔·丹宣布重启组阁磋商","政治","罗马尼亚总统尼库绍尔·丹表示将于9月1日重启总理人选磋商，并预计可形成稳定多数。\n\n截至报道时罗马尼亚仍由看守政府履职，表态不等于组阁已经完成。","Romania Insider","https://www.romania-insider.com/president-consultations-govt-restart-sept-2026","en / zh","manual","election"],
  ["ro-2026-09-02-rrf-absorption","romania","罗马尼亚","2026-09-02","罗马尼亚预计复苏基金赠款吸收率超过90%","欧盟","看守总理伊利耶·博洛让表示，罗马尼亚预计复苏基金赠款吸收率达92.7%，贷款吸收率超过95%。\n\n计算基于缩减后的约200亿欧元总额度；第六次付款申请尚未提交。","Romania Insider","https://www.romania-insider.com/romania-resilience-facility-absorbtion-rates-sept-2026","en / zh","manual","EU_funds"],

  ["sk-2026-08-20-july-unemployment","slovakia","斯洛伐克","2026-08-20","斯洛伐克7月登记失业率升至4.07%","经济","斯洛伐克劳动部门称7月可就业求职者占劳动年龄人口比率为4.07%，较6月上升0.1个百分点。\n\n月末登记可就业求职者为146346人。","TASR","https://etasr.sk/article/23627668","sk / zh","manual","macro"],
  ["sk-2026-08-24-jess-share-valuation","slovakia","斯洛伐克","2026-08-24","斯洛伐克将复核JESS核能公司股权估值","能源","斯洛伐克总理罗伯特·菲佐表示，将由另一家国际咨询机构复核安永对捷克电力公司所持JESS股份的1.89亿欧元估值。\n\n复核决定不代表股权交易价格已经最终确定。","TASR","https://etasr.sk/article/23640188","en / zh","manual","energy"],
  ["sk-2026-08-27-zvs-supply-chain-allegation","slovakia","斯洛伐克","2026-08-27","斯洛伐克反对党要求调查国防企业供应链利润流向","政治","进步斯洛伐克党议员称，部分国有的ZVS Holding通过供应链安排损失利润，并要求审查。\n\n相关内容属于反对党指控，记录不把指控视为已经证实的审计结论。","TASR","https://etasr.sk/article/23648256","en / zh","manual","industrial_policy"],

  ["rs-2026-08-20-snap-election-dates","serbia","塞尔维亚","2026-08-20","武契奇称塞尔维亚或于10月提前选举","政治","塞尔维亚总统亚历山大·武契奇表示，提前议会选举可能安排在10月18日或25日。\n\n日期是总统当时提出的选项，不按已正式发布选举令处理。","Reuters","https://www.reuters.com/world/serbia-hold-snap-elections-oct-18-or-25-president-vucic-says-2026-08-20/","en / zh","manual","election"],
  ["rs-2026-09-04-eu-kos-cancels-trip","serbia","塞尔维亚","2026-09-04","欧盟委员因姆拉迪奇纪念安排取消塞尔维亚行程","欧盟","欧盟扩大事务委员玛尔塔·科斯因塞尔维亚方面拟举行拉特科·姆拉迪奇纪念活动而取消访问。\n\n该决定反映欧盟与塞尔维亚关系中的政治分歧，不推断入盟谈判长期结果。","Reuters","https://www.reuters.com/world/eu-commissioner-kos-cancels-trip-serbia-after-planned-tribute-mladic-2026-09-04/","en / zh","manual","regional"],
];

export const weeklyNews20260905: WeeklyNewsItem[] = rows.map(([id,countrySlug,countryZh,weekOf,title,topic,summary,sourceLabel,sourceUrl,language,sourceStatus,eventType]) => ({
  id,countrySlug,countryZh,weekOf,title,topic,summary,sourceLabel,sourceUrl,language,eventType,
  dataStatus:"verified",actor:sourceLabel,direction:"neutral",intensity:null,affectedIndicators:[],affectedModels:[],relatedProjectIds:[],relatedDriverIds:[],duration:"pending",
  confidence:sourceStatus === "official" ? "high" : "medium",sourceStatus,codingStatus:"partial",entersModel:false,
}));
